<style>
    select.gray {
        color: #111;
    }
    option {
        color: #111;
    }
    .grayout option:first-child {
        color: #111;
    }
    select.select-idioma {
        color: #111;
        border-radius: 10px;
        margin: 0;
        margin-bottom: 0%;
        margin-top: 0%;
        border-radius: 5px;
        vertical-align: top;
        padding-top: 2vh;
        padding-bottom: 2vh;
        padding: 1.2vh;
        background-color: #fff;
        background-image: url("https://upload.wikimedia.org/wikipedia/commons/4/4b/Feather-arrows-chevron-down.svg");
        background-position: 97% center;
        background-position: right 0px center;
        background-repeat: no-repeat;
        background-size: 18px;
        border: 1px solid #ccc;
        -webkit-appearance: button;
        -webkit-border-radius: 3px;
        -webkit-padding-end: 30px;
        -webkit-padding-start: 8px;
        -webkit-user-select: none;
        -moz-appearance: none;
        font-size: 1vw;
        overflow: hidden;
        text-overflow: ellipsis;
        color: #111;
        white-space: nowrap;
        width: 100%;
        transition: border 300ms;
    }
    @media screen and (max-width: 580px) {
        select.select-idioma {
            color: #111;
            border-radius: 10px;
            margin: 0;
            margin-bottom: 0%;
            margin-top: 0%;
            border-radius: 2px !important;
            vertical-align: top;
            padding-top: 2vh;
            padding-bottom: 2vh;
            padding: 1.2vh;
            background-color: #fff;
            background-image: none;
            background-position: 97% center;
            background-position: right 0px center;
            background-repeat: no-repeat;
            background-size: 18px;
            border: 1px solid #999;
            -webkit-appearance: button;
            -webkit-border-radius: 3px;
            -webkit-padding-end: 30px;
            -webkit-padding-start: 8px;
            -webkit-user-select: none;
            -moz-appearance: none;
            font-size: 1em;
            overflow: hidden;
            text-overflow: ellipsis;
            color: #555;
            white-space: nowrap;
            width: 100%;
            transition: border 300ms;
        }
    }

</style>