<style>
    .custom-file{
        margin-bottom: 6px;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Importar Promociones</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/promocion/guardar-importar-promociones" data-callback="respuesta(response, 'Promociones Importado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Empresa</label>
            <span>
                <select class="select2 form-control" name="idempresas">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->empresas as $item):?>
                    <option value="<?php echo $item['idempresas'];?>"><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Archivo <span class="importante">(*)</span></label>
            <div class="custom-file">
                <input type="file" name="archivo" class="custom-file-input adjuntar" onchange="this.nextElementSibling.textContent = this.value">
                <label class="custom-file-label">Elija el archivo</label>
            </div>
            <a download="Formato Promociones" href="formatos/promociones.xlsx">
                <div class="alert alert-warning" role="alert">
                    <strong>Click para descargar formato excel</strong>
                </div>
            </a>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Importar Promociones</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            idempresas: {
                required: true
            },
            archivo: {
                required: true
            }
        },
        messages: {
            idempresas: {
                required: 'Por favor, seleccione la empresa'
            },
            archivo: {
                required: 'Por favor, seleccione el archivo'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>