<!-- start Google Analytics -->
<?php if( $this->layout()->dominio == "tecnosalud.com.pe" ) : ?>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177219604-16"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-177219604-16');
</script>
<?php endif; ?>
<!-- end Google Analytics -->

<!-- begin olark code -->
<?php if( $this->layout()->dominio == "tecnosalud.com.pe" ) : ?>
<!-- begin olark code -->

<!-- end olark code -->
<?php endif; ?>
<!-- end olark code -->

<!-- start fullstory code -->
<?php if( $this->layout()->dominio == "tecnosalud.com.pe" ) : ?>

<?php endif; ?>
<!-- end fullstory code -->