<div class="modal-header">
    <h4 class="modal-title">¿Estas seguro que desea eliminar al usuario?</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/sistema/confirmar-eliminar-usuario?idusuario=<?php echo $this->idusuario; ?>" data-callback="respuesta(response, 'Usuario eliminado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="titulo-eliminar"><?php echo $this->nombres." ".$this->apellido_paterno." ".$this->apellido_materno; ?></div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit" data-id-form='validar_formulario'>Eliminar Usuario</button>
    </div>
</form>