<div class="text-center error-box">
    <br><br>
    <h2 class="font-xl"><strong><i class="fa fa-fw fa-warning fa-lg text-danger fa-5x"></i><br/><br/> Página no encontrada</strong></h2>
    <br />
    <p class="lead">La ruta a la que usted desea entrar no se ha encontrado, por favor utilice una ruta válida.</p>
    <br><br><br>
    <div class="row">
        <div class="col-sm-12">
            <a class="btn btn-lg btn-primary"  href="/"> Regresar a Dashboard</a>
        </div>
    </div>
</div>