<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Perfil</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="form_editar_perfil" data-accion="/panel/guardar-editar-perfil" data-callback="respuestaPerfil(response)" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Imagen de Perfil</label>
            <div class="contenedor-imagen"> 
                <div style="background-image: url('<?php echo $this->img_user_perfil?>');" class="imagen"></div>
                <div class="btn btn-dark btn-sm waves-effect waves-themed" id="btn_cambiar_img_perfil"><i class="fas fa-upload"></i> Cambiar Imagen</div>
                <input type="file" id="img_perfil" onchange="cambiarImagen();" class="hidden" name="img_perfil" accept=".jpg,.jpeg,.png" style="display: none;">
            </div>
        </div>
        <div class="form-group">
            <label class="form-label">Correo Electrónico</label>
            <span>
                <input type="text" name="correo_electronico" class="form-control" value="<?php echo $this->dataUsuario->email?>" readonly>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Nombres</label>
            <span>
                <input type="text" name="nombres" class="form-control" value="<?php echo $this->dataUsuario->nombres?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Paterno</label>
            <span>
                <input type="text" name="apellido_paterno" class="form-control" value="<?php echo $this->dataUsuario->apellido_paterno?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Materno</label>
            <span>
                <input type="text" name="apellido_materno" class="form-control" value="<?php echo $this->dataUsuario->apellido_materno?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Teléfono</label>
            <span>
                <input type="text" name="telefono" class="form-control" value="<?php echo $this->dataUsuario->telefono?>">
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-key"></i>&nbsp;Cambiar Contraseña</h2>
        </div>
        <div class="form-group">
            <label class="form-label">Contraseña</label>
            <span>
                <input type="password" name="contrasena" id="contrasena" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Repita Contraseña</label>
            <span>
                <input type="password" name="repita_contrasena" class="form-control">
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='form_editar_perfil'>Guardar Cambios</button>
    </div>
</form>

<script>

    $("#btn_cambiar_img_perfil").click(function () {
        $("#img_perfil").click();
    });

    function cambiarImagen() {
        var file = document.getElementById('img_perfil').files[0];
        var reader = new FileReader();
        reader.onload = function (e) {
            $('.contenedor-imagen .imagen').css({'background-image':'url('+e.target.result+')'});
        };
        reader.readAsDataURL(file);
    }

    $("#form_editar_perfil").validate({
        rules: {
            nombres: {
                required: true
            },
            correo_electronico: {
                required: true,
                email: true
            },
            apellido_paterno: {
                required: true
            },
            contrasena: {
                required: false,
                minlength: 6,
                maxlength: 20
            },
            repita_contrasena: {
                required: false,
                minlength: 6,
                maxlength: 20,
                equalTo: '#contrasena'
            }
        },
        messages: {
            nombres: {
                required: 'Por favor, ingrese los nombres'
            },
            correo_electronico: {
                required: 'Por favor, ingrese el correo electrónico',
                email: 'Por favor, ingrese una dirección de correo electrónico válida'
            },
            apellido_paterno: {
                required: 'Por favor, ingrese el apellido paterno'
            },
            contrasena: {
                required: 'Por favor, ingrese la contraseña',
                minlength: 'Por favor, introduzca al menos 6 caracteres',
                maxlength: 'Por favor, introduzca no más de 20 caracteres'
            },
            repita_contrasena: {
                required: 'Por favor, ingrese la contraseña una vez más',
                equalTo: 'Por favor, ingrese la misma contraseña que el anterior',
                minlength: 'Por favor, introduzca al menos 6 caracteres',
                maxlength: 'Por favor, introduzca no más de 20 caracteres'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

    function respuestaPerfil(response) {
        if(response.result == 'success'){
            $(".sesion-nombres").text(response.datausuario['nombres']+" "+response.datausuario['apellido_paterno']+" "+response.datausuario['apellido_materno']);
            $(".sesion-imagen").attr("src", "img/avatars/"+response.datausuario['token']+".jpg");
            alerta('Sus datos se actualizaron correctamente.', 'success');
            ocultarModal();
        }
    }

</script>