<?php if(!empty($this->botones)) : $i = 1; foreach($this->botones as $item) : ?>
<div class="row-botones">
    <div class="panel-hdr">
        <h2><i class="fas fa-fw fa-lg fa-align-justify"></i>&nbsp;Botón <?php echo $i; ?></h2>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-8">
                <label class="form-label">Icono</label>
                <div class="contenedor-imagen-personalizado">
                    <img src="<?php echo ( $item['icono'] !== 'img/boton-no-found.png' ) ? "paginas/botones/".$item['icono']: 'img/boton-no-found.png'; ?>" width="41" class="imagen" alt="">
                    <input type="hidden" name="icono_hash[]" value="<?php echo $item['icono']; ?>">
                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 150 px de ancho y 150 px de alto</div>
                    <button type="button" class="btn btn-dark btn-block btn-sm cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Subir Imagen</button>
                    <input type="file" data-width="150" data-height="150" onchange="cambiarImagenDimension(this, event);" class="hidden" name="icono[]" accept=".jpg,.jpeg,.png" style="display: none;">
                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-12">
                        <label class="form-label">Color Fondo</label>
                        <span>
                            <input type="color" name="color_fondo[]" class="form-control" value="<?php echo $item['color_fondo']; ?>">
                        </span>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label">Color Texto</label>
                        <span>
                            <input type="color" name="color_texto[]" class="form-control" value="<?php echo $item['color_texto']; ?>">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-6">
                <label class="form-label">Texto</label>
                <span>
                    <input type="text" name="texto[]" class="form-control" value="<?php echo $item['texto']; ?>" placeholder="Ingrese el nombre del botón">
                </span>
            </div>
            <div class="col-md-6">
                <label class="form-label">Página Redirección</label>
                <span>
                    <select class="select2 form-control" name="pagina_redireccion[]">
                        <option value="" selected="select">Seleccionar...</option>
                        <?php foreach($this->menus as $menu):?>
                        <option value="<?php echo $menu['hash_url']; ?>" <?php if( $item['pagina_redireccion'] === $menu['hash_url'] ) { echo "selected='select'"; } ?>><?php echo $menu['nombre'];?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
    </div>
</div>
<?php $i++; endforeach; endif; ?>