<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="theme-color" content="#00b3ce" />
        <meta http-equiv="Content-Language" content="es" />
        <meta name="description" content="LA ÚNICA FERIA DEL SECTOR INMOBILIARIO EN EL PERÚ, y es organizada por la Centro Virtual de Convenciones." />
        <meta name="Keywords" content="Ferias virtuales, recorridos, convenciones" />
        <title>FERIA VIRTUAL INMOBILIRIA - LA ÚNICA FERIA VIRTUAL DEL SECTOR INMOBILIARIO EN EL PERÚ.</title>
        <base href="<?php echo $this->layout()->base_url; ?>" />
        <link href="https://centrovirtualdeconvenciones.com/expohogar.png" rel="shortcut icon" title="feria-2020" />
        <meta name="viewport" content="width=480" initial-scale="1" />
        <link rel="alternate" hreflang="es" href="https://dragmastands.com/" />
        <link href="plantillas/css/style.css" rel="stylesheet" type="text/css" />
        <!-- CSS [INICIO] -->
        <link rel="stylesheet" media="screen, print" href="plantillas/css/fontawesome.min.css" />
        <link href="plantillas/css/base.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" media="screen, print" href="css/formplugins/select2/select2.bundle.css" />
        <link rel="stylesheet" media="screen, print" href="css/notifications/toastr/toastr.css" />
        <!-- CSS [FIN] -->
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
        <script type="text/javascript" src="plantillas/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="plantillas/js/jquery.popupoverlay.js"></script>
        <!-- JS [INICIO] -->
        <script src="js/formplugins/select2/select2.bundle.js"></script>
        <script src="js/notifications/toastr/toastr.js"></script>
        <script src="plantillas/js/bootstrap-tooltip.js"></script>
        <!-- JS [FIN] -->
    </head>

    <body style="overflow-y: scroll;">
        <div class="se-pre-con"></div>

        <div class="header-index" style="display: none;">
            <a href="javascript:void(0)" class="logos">
                <!-- <img src="plantillas/imagenes/LOGO-EXPOPOSTGRADOS.svg" width="60%" /> -->
            </a>
            <div class="logos-2">
                <img src="plantillas/imagenes/logocentrovirtual.png" width="15%" />
                <a href="hall-planos.html" style="visibility: hidden;">INICIA FERIA</a>
            </div>
            <div class="logos-3">
                <a href="registrar-visitante.html" style="visibility: hidden;"><i class="fas fa-user"></i>&nbsp;REGISTRARME</a>
                <a href="#" class="ingresar_open"><i class="fas fa-sign-in-alt"></i>&nbsp;INGRESAR</a>
            </div>

            <a href="#" data-drawer-trigger aria-controls="drawer-name" aria-expanded="false" class="button-menu"><img src="plantillas/imagenes/menu-01.svg" width="68%" /></a>
        </div>

        <a href="#" class="claim-book" style="display: none;"><img src="plantillas/imagenes/reclamaciones.svg" width="40%" /> </a>

        <section class="registro-home">
            <a class="show-hide" href="#" onclick="smooth()">VER REGISTRO</a>

            <div class="white-form-enter" id="show">
                <div class="fondo-logo-form imagen" data-id="imagen_logo" data-width="319" data-height="190" data-accept=".jpg,.jpeg,.png">
                    <img src="<?php echo ( isset($this->configuracion['imagen_logo'])) ? 'paginas/registro-presencial/'.$this->configuracion['imagen_logo']['hash'] : 'img/plantillas/registro-presencial/imagen_logo.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="bottom" title="La dimensión recomendada es de 319 px de ancho y 190 px de alto" alt="">
                </div>

                <!-- <center><h2>Completa tus datos con tu D.N.I. y tus nombres*</h2></center> -->

                <h3 style="display: none;">1. Datos del usuario</h3>

                <div class="all-2">
                    <div class="first-form-2" style="margin-left: 25%;">
                        <center>
                            <p><i class="fas fa-user"></i>&nbsp;Ingresa tu D.N.I *</p>
                        </center>
                    </div>
                    <div class="second-form-2" style="display: none;">
                        <p><i class="fas fa-user"></i>&nbsp;Apellidos*</p>
                    </div>
                </div>

                <div class="all">
                    <div class="first-form">
                        <!-- <p class="hidden-responsive"><i class="fas fa-user"></i>&nbsp;Completa tus datos rellenando con tu D.N.I y tus nombres *</p> -->
                        <input type="text" name="dni" style="width: 100%;" id="txtbusca" class="campos-contacto-home" placeholder="DNI*" autofocus disabled="" />
                    </div>

                    <div class="salida"></div>

                    <div class="all-2">
                        <div class="first-form-2">
                        </div>
                        <div class="second-form-2" style="display: none;">
                            <p><i class="fas fa-key"></i>&nbsp;Contraseña*</p>
                        </div>
                    </div>
                    <input type="hidden" name="proceso" id="proceso" />
                </div>
            </div>

            <div class="avion" style="display: none;"><img src="plantillas/imagenes/zep.png" width="300" /></div>

            <section class="drawer" id="drawer-name" data-drawer-target>
                <div class="drawer__overlay" data-drawer-close tabindex="1"></div>

                <div class="drawer__wrapper">
                    <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
                    <div class="drawer__content">
                        <ul class="menu-responsive">
                            <a href="hall-planos-1.html">INICIAR FERIA</a>
                            <a href="hall.html"><img src="plantillas/imagenes/iconos-menu-01.svg" />Recepción</a>
                            <a href="hall-planos-1.html"><img src="plantillas/imagenes/iconos-menu-02.svg" />Zona Ferial</a>
                            <a href="conferencias.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Conferencias</a>
                            <a href="#"><i class="fas fa-search"></i>&nbsp;Buscar por distrito</a>
                        </ul>
                        <div class="logo-responsive-ccl"></div>
                    </div>
                </div>
            </section>

            <?php if( isset($this->configuracion['imagen_fondo_movil']) ) : ?>
            <style>
                @media screen and (max-width: 580px) {
                    .registro-home .slide.active {
                        background-image: url('<?php echo 'paginas/registro-presencial/'.$this->configuracion['imagen_fondo_movil']['hash']; ?>') !important;
                    }
                }
            </style>
            <?php endif; ?>

            <div class="imagen-fondo-movil" data-width="500" data-height="881" data-accept=".jpg,.jpeg,.png"></div>

            <div class="slide active imagen-fondo" data-width="2000" data-height="1109" data-accept=".jpg,.jpeg,.png" style="background-image: url(<?php echo(isset($this->configuracion[ 'imagen_fondo' ]))?'paginas/registro-presencial/'.$this->configuracion['imagen_fondo']['hash']:'img/plantillas/registro-presencial/imagen_fondo.jpg';?>);"
            ></div>

            <div id="ingresar" class="well">
                <div class="modal-contents-2">
                    <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>" method="post" class="form">
                        <div class="welcome-form">
                            <h1>Ingresar a Evento</h1>
                            <p>Digita los datos para poder ingresar</p>
                        </div>

                        <div class="titulos-form">Nombre de Usuario</div>
                        <div class="user line-input">
                            <i class="fas fa-user"></i>
                            <label class="lnr lnr-user"></label>
                            <input type="text" placeholder="Nombre Usuario*" name="usuario" />
                        </div>
                        <div class="titulos-form">Contraseña de Acceso</div>
                        <div class="password line-input">
                            <i class="fas fa-key"></i>
                            <label class="lnr lnr-lock"></label>
                            <input type="password" placeholder="Contraseña*" name="clave" />
                        </div>
                        <a href="#" class="titulos-form-forgot">Olvidaste tu Constraseña</a>
                        <?php if(!empty($error)):?>
                        <div class="mensaje">
                            <?php echo $error; ?>
                        </div>
                        <?php endif; ?>
                        <button type="submit">INGRESAR<label class="lnr lnr-chevron-right"></label></button>
                    </form>
                </div>
            </div>
        </section>
    </body>
    <script>
        $(document).ready(function () {
            $("#txtbusca").keyup(function () {
                var parametros = "txtbusca=" + $(this).val();
                $.ajax({
                    data: parametros,
                    url: "salida_1.php",
                    type: "post",
                    beforeSend: function () {},
                    success: function (response) {
                        $(".salida").html(response);
                    },
                    error: function () {
                        alert("error");
                    },
                });
            });
        });
    </script>
    <script>
        /*!
         * Based on articles on
         * https://gomakethings.com
         */

        var drawer = function () {
            /**
             * Element.closest() polyfill
             * https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
             */
            if (!Element.prototype.closest) {
                if (!Element.prototype.matches) {
                    Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
                }
                Element.prototype.closest = function (s) {
                    var el = this;
                    var ancestor = this;
                    if (!document.documentElement.contains(el)) return null;
                    do {
                        if (ancestor.matches(s)) return ancestor;
                        ancestor = ancestor.parentElement;
                    } while (ancestor !== null);
                    return null;
                };
            }

            //
            // Settings
            //
            var settings = {
                speedOpen: 50,
                speedClose: 350,
                activeClass: "is-active",
                visibleClass: "is-visible",
                selectorTarget: "[data-drawer-target]",
                selectorTrigger: "[data-drawer-trigger]",
                selectorClose: "[data-drawer-close]",
            };

            //
            // Methods
            //

            // Toggle accessibility
            var toggleAccessibility = function (event) {
                if (event.getAttribute("aria-expanded") === "true") {
                    event.setAttribute("aria-expanded", false);
                } else {
                    event.setAttribute("aria-expanded", true);
                }
            };

            // Open Drawer
            var openDrawer = function (trigger) {
                // Find target
                var target = document.getElementById(trigger.getAttribute("aria-controls"));

                // Make it active
                target.classList.add(settings.activeClass);

                // Make body overflow hidden so it's not scrollable
                document.documentElement.style.overflow = "hidden";

                // Toggle accessibility
                toggleAccessibility(trigger);

                // Make it visible
                setTimeout(function () {
                    target.classList.add(settings.visibleClass);
                }, settings.speedOpen);
            };

            // Close Drawer
            var closeDrawer = function (event) {
                // Find target
                var closestParent = event.closest(settings.selectorTarget),
                    childrenTrigger = document.querySelector('[aria-controls="' + closestParent.id + '"');

                // Make it not visible
                closestParent.classList.remove(settings.visibleClass);

                // Remove body overflow hidden
                document.documentElement.style.overflow = "";

                // Toggle accessibility
                toggleAccessibility(childrenTrigger);

                // Make it not active
                setTimeout(function () {
                    closestParent.classList.remove(settings.activeClass);
                }, settings.speedClose);
            };

            // Click Handler
            var clickHandler = function (event) {
                // Find elements
                var toggle = event.target,
                    open = toggle.closest(settings.selectorTrigger),
                    close = toggle.closest(settings.selectorClose);

                // Open drawer when the open button is clicked
                if (open) {
                    openDrawer(open);
                }

                // Close drawer when the close button (or overlay area) is clicked
                if (close) {
                    closeDrawer(close);
                }

                // Prevent default link behavior
                if (open || close) {
                    event.preventDefault();
                }
            };

            // Keydown Handler, handle Escape button
            var keydownHandler = function (event) {
                if (event.key === "Escape" || event.keyCode === 27) {
                    // Find all possible drawers
                    var drawers = document.querySelectorAll(settings.selectorTarget),
                        i;

                    // Find active drawers and close them when escape is clicked
                    for (i = 0; i < drawers.length; ++i) {
                        if (drawers[i].classList.contains(settings.activeClass)) {
                            closeDrawer(drawers[i]);
                        }
                    }
                }
            };

            //
            // Inits & Event Listeners
            //
            document.addEventListener("click", clickHandler, false);
            document.addEventListener("keydown", keydownHandler, false);
        };

        drawer();
    </script>

    <script>
        $(document).ready(function () {
            $("#ingresar").popup({
                transition: "all 0.3s",
                closebutton: true,
            });
        });
    </script>

    <script>
        function smooth() {
            if ($("#show").is(":visible")) {
                $("#show").hide("1000");
            } else {
                $("#show").show("1000");
            }
        }
    </script>

    <script>
        // Wait for window load
        $(window).load(function () {
            // Animate loader off screen
            $(".se-pre-con").fadeOut("slow");
        });
    </script>

    <?php echo $this->partial('partial/paginas/opciones', ['planes_paginas'=> $this->planes_paginas, 'idferias'=> $this->feria['idferias'], 'idpaginas'=> $this->pagina['idpaginas'], 'pagina'=> $this->pagina, 'configuracion'=> $this->configuracion]); ?>

    <form id="form_pagina">
        <input type="hidden" name="plantilla" value="registro-presencial" />
        <input type="hidden" name="idpaginas" value="<?php echo $this->pagina['idpaginas']; ?>" />
        <input type="hidden" name="idferias" value="<?php echo $this->feria['idferias']; ?>" />
        <input type="hidden" name="idpaginasferias" value="<?php echo $this->idpaginasferias; ?>" />
        <input type="file" id="imagen_logo" name="imagen_logo" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_fondo" name="imagen_fondo" onchange="subirFondo(this.files, this, 'imagen-fondo')" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_fondo_movil" name="imagen_fondo_movil" onchange="subirFondo(this.files, this, 'imagen-fondo-movil')" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="fondo_video" name="fondo_video" style="display: none;" onchange="subirFondoVideo(this.files, this, 'btn-fondo-video')" accept=".mp4" />
        <input type="hidden" id="activar_fondo_video" name="activar_fondo_video" value="false">
    </form>

    <script>

        $("a").click(function (e) {
            e.preventDefault();
        });

        $(".img.img, .btn-cambiar-fondo, .btn-cambiar-fondo-movil").tooltip();

        $(".imagen").click(function () {
            let idinputfile = $(this).attr("data-id");
            $("#" + idinputfile).click();
        });

        $(".btn-cambiar-fondo").click(function () {
            $("#imagen_fondo").click();
        });

        $(".btn-cambiar-fondo-movil").click(function () {
            $("#imagen_fondo_movil").click();
        });

        $(".btn-fondo-video").click(function () {
            $("#fondo_video").click();
        });

        var _URL = window.URL || window.webkitURL;

        function subirArchivo(files, obj) {
            let reader = new FileReader();
            let idinputfile = $(obj).attr("id");
            let contenedor = $("[data-id='" + idinputfile + "']");
            let imgContenedor = contenedor.find(".img");
            let file = files[0];
            let img_width = parseInt(contenedor.attr("data-width"));
            let img_height = parseInt(contenedor.attr("data-height"));
            let accept = contenedor.attr("data-accept");
            reader.readAsDataURL(file);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    var width = this.width;
                    var height = this.height;
                    if (width != img_width || height != img_height) {
                        alerta('La imagen no cumple con las dimensiones recomendadas.', 'danger');
                        $(obj).val('');
                        imgContenedor.attr("src", "img/no-imagen.jpg");
                        return false;
                    }
                    contenedor.find("img.img").attr("src", e.target.result);
                };
            };
        }

        function subirFondo(files, obj, clase) {
            let contenedor = $("."+clase);
            let reader = new FileReader();
            let file = files[0];
            let img_width = parseInt(contenedor.attr("data-width"));
            let img_height = parseInt(contenedor.attr("data-height"));
            let accept = contenedor.attr("data-accept");
            reader.readAsDataURL(file);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    var width = this.width;
                    var height = this.height;
                    if (width != img_width || height != img_height) {
                        alerta('La imagen no cumple las dimensiones recomendadas. Por favor, intentelo otra vez.', 'warning');
                        $(obj).val('');
                        contenedor.css({ "background-image": "url(img/no-imagen.jpg)" });
                        return false;
                    }
                    console.log(e.target.result);
                    contenedor.css({ "background-image": "url(" + e.target.result + ")" });
                };
            };
        }

        function subirFondoVideo(files, obj, classFondoVideo) {
            document.querySelector(`.${classFondoVideo}`).innerHTML = `<i class="fas fa-images"></i> Cambiar Video`;
        }

        $(".btn-guardar-cambios").click(function () {
            let _this = $(this);
            let form = $("form#form_pagina");
            var data = new FormData(form[0]);
            _this.attr("disabled", "");
            _this.find("i").hide();
            $.ajax({
                url: "cliente/guardar-parametros-pagina",
                type: "POST",
                data: data,
                contentType: false,
                processData: false,
                success: function (response) {
                    //console.log( response );
                    if (response.result == "success") {
                        form.find("input[name='idpaginasferias']").val(response.idpaginasferias);
                        _this.find("i").show();
                        _this.find("span").text("Guardar Cambios");
                        alerta("Los datos se guardaron correctamente.", "success");
                    }
                    _this.removeAttr("disabled", "");
                },
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener(
                        "progress",
                        function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round((evt.loaded / evt.total) * 100) + "%";
                                //console.log( percentComplete );
                                _this.find("span").text(percentComplete + " Guardando Cambios...");
                            }
                        },
                        false
                    );
                    return xhr;
                },
                error: function () {
                    alerta("Se han detectado errores de red intente en otro momento.", "danger");
                    _this.removeAttr("disabled", "");
                },
            });
        });
    </script>
</html>