<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="theme-color" content="#00b3ce" />
        <meta http-equiv="Content-Language" content="es" />
        <meta name="description" content="LA ÚNICA FERIA DEL SECTOR INMOBILIARIO EN EL PERÚ, y es organizada por la Centro Virtual de Convenciones." />
        <meta name="Keywords" content="Ferias virtuales, recorridos, convenciones" />
        <title>FERIA VIRTUAL INMOBILIRIA - LA ÚNICA FERIA VIRTUAL DEL SECTOR INMOBILIARIO EN EL PERÚ.</title>
        <base href="<?php echo $this->layout()->base_url; ?>" />
        <link href="https://centrovirtualdeconvenciones.com/expohogar.png" rel="shortcut icon" title="feria-2020" />
        <meta name="viewport" content="width=480" initial-scale="1" />
        <link href="plantillas/css/style.css" rel="stylesheet" type="text/css" />
        <!-- CSS [INICIO] -->
        <link rel="stylesheet" media="screen, print" href="plantillas/css/fontawesome.min.css" />
        <link href="plantillas/css/base.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" media="screen, print" href="css/formplugins/select2/select2.bundle.css" />
        <link rel="stylesheet" media="screen, print" href="css/notifications/toastr/toastr.css" />
        <!-- CSS [FIN] -->
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <script type="text/javascript" src="plantillas/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="plantillas/js/jquery.popupoverlay.js"></script>
        <!-- JS [INICIO] -->
        <script src="js/formplugins/select2/select2.bundle.js"></script>
        <script src="js/notifications/toastr/toastr.js"></script>
        <script src="plantillas/js/bootstrap-tooltip.js"></script>
        <!-- JS [FIN] -->
    </head>
    <body>
        <div class="se-pre-con"></div>
        <div class="header-index">
            <a href="javascript:void(0)" class="logos">
                <img src="ferias/logo/<?php echo $this->feria['hash_logo']; ?>" width="60%" />
            </a>
            <div class="logos-2">
            <img src="plantillas/imagenes/logocentrovirtual.png" width="15%" />
                <img src="clientes/logo/<?php echo $this->cliente['hash_logo']; ?>" width="20%" />
            </div>
            <div class="logos-3" style="display: none;">
                <a href="registro.html"><i class="fas fa-user"></i>&nbsp;INGRESAR AL EVENTO</a>
            </div>
            <a href="#" data-drawer-trigger aria-controls="drawer-name" aria-expanded="false" class="button-menu"><img src="plantillas/imagenes/menu-01.svg" width="68%" /></a>
        </div>
        <section class="home">
            <div class="avion">
                <div class="zep-otro">
                    <img src="plantillas/imagenes/zep.png" />
                    <div class="zep-fondo"><img src="ferias/logo/<?php echo $this->feria['hash_logo']; ?>" /></div>
                </div>
            </div>

            <section class="drawer" id="drawer-name" data-drawer-target>
                <div class="drawer__overlay" data-drawer-close tabindex="1"></div>

                <div class="drawer__wrapper">
                    <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
                    <div class="drawer__content">
                        <ul class="menu-responsive">
                            <a href="#">INICIAR FERIA</a>
                            <a href="#"><img src="plantillas/imagenes/iconos-menu-01.svg" alt="">Recepción</a>
                            <a href="#"><img src="plantillas/imagenes/iconos-menu-02.svg" alt="">Zona Ferial</a>
                            <a href="#"><img src="plantillas/imagenes/iconos-menu-03.svg" alt="">Conferencias</a>
                            <a href="#"><i class="fas fa-search"></i>&nbsp;Buscar por Distrito</a>
                        </ul>
                        <div class="logo-responsive-ccl">
                            <img src="plantillas/imagenes/logo-ccl-white-01.svg" width="45%" alt="">
                        </div>
                    </div>
                </div>
            </section>

            <div class="caja-ads-evento">
                <div class="caja-ads-evento-centro">
                    <div class="ads-1 imagen" data-id="imagen_izquierda_1" data-width="600" data-height="341">
                        <img src="<?php echo ( isset($this->configuracion['imagen_izquierda_1'])) ? 'paginas/home/'.$this->configuracion['imagen_izquierda_1']['hash'] : 'img/plantillas/home/imagen_izquierda_1.jpg'; ?>" class="img" data-accept=".jpg,.jpeg,.png" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 600 px de ancho y 341 px de alto" alt="">
                    </div>
                    <div class="espacio-evento"></div>
                    <div class="ads-2 imagen" data-id="imagen_tv" data-width="700" data-height="359" data-accept=".jpg,.jpeg,.png">
                        <img src="<?php echo ( isset($this->configuracion['imagen_tv'])) ? 'paginas/home/'.$this->configuracion['imagen_tv']['hash'] : 'img/plantillas/home/imagen_tv.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 700 px de ancho y 359 px de alto" alt="">
                    </div>
                    <div class="espacio-evento"></div>
                    <div class="ads-3 imagen" data-id="imagen_derecha_3" data-width="600" data-height="341" data-accept=".jpg,.jpeg,.png">
                        <img src="<?php echo ( isset($this->configuracion['imagen_derecha_3'])) ? 'paginas/home/'.$this->configuracion['imagen_derecha_3']['hash'] : 'img/plantillas/home/imagen_derecha_3.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 600 px de ancho y 341 px de alto" alt="">
                    </div>
                </div>
            </div>

            <div class="cajas-artes-index">
                <div class="center-cajas">
                    <div class="arte-1-index">
                        <img src="plantillas/imagenes/totems.png" alt="">

                        <div class="arte-1-fondo imagen" data-id="imagen_izquierda_2" data-width="124" data-height="214" data-accept=".jpg,.jpeg,.png">
                            <a href="#">
                                <img src="<?php echo ( isset($this->configuracion['imagen_izquierda_2'])) ? 'paginas/home/'.$this->configuracion['imagen_izquierda_2']['hash'] : 'img/plantillas/home/imagen_izquierda_2.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 124 px de ancho y 214 px de alto" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="espacito-index"></div>
                    <div class="arte-2-index">
                        <a href="#"><img src="plantillas/imagenes/totems.png" alt=""></a>

                        <div class="arte-2-fondo imagen" data-id="imagen_izquierda_3" data-width="124" data-height="214" data-accept=".jpg,.jpeg,.png">
                            <a href="#">
                                <img src="<?php echo ( isset($this->configuracion['imagen_izquierda_3'])) ? 'paginas/home/'.$this->configuracion['imagen_izquierda_3']['hash'] : 'img/plantillas/home/imagen_izquierda_3.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 124 px de ancho y 214 px de alto" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="espacito-index-2"></div>
                    <div class="arte-3-index">
                        <img src="plantillas/imagenes/totems-2.png" alt="">
                        <div class="arte-3-fondo imagen" data-id="imagen_derecha_1" data-width="124" data-height="214" data-accept=".jpg,.jpeg,.png">
                            <a href="#">
                                <img src="<?php echo ( isset($this->configuracion['imagen_derecha_1'])) ? 'paginas/home/'.$this->configuracion['imagen_derecha_1']['hash'] : 'img/plantillas/home/imagen_derecha_1.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 124 px de ancho y 214 px de alto" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="espacito-index"></div>
                    <div class="arte-4-index">
                        <img src="plantillas/imagenes/totems-2.png" alt="">
                        <div class="arte-4-fondo imagen" data-id="imagen_derecha_2" data-width="124" data-height="214" data-accept=".jpg,.jpeg,.png">
                            <a href="#">
                                <img src="<?php echo ( isset($this->configuracion['imagen_derecha_2'])) ? 'paginas/home/'.$this->configuracion['imagen_derecha_2']['hash'] : 'img/plantillas/home/imagen_derecha_2.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="top" title="La dimensión recomendada es de 124 px de ancho y 214 px de alto" alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <?php if( isset($this->configuracion['imagen_fondo_movil']) ) : ?>
            <style>
                @media screen and (max-width: 580px) {
                    .home .slide.active {
                        background-image: url('<?php echo 'paginas/home/'.$this->configuracion['imagen_fondo_movil']['hash']; ?>') !important;
                    }
                }
            </style>
            <?php endif; ?>

            <div class="imagen-fondo-movil" data-width="500" data-height="881" data-accept=".jpg,.jpeg,.png"></div>

            <div class="slide active imagen-fondo" data-width="2000" data-height="1109" data-accept=".jpg,.jpeg,.png" style="background-image: url(<?php echo(isset($this->configuracion['imagen_fondo']))?'paginas/home/'.$this->configuracion['imagen_fondo']['hash']:'img/plantillas/home/imagen_fondo.jpg';?>);"></div>

            <div id="ingresar" class="well">
                <div class="modal-contents-2">
                    <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>" method="post" class="form">
                        <div class="welcome-form">
                            <h1>Ingresar a Evento</h1>
                            <p>Digita los datos para poder ingresar</p>
                        </div>
                        <div class="titulos-form">Nombre de Usuario</div>
                        <div class="user line-input">
                            <i class="fas fa-user"></i>
                            <label class="lnr lnr-user"></label>
                            <input type="text" placeholder="Nombre Usuario*" name="usuario" />
                        </div>
                        <div class="titulos-form">Contraseña de Acceso</div>
                        <div class="password line-input">
                            <i class="fas fa-key"></i>
                            <label class="lnr lnr-lock"></label>
                            <input type="password" placeholder="Contraseña*" name="clave" />
                        </div>
                        <a href="#" class="titulos-form-forgot">Olvidaste tu Constraseña</a>
                        <?php if(!empty($error)):?>
                        <div class="mensaje">
                            <?php echo $error; ?>
                        </div>
                        <?php endif; ?>
                        <button type="submit">INGRESAR<label class="lnr lnr-chevron-right"></label></button>
                    </form>
                </div>
            </div>
        </section>

        <div class="navbar">
            <div class="boton" style="animation-delay: 1.3s; display: none;">
                <img src="plantillas/imagenes/new-icons-01.svg" width="32%" />
                <a href="recepcion.html"> RECEPCIÓN</a>
            </div>

            <div class="boton" style="animation-delay: 1.5s; display: none;">
                <img src="plantillas/imagenes/new-icons-03.svg" width="32%" />
                <a href="hall.html">EXPOSITORES</a>
            </div>

            <div class="boton" style="animation-delay: 1.7s; display: none;">
                <img src="plantillas/imagenes/new-icons-02.svg" width="32%" />
                <a href="conferencias.html">CONFERENCIAS</a>
            </div>
        </div>
    </body>
    <script>
        /*!
         * Based on articles on
         * https://gomakethings.com
         */

        var drawer = function () {
            /**
             * Element.closest() polyfill
             * https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
             */
            if (!Element.prototype.closest) {
                if (!Element.prototype.matches) {
                    Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
                }
                Element.prototype.closest = function (s) {
                    var el = this;
                    var ancestor = this;
                    if (!document.documentElement.contains(el)) return null;
                    do {
                        if (ancestor.matches(s)) return ancestor;
                        ancestor = ancestor.parentElement;
                    } while (ancestor !== null);
                    return null;
                };
            }

            //
            // Settings
            //
            var settings = {
                speedOpen: 50,
                speedClose: 350,
                activeClass: "is-active",
                visibleClass: "is-visible",
                selectorTarget: "[data-drawer-target]",
                selectorTrigger: "[data-drawer-trigger]",
                selectorClose: "[data-drawer-close]",
            };

            //
            // Methods
            //

            // Toggle accessibility
            var toggleAccessibility = function (event) {
                if (event.getAttribute("aria-expanded") === "true") {
                    event.setAttribute("aria-expanded", false);
                } else {
                    event.setAttribute("aria-expanded", true);
                }
            };

            // Open Drawer
            var openDrawer = function (trigger) {
                // Find target
                var target = document.getElementById(trigger.getAttribute("aria-controls"));

                // Make it active
                target.classList.add(settings.activeClass);

                // Make body overflow hidden so it's not scrollable
                document.documentElement.style.overflow = "hidden";

                // Toggle accessibility
                toggleAccessibility(trigger);

                // Make it visible
                setTimeout(function () {
                    target.classList.add(settings.visibleClass);
                }, settings.speedOpen);
            };

            // Close Drawer
            var closeDrawer = function (event) {
                // Find target
                var closestParent = event.closest(settings.selectorTarget),
                    childrenTrigger = document.querySelector('[aria-controls="' + closestParent.id + '"');

                // Make it not visible
                closestParent.classList.remove(settings.visibleClass);

                // Remove body overflow hidden
                document.documentElement.style.overflow = "";

                // Toggle accessibility
                toggleAccessibility(childrenTrigger);

                // Make it not active
                setTimeout(function () {
                    closestParent.classList.remove(settings.activeClass);
                }, settings.speedClose);
            };

            // Click Handler
            var clickHandler = function (event) {
                // Find elements
                var toggle = event.target,
                    open = toggle.closest(settings.selectorTrigger),
                    close = toggle.closest(settings.selectorClose);

                // Open drawer when the open button is clicked
                if (open) {
                    openDrawer(open);
                }

                // Close drawer when the close button (or overlay area) is clicked
                if (close) {
                    closeDrawer(close);
                }

                // Prevent default link behavior
                if (open || close) {
                    event.preventDefault();
                }
            };

            // Keydown Handler, handle Escape button
            var keydownHandler = function (event) {
                if (event.key === "Escape" || event.keyCode === 27) {
                    // Find all possible drawers
                    var drawers = document.querySelectorAll(settings.selectorTarget),
                        i;

                    // Find active drawers and close them when escape is clicked
                    for (i = 0; i < drawers.length; ++i) {
                        if (drawers[i].classList.contains(settings.activeClass)) {
                            closeDrawer(drawers[i]);
                        }
                    }
                }
            };

            //
            // Inits & Event Listeners
            //
            document.addEventListener("click", clickHandler, false);
            document.addEventListener("keydown", keydownHandler, false);
        };

        drawer();
    </script>

    <script>
        $(document).ready(function () {
            $("#ingresar").popup({
                transition: "all 0.3s",
                closebutton: true,
            });
        });
    </script>

    <script>
        // Wait for window load
        $(window).load(function () {
            // Animate loader off screen
            $(".se-pre-con").fadeOut("slow");
        });
    </script>

    <?php echo $this->partial('partial/paginas/opciones', ['planes_paginas'=> $this->planes_paginas, 'idferias'=> $this->feria['idferias'], 'idpaginas'=> $this->pagina['idpaginas'], 'pagina'=> $this->pagina, 'configuracion'=> $this->configuracion]); ?>

    <form id="form_pagina">
        <input type="hidden" name="plantilla" value="home" />
        <input type="hidden" name="idpaginas" value="<?php echo $this->pagina['idpaginas']; ?>" />
        <input type="hidden" name="idferias" value="<?php echo $this->feria['idferias']; ?>" />
        <input type="hidden" name="idpaginasferias" value="<?php echo $this->idpaginasferias; ?>" />
        <input type="file" id="imagen_izquierda_1" name="imagen_izquierda_1" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_izquierda_2" name="imagen_izquierda_2" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_izquierda_3" name="imagen_izquierda_3" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_derecha_1" name="imagen_derecha_1" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_derecha_2" name="imagen_derecha_2" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_derecha_3" name="imagen_derecha_3" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_tv" name="imagen_tv" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_fondo" name="imagen_fondo" onchange="subirFondo(this.files, this, 'imagen-fondo')" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_fondo_movil" name="imagen_fondo_movil" onchange="subirFondo(this.files, this, 'imagen-fondo-movil')" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="fondo_video" name="fondo_video" style="display: none;" onchange="subirFondoVideo(this.files, this, 'btn-fondo-video')" accept=".mp4" />
        <input type="hidden" id="activar_fondo_video" name="activar_fondo_video" value="false">
    </form>

    <script>
        $("a").click(function (e) {
            e.preventDefault();
        });

        $(".img.img, .btn-cambiar-fondo, .btn-cambiar-fondo-movil").tooltip();

        $(".imagen").click(function () {
            let idinputfile = $(this).attr("data-id");
            $("#" + idinputfile).click();
        });

        $(".btn-cambiar-fondo").click(function () {
            $("#imagen_fondo").click();
        });

        $(".btn-cambiar-fondo-movil").click(function () {
            $("#imagen_fondo_movil").click();
        });

        $(".btn-fondo-video").click(function () {
            $("#fondo_video").click();
        });

        var _URL = window.URL || window.webkitURL;

        function subirArchivo(files, obj) {
            let reader = new FileReader();
            let idinputfile = $(obj).attr("id");
            let contenedor = $("[data-id='" + idinputfile + "']");
            let imgContenedor = contenedor.find(".img");
            let file = files[0];
            let img_width = parseInt(contenedor.attr("data-width"));
            let img_height = parseInt(contenedor.attr("data-height"));
            let accept = contenedor.attr("data-accept");
            reader.readAsDataURL(file);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    var width = this.width;
                    var height = this.height;
                    if (width != img_width || height != img_height) {
                        alerta('La imagen no cumple con las dimensiones recomendadas.', 'danger');
                        $(obj).val('');
                        imgContenedor.attr("src", "img/no-imagen.jpg");
                        return false;
                    }
                    contenedor.find("img.img").attr("src", e.target.result);
                };
            };
        }

        function subirFondo(files, obj, clase) {
            let contenedor = $("."+clase);
            let reader = new FileReader();
            let file = files[0];
            let img_width = parseInt(contenedor.attr("data-width"));
            let img_height = parseInt(contenedor.attr("data-height"));
            let accept = contenedor.attr("data-accept");
            reader.readAsDataURL(file);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    var width = this.width;
                    var height = this.height;
                    if (width != img_width || height != img_height) {
                        alerta('La imagen no cumple las dimensiones recomendadas. Por favor, intentelo otra vez.', 'warning');
                        $(obj).val('');
                        contenedor.css({ "background-image": "url(img/no-imagen.jpg)" });
                        return false;
                    }
                    contenedor.css({ "background-image": "url(" + e.target.result + ")" });
                };
            };
        }

        function subirFondoVideo(files, obj, classFondoVideo) {
            document.querySelector(`.${classFondoVideo}`).innerHTML = `<i class="fas fa-images"></i> Cambiar Video`;
        }

        $(".btn-guardar-cambios").click(function () {
            let _this = $(this);
            let form = $("form#form_pagina");
            var data = new FormData(form[0]);
            _this.attr("disabled", "");
            _this.find("i").hide();
            $.ajax({
                url: "cliente/guardar-parametros-pagina",
                type: "POST",
                data: data,
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.result == "success") {
                        form.find("input[name='idpaginasferias']").val(response.idpaginasferias);
                        _this.find("i").show();
                        _this.find("span").text("Guardar Cambios");
                        alerta("Los datos se guardaron correctamente.", "success");
                    }
                    _this.removeAttr("disabled", "");
                },
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener(
                        "progress",
                        function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round((evt.loaded / evt.total) * 100) + "%";
                                _this.find("span").text(percentComplete + " Guardando Cambios...");
                            }
                        },
                        false
                    );
                    return xhr;
                },
                error: function () {
                    alerta("Se han detectado errores de red intente en otro momento.", "danger");
                    _this.removeAttr("disabled", "");
                },
            });
        });
    </script>
</html>