<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="theme-color" content="#00b3ce" />
        <meta http-equiv="Content-Language" content="es" />
        <meta name="description" content="LA ÚNICA FERIA DEL SECTOR INMOBILIARIO EN EL PERÚ, y es organizada por la Centro Virtual de Convenciones." />
        <meta name="Keywords" content="Ferias virtuales, recorridos, convenciones" />
        <title>FERIA VIRTUAL INMOBILIRIA - LA ÚNICA FERIA VIRTUAL DEL SECTOR INMOBILIARIO EN EL PERÚ.</title>
        <base href="<?php echo $this->layout()->base_url; ?>" />
        <link href="https://centrovirtualdeconvenciones.com/expohogar.png" rel="shortcut icon" title="feria-2020" />
        <meta name="viewport" content="width=480" initial-scale="1" />
        <link rel="alternate" hreflang="es" href="https://dragmastands.com/" />
        <link href="plantillas/css/style.css" rel="stylesheet" type="text/css" />
        <!-- CSS [INICIO] -->
        <link rel="stylesheet" media="screen, print" href="plantillas/css/fontawesome.min.css">
        <link href="plantillas/css/base.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" media="screen, print" href="css/formplugins/select2/select2.bundle.css">
        <link rel="stylesheet" media="screen, print" href="css/notifications/toastr/toastr.css">
        <!-- CSS [FIN] -->
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <script type="text/javascript" src="plantillas/js/jquery-1.10.2.min.js"></script>
        <!-- JS [INICIO] -->
        <script src="js/formplugins/select2/select2.bundle.js"></script>
        <script src="js/notifications/toastr/toastr.js"></script>
        <script src="plantillas/js/bootstrap-tooltip.js"></script>
        <!-- JS [FIN] -->
    </head>

    <body>
        <div class="se-pre-con"></div>

        <div class="header-index">
            <a href="javascript:void(0)" class="logos">
                <img src="ferias/logo/<?php echo $this->feria['hash_logo']; ?>" width="60%" alt="">
            </a>
            <div class="logos-2">
                <img src="plantillas/imagenes/logocentrovirtual.png" width="15%" alt="">
                <img src="clientes/logo/<?php echo $this->cliente['hash_logo']; ?>" width="20%" alt="">
            </div>
            <div class="logos-3">
                <a href="registro.html" style="display: none;"><i class="fas fa-user"></i>&nbsp;INGRESAR AL EVENTO</a>
            </div>

            <a href="#" data-drawer-trigger aria-controls="drawer-name" aria-expanded="false" class="button-menu"><img src="plantillas/imagenes/menu-01.svg" width="68%" alt=""></a>
        </div>
        <section class="home-conferencias">
            <section class="drawer" id="drawer-name" data-drawer-target>
                <div class="drawer__overlay" data-drawer-close tabindex="-1"></div>
                <div class="drawer__wrapper">
                    <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
                    <div class="drawer__content">
                        <ul class="menu-responsive">
                            <a href="hall-planos-1.html">INICIAR FERIA</a>
                            <a href="hall.html"><img src="plantillas/imagenes/iconos-menu-01.svg" />Recepción</a>
                            <a href="hall-planos-1.html"><img src="plantillas/imagenes/iconos-menu-02.svg" />Expoferia</a>
                            <a href="conferencias.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Conferencias</a>
                            <a href="rueda-negocios.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Rueda de Negocios</a>
                        </ul>
                        <div class="logo-responsive-ccl">
                            <img src="plantillas/imagenes/logo-ccl-white-01.svg" width="45%" alt="">
                        </div>
                    </div>
                </div>
            </section>

            <?php if( isset($this->configuracion['imagen_fondo_movil']) ) : ?>
            <style>
                @media screen and (max-width: 580px) {
                    .home-conferencias .slide.active {
                        background-image: url('<?php echo 'paginas/hall-conferencias/'.$this->configuracion['imagen_fondo_movil']['hash']; ?>') !important;
                    }
                }
            </style>
            <?php endif; ?>

            <div class="imagen-fondo-movil" data-width="500" data-height="881" data-accept=".jpg,.jpeg,.png"></div>

            <div class="slide active imagen-fondo" data-width="2000" data-height="1109" data-accept=".jpg,.jpeg,.png" style="background-image: url(<?php echo ( isset($this->configuracion['imagen_fondo'])) ? 'paginas/hall-conferencias/'.$this->configuracion['imagen_fondo']['hash'] : 'img/plantillas/hall-conferencias/imagen_fondo.jpg'; ?>)">
                <div class="logo-evento-conferencias">
                    <div class="center-logo"><img src="ferias/logo/<?php echo $this->feria['hash_logo']; ?>" alt=""></div>
                </div>

                <div class="cajas-artes-conferencias">
                    <div class="arte-3-conferencias imagen banners"
                        data-idbanner-url="<?php echo (isset($this->configuracion['banner_opciones_url']['imagen_derecha_1']))?$this->configuracion['banner_opciones_url']['imagen_derecha_1']:'';?>" 
                        data-idbanner="<?php echo (isset($this->configuracion['banner_opciones']['imagen_derecha_1']))?$this->configuracion['banner_opciones']['imagen_derecha_1']:'';?>"
                        data-id="imagen_derecha_1" data-width="232" data-height="533" data-accept=".jpg,.jpeg,.png">
                        <a href="javascript:void(0)"><img src="<?php echo ( isset($this->configuracion['imagen_derecha_1'])) ? 'paginas/hall-conferencias/'.$this->configuracion['imagen_derecha_1']['hash'] : 'img/plantillas/hall-conferencias/imagen_derecha_1.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="bottom" title="La dimensión recomendada es de 232 px de ancho y 533 px de alto" alt=""></a>
                    </div>

                    <div class="espacito-conferencias"></div>

                    <div class="arte-2-conferencias imagen banners"
                        data-idbanner-url="<?php echo (isset($this->configuracion['banner_opciones_url']['imagen_derecha_2']))?$this->configuracion['banner_opciones_url']['imagen_derecha_2']:'';?>" 
                        data-idbanner="<?php echo (isset($this->configuracion['banner_opciones']['imagen_derecha_2']))?$this->configuracion['banner_opciones']['imagen_derecha_2']:'';?>"
                        data-id="imagen_derecha_2" data-width="232" data-height="533" data-accept=".jpg,.jpeg,.png">
                        <a href="javascript:void(0)"><img src="<?php echo ( isset($this->configuracion['imagen_derecha_2'])) ? 'paginas/hall-conferencias/'.$this->configuracion['imagen_derecha_2']['hash'] : 'img/plantillas/hall-conferencias/imagen_derecha_2.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="bottom" title="La dimensión recomendada es de 232 px de ancho y 533 px de alto" alt=""></a>
                    </div>

                    <div class="espacito-conferencias"></div>

                    <div class="arte-1-conferencias imagen banners"
                        data-idbanner-url="<?php echo (isset($this->configuracion['banner_opciones_url']['imagen_derecha_3']))?$this->configuracion['banner_opciones_url']['imagen_derecha_3']:'';?>" 
                        data-idbanner="<?php echo (isset($this->configuracion['banner_opciones']['imagen_derecha_3']))?$this->configuracion['banner_opciones']['imagen_derecha_3']:'';?>"
                        data-id="imagen_derecha_3" data-width="232" data-height="533" data-accept=".jpg,.jpeg,.png">
                        <a href="javascript:void(0)"> <img src="<?php echo ( isset($this->configuracion['imagen_derecha_3'])) ? 'paginas/hall-conferencias/'.$this->configuracion['imagen_derecha_3']['hash'] : 'img/plantillas/hall-conferencias/imagen_derecha_3.jpg'; ?>" class="img" data-toggle="tooltip" data-placement="bottom" title="La dimensión recomendada es de 232 px de ancho y 533 px de alto" alt=""></a>
                    </div>
                </div>
                <div class="navbar-conference" style="position:relative;display:none;">
                    <div class="boton-conference" style="animation-delay: 1s;"><span>AUDITORIO VIRTUAL</span></div>
                    <span class="lista-opciones">
                        <?php if(isset($this->configuracion['hall_conferencias_opciones']) && !empty($this->configuracion['hall_conferencias_opciones'])): ?>
                        <?php
                            $dataOpciones = $this->configuracion['hall_conferencias_opciones'];
                            foreach($dataOpciones as $opcion) :
                                $nombreImagen = '';
                                if( $opcion['key'] == 'virtual_conferencias' )$nombreImagen = 'iconos-menu-03.svg';
                                else if( $opcion['key'] == 'virtual_zona' )$nombreImagen = 'iconos-menu-agenda.svg';
                                else $nombreImagen = 'iconos-menu-01.svg';
                        ?>
                        <div class="boton-conference" data-key="<?php echo $opcion['key']; ?>" style="animation-delay: 1.3s;">
                            <div class="marco-boton"><img src="plantillas/imagenes/<?php echo $nombreImagen; ?>" width="30%" alt=""></div>
                            <a href="javascript:void(0)"><?php echo $opcion['value']; ?></a>
                            <input type="hidden" data-banner="url" value="<?php echo $opcion['url']; ?>">
                        </div>
                        <?php endforeach; else : ?>
                        <div class="boton-conference" data-key="virtual_conferencias" style="animation-delay: 1.3s;">
                            <div class="marco-boton"><img src="plantillas/imagenes/iconos-menu-03.svg" width="30%" alt=""></div>
                            <a href="javascript:void(0)">PROG. CONFERENCIAS</a>
                            <input type="hidden" data-banner="url" value="cronogramas">
                        </div>
                        <div class="boton-conference" data-key="virtual_zona" style="animation-delay: 1.6s;">
                            <div class="marco-boton"><img src="plantillas/imagenes/iconos-menu-agenda.svg" width="30%" alt=""></div>
                            <a href="javascript:void(0)">ZONA FERIAL</a>
                            <input type="hidden" data-banner="url" value="zonas/1">
                        </div>
                        <div class="boton-conference" data-key="virtual_auditorio" style="animation-delay: 1.9s;">
                            <div class="marco-boton"><img src="plantillas/imagenes/iconos-menu-01.svg" width="30%" alt=""></div>
                            <a href="javascript:void(0)">AUDITORIO</a>
                            <input type="hidden" data-banner="url" value="auditorio">
                        </div>
                        <div class="boton-conference" data-key="buscador" style="animation-delay: 1.9s;">
                            <div class="marco-boton"><img src="plantillas/imagenes/iconos-menu-01.svg" width="30%" alt=""></div>
                            <a href="javascript:void(0)">BUSCADOR</a>
                            <input type="hidden" data-banner="url" value="busqueda-productos">
                        </div>
                        <?php endif; ?>
                    </span>
                    <div class="auditorio-opciones pop-up" href="/cliente/paginas-auditorio-opciones">
                        <div>Cambiar Orden</div>
                    </div>
                </div>
            </div>
        </section>

        <div class="navbar">
            <div class="boton" style="animation-delay: 1.3s; display: none;">
                <img src="plantillas/imagenes/new-icons-01.svg" width="32%" alt="">
                <a href="recepcion.html"> RECEPCIÓN</a>
            </div>

            <div class="boton" style="animation-delay: 1.5s; display: none;">
                <img src="plantillas/imagenes/new-icons-03.svg" width="32%" alt="">
                <a href="hall.html">PLANO</a>
            </div>
        </div>

        <script>
            /*!
             * Based on articles on
             * https://gomakethings.com
             */

            var drawer = function () {
                /**
                 * Element.closest() polyfill
                 * https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
                 */
                if (!Element.prototype.closest) {
                    if (!Element.prototype.matches) {
                        Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
                    }
                    Element.prototype.closest = function (s) {
                        var el = this;
                        var ancestor = this;
                        if (!document.documentElement.contains(el)) return null;
                        do {
                            if (ancestor.matches(s)) return ancestor;
                            ancestor = ancestor.parentElement;
                        } while (ancestor !== null);
                        return null;
                    };
                }

                //
                // Settings
                //
                var settings = {
                    speedOpen: 50,
                    speedClose: 350,
                    activeClass: "is-active",
                    visibleClass: "is-visible",
                    selectorTarget: "[data-drawer-target]",
                    selectorTrigger: "[data-drawer-trigger]",
                    selectorClose: "[data-drawer-close]",
                };

                //
                // Methods
                //

                // Toggle accessibility
                var toggleAccessibility = function (event) {
                    if (event.getAttribute("aria-expanded") === "true") {
                        event.setAttribute("aria-expanded", false);
                    } else {
                        event.setAttribute("aria-expanded", true);
                    }
                };

                // Open Drawer
                var openDrawer = function (trigger) {
                    // Find target
                    var target = document.getElementById(trigger.getAttribute("aria-controls"));

                    // Make it active
                    target.classList.add(settings.activeClass);

                    // Make body overflow hidden so it's not scrollable
                    document.documentElement.style.overflow = "hidden";

                    // Toggle accessibility
                    toggleAccessibility(trigger);

                    // Make it visible
                    setTimeout(function () {
                        target.classList.add(settings.visibleClass);
                    }, settings.speedOpen);
                };

                // Close Drawer
                var closeDrawer = function (event) {
                    // Find target
                    var closestParent = event.closest(settings.selectorTarget),
                        childrenTrigger = document.querySelector('[aria-controls="' + closestParent.id + '"');

                    // Make it not visible
                    closestParent.classList.remove(settings.visibleClass);

                    // Remove body overflow hidden
                    document.documentElement.style.overflow = "";

                    // Toggle accessibility
                    toggleAccessibility(childrenTrigger);

                    // Make it not active
                    setTimeout(function () {
                        closestParent.classList.remove(settings.activeClass);
                    }, settings.speedClose);
                };

                // Click Handler
                var clickHandler = function (event) {
                    // Find elements
                    var toggle = event.target,
                        open = toggle.closest(settings.selectorTrigger),
                        close = toggle.closest(settings.selectorClose);

                    // Open drawer when the open button is clicked
                    if (open) {
                        openDrawer(open);
                    }

                    // Close drawer when the close button (or overlay area) is clicked
                    if (close) {
                        closeDrawer(close);
                    }

                    // Prevent default link behavior
                    if (open || close) {
                        event.preventDefault();
                    }
                };

                // Keydown Handler, handle Escape button
                var keydownHandler = function (event) {
                    if (event.key === "Escape" || event.keyCode === 27) {
                        // Find all possible drawers
                        var drawers = document.querySelectorAll(settings.selectorTarget),
                            i;

                        // Find active drawers and close them when escape is clicked
                        for (i = 0; i < drawers.length; ++i) {
                            if (drawers[i].classList.contains(settings.activeClass)) {
                                closeDrawer(drawers[i]);
                            }
                        }
                    }
                };

                //
                // Inits & Event Listeners
                //
                document.addEventListener("click", clickHandler, false);
                document.addEventListener("keydown", keydownHandler, false);
            };

            drawer();
        </script>
    </body>
    <script>
        // Wait for window load
        $(window).load(function () {
            // Animate loader off screen
            $(".se-pre-con").fadeOut("slow");
        });
    </script>

<?php echo $this->partial('partial/paginas/opciones', ['planes_paginas'=> $this->planes_paginas, 'idferias'=> $this->feria['idferias'], 'idpaginas'=> $this->pagina['idpaginas'], 'pagina'=> $this->pagina, 'configuracion'=> $this->configuracion]); ?>

<form id="form_pagina">
    <input type="hidden" name="plantilla" value="hall-conferencias">
    <input type="hidden" name="idpaginas" value="<?php echo $this->pagina['idpaginas']; ?>">
    <input type="hidden" name="idferias" value="<?php echo $this->feria['idferias']; ?>">
    <input type="hidden" name="idpaginasferias" value="<?php echo $this->idpaginasferias; ?>">
    <input type="file" id="imagen_derecha_1" name="imagen_derecha_1" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png">
    <input type="file" id="imagen_derecha_2" name="imagen_derecha_2" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png">
    <input type="file" id="imagen_derecha_3" name="imagen_derecha_3" onchange="subirArchivo(this.files, this)" style="display: none;" accept=".jpg,.jpeg,.png">
    <input type="file" id="imagen_fondo" name="imagen_fondo" onchange="subirFondo(this.files, this, 'imagen-fondo')" style="display: none;" accept=".jpg,.jpeg,.png">
    <input type="hidden" name="hall_conferencias_opciones" value='<?php echo ( !empty($this->configuracion['hall_conferencias_opciones']) ) ? json_encode($this->configuracion['hall_conferencias_opciones']) : '[]'; ?>'>
    <input type="hidden" name="banner_opciones" value='<?php echo ( !empty($this->configuracion['banner_opciones']) ) ? json_encode($this->configuracion['banner_opciones']) : '[]'; ?>'>
    <input type="hidden" name="banner_opciones_url" value='<?php echo ( !empty($this->configuracion['banner_opciones_url']) ) ? json_encode($this->configuracion['banner_opciones_url']) : '[]'; ?>'>
    <input type="file" id="imagen_fondo_movil" name="imagen_fondo_movil" onchange="subirFondo(this.files, this, 'imagen-fondo-movil')" style="display: none;" accept=".jpg,.jpeg,.png" />
    <input type="file" id="fondo_video" name="fondo_video" style="display: none;" onchange="subirFondoVideo(this.files, this, 'btn-fondo-video')" accept=".mp4" />
    <input type="hidden" id="activar_fondo_video" name="activar_fondo_video" value="false">
</form>

<script>

    $("a").click(function (e) {
        e.preventDefault();
    });

    $(".img.img, .btn-cambiar-fondo, .btn-cambiar-fondo-movil").tooltip();

    $(".imagen").click(function () {
        let idinputfile = $(this).attr("data-id");
        $("#" + idinputfile).click();
    });

    $(".btn-cambiar-fondo").click(function () {
        $("#imagen_fondo").click();
    });

    $(".btn-cambiar-fondo-movil").click(function () {
        $("#imagen_fondo_movil").click();
    });

    $(".btn-fondo-video").click(function () {
        $("#fondo_video").click();
    });

    var _URL = window.URL || window.webkitURL;

    function subirArchivo(files, obj) {
        let reader = new FileReader();
        let idinputfile = $(obj).attr("id");
        let contenedor = $("[data-id='" + idinputfile + "']");
        let imgContenedor = contenedor.find(".img");
        let file = files[0];
        let img_width = parseInt(contenedor.attr("data-width"));
        let img_height = parseInt(contenedor.attr("data-height"));
        let accept = contenedor.attr("data-accept");
        reader.readAsDataURL(file);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alerta('La imagen no cumple con las dimensiones recomendadas.', 'danger');
                    $(obj).val('');
                    imgContenedor.attr("src", "img/no-imagen.jpg");
                    return false;
                }
                contenedor.find("img.img").attr("src", e.target.result);
            };
        };
    }

    function subirFondo(files, obj, clase) {
        let contenedor = $("."+clase);
        let reader = new FileReader();
        let file = files[0];
        let img_width = parseInt(contenedor.attr("data-width"));
        let img_height = parseInt(contenedor.attr("data-height"));
        let accept = contenedor.attr("data-accept");
        reader.readAsDataURL(file);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alerta('La imagen no cumple las dimensiones recomendadas. Por favor, intentelo otra vez.', 'warning');
                    $(obj).val('');
                    contenedor.css({ "background-image": "url(img/no-imagen.jpg)" });
                    return false;
                }
                console.log(e.target.result);
                contenedor.css({ "background-image": "url(" + e.target.result + ")" });
            };
        };
    }

    function subirFondoVideo(files, obj, classFondoVideo) {
        document.querySelector(`.${classFondoVideo}`).innerHTML = `<i class="fas fa-images"></i> Cambiar Video`;
    }

    $(".btn-guardar-cambios").click(function(){
        let _this = $(this);
        let form = $("form#form_pagina");
        var data = new FormData(form[0]);
        _this.attr("disabled", "");
        _this.find("i").hide();
        $.ajax({
            url: 'cliente/guardar-parametros-pagina',
            type: 'POST',
            data: data,
            contentType: false,
            processData: false,
            success: function (response) {
                //console.log( response );
                if( response.result == 'success' ) {
                    form.find("input[name='idpaginasferias']").val(response.idpaginasferias);
                    _this.find("i").show();
                    _this.find("span").text('Guardar Cambios');
                    alerta('Los datos se guardaron correctamente.', 'success');
                }
                _this.removeAttr("disabled", "");
            },
            xhr: function () {
                var xhr = new window.XMLHttpRequest();
                xhr.upload.addEventListener("progress", function(evt){
                    if (evt.lengthComputable) {
                        var percentComplete = Math.round((evt.loaded / evt.total)*100)+"%";
                        //console.log( percentComplete );
                        _this.find("span").text(percentComplete + ' Guardando Cambios...');
                    }
                }, false);
                return xhr;
            },
            error: function(){
                alerta('Se han detectado errores de red intente en otro momento.', 'danger');
                _this.removeAttr("disabled", "");
            }
        });
    });
    function abrirVista(href, idmodal, accion){
        let params = '';
        switch(accion){
            case 'banner':
                params = 'id=&accion=hall-conferencias&idferias=<?php echo $this->feria['idferias']; ?>';
            break;
        }
        abrirModal(href+'?'+params, idmodal);
    }
</script>

</html>