<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="theme-color" content="#00b3ce" />
        <meta http-equiv="Content-Language" content="es" />
        <meta name="description" content="LA ÚNICA FERIA DEL SECTOR INMOBILIARIO EN EL PERÚ, y es organizada por la Centro Virtual de Convenciones." />
        <meta name="Keywords" content="Ferias virtuales, recorridos, convenciones" />
        <title>
            FERIA VIRTUAL INMOBILIRIA - LA ÚNICA FERIA VIRTUAL DEL SECTOR INMOBILIARIO EN EL PERÚ.
        </title>
        <base href="<?php echo $this->layout()->base_url; ?>" />
        <link href="https://centrovirtualdeconvenciones.com/expohogar.png" rel="shortcut icon" title="feria-2020" />
        <meta name="viewport" content="width=480" initial-scale="1" />
        <link rel="alternate" hreflang="es" href="https://dragmastands.com/" />
        <link href="plantillas/css/style.css" rel="stylesheet" type="text/css" />
        <!-- CSS [INICIO] -->
        <link rel="stylesheet" media="screen, print" href="plantillas/css/fontawesome.min.css" />
        <link href="plantillas/css/base.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" media="screen, print" href="css/formplugins/select2/select2.bundle.css" />
        <link rel="stylesheet" media="screen, print" href="css/notifications/toastr/toastr.css" />
        <!-- CSS [FIN] -->
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <script type="text/javascript" src="plantillas/js/jquery-1.10.2.min.js"></script>
        <!-- JS [INICIO] -->
        <script src="js/formplugins/select2/select2.bundle.js"></script>
        <script src="js/notifications/toastr/toastr.js"></script>
        <script src="plantillas/js/bootstrap-tooltip.js"></script>
        <!-- JS [FIN] -->
    </head>

    <body>
        <div class="se-pre-con"></div>

        <div class="header-index">
            <a href="javascript:void(0)" class="logos">
                <img src="ferias/logo/<?php echo $this->feria['hash_logo']; ?>" width="60%" />
            </a>
            <div class="logos-2">
                <img src="plantillas/imagenes/logocentrovirtual.png" width="15%" />
                <img src="clientes/logo/<?php echo $this->cliente['hash_logo']; ?>" width="20%" />
            </div>
            <!-- <div class="logos-3">
         
         <a href="registro.html" ><i class="fas fa-user"></i>&nbsp;INGRESAR AL EVENTO</a>
       </div>-->

            <a href="#" data-drawer-trigger aria-controls="drawer-name" aria-expanded="false" class="button-menu"><img src="plantillas/imagenes/menu-01.svg" width="68%" /></a>
        </div>

        <section class="home-recepcion">
            <section class="drawer" id="drawer-name" data-drawer-target>
                <div class="drawer__overlay" data-drawer-close tabindex="-1"></div>

                <div class="drawer__wrapper">
                    <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
                    <div class="drawer__content">
                        <ul class="menu-responsive">
                            <a href="hall-planos-1.html">INICIAR FERIA</a>
                            <a href="hall.html"><img src="plantillas/imagenes/iconos-menu-01.svg" />Recepción</a>
                            <a href="hall-planos-1.html"><img src="plantillas/imagenes/iconos-menu-02.svg" />Expoferia</a>
                            <a href="conferencias.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Conferencias</a>
                            <a href="rueda-negocios.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Rueda de Negocios</a>
                        </ul>
                        <div class="logo-responsive-ccl"></div>
                    </div>
                </div>
            </section>

            <?php if( isset($this->configuracion['imagen_fondo_movil']) ) : ?>
            <style>
                @media screen and (max-width: 580px) {
                    .home-recepcion .slide.active-2 {
                        background-image: url('<?php echo 'paginas/recepcion/'.$this->configuracion['imagen_fondo_movil']['hash']; ?>') !important;
                    }
                }
            </style>
            <?php endif; ?>

            <div class="imagen-fondo-movil" data-width="500" data-height="881" data-accept=".jpg,.jpeg,.png"></div>

            <div class="slide active-2 imagen-fondo" data-width="2000" data-height="1109" data-accept=".jpg,.jpeg,.png" style="background-image: url(<?php echo(isset($this->configuracion['imagen_fondo']))?'paginas/recepcion/'.$this->configuracion['imagen_fondo']['hash']:'img/plantillas/recepcion/imagen_fondo.jpg';?>);">

                <div class="caja-logos-evento imagen" data-id="imagen_izquierda" data-width="600" data-height="341" data-accept=".jpg,.jpeg,.png">
                    <a href="#">
                        <img
                            src="<?php echo ( isset($this->configuracion['imagen_izquierda'])) ? 'paginas/recepcion/'.$this->configuracion['imagen_izquierda']['hash'] : 'img/plantillas/recepcion/imagen_izquierda.jpg'; ?>"
                            class="img"
                            data-toggle="tooltip"
                            data-placement="bottom"
                            title="La dimensión recomendada es de 600 px de ancho y 341 px de alto"
                        />
                    </a>
                </div>

                <div class="content-gif-tv">
                    <div class="tv-gif">
                        <img src="plantillas/imagenes/tv-fondo-back.png" />

                        <div class="caja-gif imagen" data-id="imagen_gif" data-width="781" data-height="427" data-accept=".jpg,.jpeg,.png,.gif">
                            <a href="#">
                                <img
                                    src="<?php echo ( isset($this->configuracion['imagen_gif'])) ? 'paginas/recepcion/'.$this->configuracion['imagen_gif']['hash'] : 'img/plantillas/recepcion/imagen_gif.gif'; ?>"
                                    class="img"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="La dimensión recomendada es de 781 px de ancho y 427 px de alto"
                                />
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="navbar-down">
                <div class="boton" style="animation-delay: 1.5s;">
                    <img src="plantillas/imagenes/new-icons-03.svg" width="32%" />
                    <a href="hall.html">PLANO</a>
                </div>

                <div class="boton" style="animation-delay: 1.7s;">
                    <img src="plantillas/imagenes/new-icons-02.svg" width="32%" />
                    <a href="conferencias.html">CONFERENCIAS</a>
                </div>
            </div>
        </section>

        <script>
            $(document).ready(function () {
                // $('#tv').popup({
                //   transition: 'all 0.3s',
                //   closebutton: true
                // });
            });
        </script>
    </body>

    <script>
        /*!
         * Based on articles on
         * https://gomakethings.com
         */

        var drawer = function () {
            /**
             * Element.closest() polyfill
             * https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
             */
            if (!Element.prototype.closest) {
                if (!Element.prototype.matches) {
                    Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
                }
                Element.prototype.closest = function (s) {
                    var el = this;
                    var ancestor = this;
                    if (!document.documentElement.contains(el)) return null;
                    do {
                        if (ancestor.matches(s)) return ancestor;
                        ancestor = ancestor.parentElement;
                    } while (ancestor !== null);
                    return null;
                };
            }

            //
            // Settings
            //
            var settings = {
                speedOpen: 50,
                speedClose: 350,
                activeClass: "is-active",
                visibleClass: "is-visible",
                selectorTarget: "[data-drawer-target]",
                selectorTrigger: "[data-drawer-trigger]",
                selectorClose: "[data-drawer-close]",
            };

            //
            // Methods
            //

            // Toggle accessibility
            var toggleAccessibility = function (event) {
                if (event.getAttribute("aria-expanded") === "true") {
                    event.setAttribute("aria-expanded", false);
                } else {
                    event.setAttribute("aria-expanded", true);
                }
            };

            // Open Drawer
            var openDrawer = function (trigger) {
                // Find target
                var target = document.getElementById(trigger.getAttribute("aria-controls"));

                // Make it active
                target.classList.add(settings.activeClass);

                // Make body overflow hidden so it's not scrollable
                document.documentElement.style.overflow = "hidden";

                // Toggle accessibility
                toggleAccessibility(trigger);

                // Make it visible
                setTimeout(function () {
                    target.classList.add(settings.visibleClass);
                }, settings.speedOpen);
            };

            // Close Drawer
            var closeDrawer = function (event) {
                // Find target
                var closestParent = event.closest(settings.selectorTarget),
                    childrenTrigger = document.querySelector('[aria-controls="' + closestParent.id + '"');

                // Make it not visible
                closestParent.classList.remove(settings.visibleClass);

                // Remove body overflow hidden
                document.documentElement.style.overflow = "";

                // Toggle accessibility
                toggleAccessibility(childrenTrigger);

                // Make it not active
                setTimeout(function () {
                    closestParent.classList.remove(settings.activeClass);
                }, settings.speedClose);
            };

            // Click Handler
            var clickHandler = function (event) {
                // Find elements
                var toggle = event.target,
                    open = toggle.closest(settings.selectorTrigger),
                    close = toggle.closest(settings.selectorClose);

                // Open drawer when the open button is clicked
                if (open) {
                    openDrawer(open);
                }

                // Close drawer when the close button (or overlay area) is clicked
                if (close) {
                    closeDrawer(close);
                }

                // Prevent default link behavior
                if (open || close) {
                    event.preventDefault();
                }
            };

            // Keydown Handler, handle Escape button
            var keydownHandler = function (event) {
                if (event.key === "Escape" || event.keyCode === 27) {
                    // Find all possible drawers
                    var drawers = document.querySelectorAll(settings.selectorTarget),
                        i;

                    // Find active drawers and close them when escape is clicked
                    for (i = 0; i < drawers.length; ++i) {
                        if (drawers[i].classList.contains(settings.activeClass)) {
                            closeDrawer(drawers[i]);
                        }
                    }
                }
            };

            //
            // Inits & Event Listeners
            //
            document.addEventListener("click", clickHandler, false);
            document.addEventListener("keydown", keydownHandler, false);
        };

        drawer();
    </script>

    <script>
        // Wait for window load
        $(window).load(function () {
            // Animate loader off screen
            $(".se-pre-con").fadeOut("slow");
        });
    </script>

    <?php echo $this->partial('partial/paginas/opciones', ['planes_paginas'=> $this->planes_paginas, 'idferias'=> $this->feria['idferias'], 'idpaginas'=> $this->pagina['idpaginas'], 'pagina'=> $this->pagina, 'configuracion'=> $this->configuracion]); ?>

    <form id="form_pagina">
        <input type="hidden" name="plantilla" value="recepcion" />
        <input type="hidden" name="idpaginas" value="<?php echo $this->pagina['idpaginas']; ?>" />
        <input type="hidden" name="idferias" value="<?php echo $this->feria['idferias']; ?>" />
        <input type="hidden" name="idpaginasferias" value="<?php echo $this->idpaginasferias; ?>" />
        <input type="file" id="imagen_izquierda" name="imagen_izquierda" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_gif" name="imagen_gif" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png,.gif" />
        <input type="file" id="imagen_fondo" name="imagen_fondo" style="display: none;" onchange="subirFondo(this.files, this, 'imagen-fondo')" accept=".jpg,.jpeg,.png" />
        <input type="hidden" name="recepcion_opciones" value="[]" />
        <input type="file" id="imagen_fondo_movil" name="imagen_fondo_movil" onchange="subirFondo(this.files, this, 'imagen-fondo-movil')" style="display: none;" accept=".jpg,.jpeg,.png" />
        <input type="file" id="fondo_video" name="fondo_video" style="display: none;" onchange="subirFondoVideo(this.files, this, 'btn-fondo-video')" accept=".mp4" />
        <input type="hidden" id="activar_fondo_video" name="activar_fondo_video" value="false">
    </form>

    <script>

        $("a").click(function (e) {
            e.preventDefault();
        });

        $(".img.img, .btn-cambiar-fondo, .btn-cambiar-fondo-movil").tooltip();

        $(".imagen").click(function () {
            let idinputfile = $(this).attr("data-id");
            $("#" + idinputfile).click();
        });

        $(".btn-cambiar-fondo").click(function () {
            $("#imagen_fondo").click();
        });

        $(".btn-cambiar-fondo-movil").click(function () {
            $("#imagen_fondo_movil").click();
        });

        $(".btn-fondo-video").click(function () {
            $("#fondo_video").click();
        });

        var _URL = window.URL || window.webkitURL;

        function subirArchivo(files, obj) {
          let reader = new FileReader();
          let idinputfile = $(obj).attr("id");
          let contenedor = $("[data-id='" + idinputfile + "']");
          let imgContenedor = contenedor.find(".img");
          let file = files[0];
          let img_width = parseInt(contenedor.attr("data-width"));
          let img_height = parseInt(contenedor.attr("data-height"));
          let accept = contenedor.attr("data-accept");
          reader.readAsDataURL(file);
          reader.onload = function (e) {
              var image = new Image();
              image.src = e.target.result;
              image.onload = function () {
                  var width = this.width;
                  var height = this.height;
                  if (width != img_width || height != img_height) {
                      alerta("La imagen no cumple con las dimensiones recomendadas.", "danger");
                      $(obj).val("");
                      imgContenedor.attr("src", "img/no-imagen.jpg");
                      return false;
                  }
                  contenedor.find("img.img").attr("src", e.target.result);
              };
          };
        }

        function subirFondo(files, obj, clase) {
          let contenedor = $("."+clase);
          let reader = new FileReader();
          let file = files[0];
          let img_width = parseInt(contenedor.attr("data-width"));
          let img_height = parseInt(contenedor.attr("data-height"));
          let accept = contenedor.attr("data-accept");
          reader.readAsDataURL(file);
          reader.onload = function (e) {
              var image = new Image();
              image.src = e.target.result;
              image.onload = function () {
                  var width = this.width;
                  var height = this.height;
                  if (width != img_width || height != img_height) {
                      alerta("La imagen no cumple las dimensiones recomendadas. Por favor, intentelo otra vez.", "warning");
                      $(obj).val("");
                      contenedor.css({ "background-image": "url(img/no-imagen.jpg)" });
                      return false;
                  }
                  console.log(e.target.result);
                  contenedor.css({ "background-image": "url(" + e.target.result + ")" });
              };
          };
        }

        function subirFondoVideo(files, obj, classFondoVideo) {
            document.querySelector(`.${classFondoVideo}`).innerHTML = `<i class="fas fa-images"></i> Cambiar Video`;
        }

        $(".btn-guardar-cambios").click(function () {
            let _this = $(this);
            let form = $("form#form_pagina");
            var data = new FormData(form[0]);
            _this.attr("disabled", "");
            _this.find("i").hide();
            $.ajax({
                url: "cliente/guardar-parametros-pagina",
                type: "POST",
                data: data,
                contentType: false,
                processData: false,
                success: function (response) {
                    //console.log( response );
                    if (response.result == "success") {
                        form.find("input[name='idpaginasferias']").val(response.idpaginasferias);
                        _this.find("i").show();
                        _this.find("span").text("Guardar Cambios");
                        alerta("Los datos se guardaron correctamente.", "success");
                    }
                    _this.removeAttr("disabled", "");
                },
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener(
                        "progress",
                        function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round((evt.loaded / evt.total) * 100) + "%";
                                //console.log( percentComplete );
                                _this.find("span").text(percentComplete + " Guardando Cambios...");
                            }
                        },
                        false
                    );
                    return xhr;
                },
                error: function () {
                    alerta("Se han detectado errores de red intente en otro momento.", "danger");
                    _this.removeAttr("disabled", "");
                },
            });
        });
    </script>
</html>