<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="theme-color" content="#00b3ce" />
        <meta http-equiv="Content-Language" content="es" />
        <meta name="description" content="LA ÚNICA FERIA DEL SECTOR INMOBILIARIO EN EL PERÚ, y es organizada por la Centro Virtual de Convenciones." />
        <meta name="Keywords" content="Ferias virtuales, recorridos, convenciones" />
        <title>FERIA VIRTUAL INMOBILIRIA - LA ÚNICA FERIA VIRTUAL DEL SECTOR INMOBILIARIO EN EL PERÚ.</title>
        <base href="<?php echo $this->layout()->base_url; ?>" />
        <link href="https://centrovirtualdeconvenciones.com/expohogar.png" rel="shortcut icon" title="feria-2020" />
        <meta name="viewport" content="width=480" initial-scale="1" />
        <link rel="alternate" hreflang="es" href="https://dragmastands.com/" />
        <link href="plantillas/css/style.css" rel="stylesheet" type="text/css" />
        <!-- CSS [INICIO] -->
        <link rel="stylesheet" media="screen, print" href="plantillas/css/fontawesome.min.css" />
        <link href="plantillas/css/base.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" media="screen, print" href="css/formplugins/select2/select2.bundle.css" />
        <link rel="stylesheet" media="screen, print" href="css/notifications/toastr/toastr.css" />
        <!-- CSS [FIN] -->
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <script type="text/javascript" src="plantillas/js/jquery-1.10.2.min.js"></script>
        <!-- JS [INICIO] -->
        <script src="js/formplugins/select2/select2.bundle.js"></script>
        <script src="js/notifications/toastr/toastr.js"></script>
        <script src="plantillas/js/bootstrap-tooltip.js"></script>
        <!-- JS [FIN] -->
    </head>

    <body style="overflow-y: scroll;">
        <!--HEADER--->
        <div class="header-index">
            <a href="javascript:void(0)" class="logos">
                <img src="ferias/logo/<?php echo $this->feria['hash_logo']; ?>" width="60%" />
            </a>
            <div class="logos-2">
                <img src="plantillas/imagenes/logocentrovirtual.png" width="15%" />
                <img src="clientes/logo/<?php echo $this->cliente['hash_logo']; ?>" width="20%" />
            </div>
            <a href="#" data-drawer-trigger aria-controls="drawer-name" aria-expanded="false" class="button-menu"><img src="plantillas/imagenes/menu-01.svg" width="68%" /></a>
        </div>

        <div class="franja-azul no-click">
        <div class="franja-azul-menu-der">
            <a href="recepción.html">&nbsp;RECEPCIÓN</a>
            <a href="conferencias.html">&nbsp;CONFERENCIAS</a>
            <a href="conferencias.html">&nbsp;RUEDA DE NEGOCIOS</a>
            <a href="conferencias.html" class="resaltar-pestaña">&nbsp;EXPOSITORES EN VIVO</a>
            <a href="conferencias.html">&nbsp; OFERTA Y DEMANDA</a>
            <a href="conferencias.html">&nbsp; RV 360°</a>
            <a class="space"></a>
            </div>
            <a href="auditorio-premium.html" class="resaltar"><i class="fas fa-search"></i>&nbsp;BUSCADOR POR DISTRITO</a>
        </div>

        <!-----FIN HEADER--->

        <div class="franja-menu-bots no-click">
            <a href="recepcion.html"><i class="fas fa-arrow-circle-left"></i>&nbsp;ANTERIOR</a>
            <a class="space"></a>
            <a>PABELLÓN A</a>
            <a class="space"></a>
            <a href="conferencias.html">&nbsp;SIGUIENTE&nbsp;<i class="fas fa-arrow-circle-right"></i></a>
        </div>

        <div class="wsp-all">
           <!-- <a href="#"><img src="plantillas/imagenes/whatsapp.svg" /></a>-->
        </div>

        <section class="drawer" id="drawer-name" data-drawer-target>
            <div class="drawer__overlay" data-drawer-close tabindex="-1"></div>
            <div class="drawer__wrapper">
                <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
                <div class="drawer__content">
                    <ul class="menu-responsive">
                        <a href="hall-planos-1.html">INICIAR FERIA</a>
                        <a href="hall.html"><img src="plantillas/imagenes/iconos-menu-01.svg" />Recepción</a>
                        <a href="hall-planos-1.html"><img src="plantillas/imagenes/iconos-menu-02.svg" />Expoferia</a>
                        <a href="conferencias.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Conferencias</a>
                        <a href="rueda-negocios.html"><img src="plantillas/imagenes/iconos-menu-03.svg" />Rueda de Negocios</a>
                    </ul>
                    <div class="logo-responsive-ccl"></div>
                </div>
            </div>
        </section>

        <div class="logo-live-stand" style="display:none;">
            <div class="logo-live-center-stand">
                <img src="plantillas/imagenes/logo-principal.svg" /><a href="#"> EN DIRECTO<img src="plantillas/imagenes/tin.svg" /></a>
            </div>
        </div>

        <div class="home-fondo-stands imagen-fondo"
            data-width="2000"
            data-height="1109"
            data-accept=".jpg,.jpeg,.png"
            style="background-image: url(<?php echo(isset($this->configuracion['imagen_fondo']))?'paginas/stand-circular/'.$this->configuracion['imagen_fondo']['hash']:'img/plantillas/stand-circular/imagen_fondo.jpg';?>);"
        >

            <div id="banco-modulo-2">
                <a id="closeButton">X</a>
                <div class="center">
                    <div class="todo-banco">
                        <div class="logo">
                            <img src="plantillas/imagenes/bbva-phone.svg" />
                        </div>
                        <div class="contenido-hide">
                            <h2>ASESOR VIRTUAL</h2>
                            <div class="foto">
                                <img src="plantillas/imagenes/girl-phone.jpg" />
                            </div>
                            <div class="names">
                                <p>Nombre del Ejecutivo</p>
                                <p>Correo</p>
                            </div>

                            <div class="two-botons">
                                <a href="#" class="chicos"> <img src="plantillas/imagenes/sms.svg" /></a>
                                <a href="#" class="chicos"> <img src="plantillas/imagenes/call.svg" /></a>
                                <a href="#" class="chicos"> <img src="plantillas/imagenes/wsp.svg" /></a>
                            </div>
                        </div>

                        <div class="navbar-bbva" style="display: none;">
                            <div class="boton" style="animation-delay: 1.7s;">
                                <a href="#" class="credito_open"><img src="plantillas/imagenes/whatsapp.svg" /></a>
                            </div>
                        </div>

                        <div class="calcula">
                            <a href="#" class="credito_open">
                                CALCULA TU<br />
                                CREDITO AQUÍ
                            </a>
                        </div>
                    </div>
                    <img class="modulito" src="plantillas/imagenes/counter-banco.png" />
                </div>
            </div>

            <div class="info-modulo" style="display:none;">
                <div class="center" data-title="ESTAMOS AQUÍ PARA AYUDARTE">
                    <div class="contenido-hide">
                        <h2>ASESOR VIRTUAL EN LÍNEA</h2>
                        <div class="foto">
                            <div class="all-agente">
                                <div class="picture">
                                    <img src="plantillas/imagenes/girl-phone.jpg" />
                                </div>
                                <span>NOMBRE DEL ASESOR</span>
                            </div>
                            <div class="space"></div>
                            <div class="two-botons">
                                <div class="tit">
                                    <span>ASESOR VIRTUAL EN LÍNEA</span>
                                </div>
                                <div class="box-responsive">
                                    <a href="#" class="chicos"> <img src="plantillas/imagenes/sms.svg" /></a>
                                    <a href="#" class="chicos"> <img src="plantillas/imagenes/call.svg" /></a>
                                    <a href="#" class="chicos"> <img src="plantillas/imagenes/wsp.svg" /></a>
                                </div>
                                <div class="horario">
                                    <p>HORARIO DE ATENCIÓN</p>
                                    <div class="hours"><small>9:00am a 1:00pm</small> <small>3:00am a 7:00pm</small></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="stand-middle-circulo">
                <img src="plantillas/imagenes/stand-circulo.png" />

                <div class="logo-stand-circulo">
                    <div class="logo-stand-circulo-center">
                        <div class="logo-frizo-circulo-1 imagen" data-id="imagen_logo_1" data-width="272" data-height="55" data-accept=".jpg,.jpeg,.png">
                            <img
                                src="<?php echo ( isset($this->configuracion['imagen_logo_1'])) ? 'paginas/stand-circular/'.$this->configuracion['imagen_logo_1']['hash'] : 'img/plantillas/stand-circular/imagen_logo_1.svg'; ?>"
                                class="img"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="La dimensión recomendada es de 272 px de ancho y 55 px de alto"
                            />
                        </div>

                        <div class="space"></div>
                        <div class="logo-frizo-circulo-2 imagen" data-id="imagen_logo_2" data-width="305" data-height="60" data-accept=".jpg,.jpeg,.png">
                            <img
                                src="<?php echo ( isset($this->configuracion['imagen_logo_2'])) ? 'paginas/stand-circular/'.$this->configuracion['imagen_logo_2']['hash'] : 'img/plantillas/stand-circular/imagen_logo_2.svg'; ?>"
                                class="img"
                                data-toggle="tooltip"
                                data-placement="bottom"
                                title="La dimensión recomendada es de 305 px de ancho y 60 px de alto"
                            />
                        </div>
                    </div>
                </div>

                <div class="logo-stand-vr">
                    <div class="logo-stand-center-vr">
                        <a href="#" class="vr_open"><img src="plantillas/imagenes/vr.svg" /></a>
                    </div>
                </div>

                <div class="logo-stand-circulo-plin">
                    <div class="logo-stand-circulo-center-plin">
                        <a href="#"> EN DIRECTO<img src="plantillas/imagenes/tin.svg" /></a>
                    </div>
                </div>

                <div class="logo-stand-circulo-distrito">
                    <div class="logo-stand-circulo-distrito-center">
                        <span><input type="text" data-text="tv_texto_1" value="<?php echo (isset($this->configuracion['tv_texto_1'])) ? $this->configuracion['tv_texto_1'] : ''; ?>" placeholder="PERSONALIZAR TEXTO"></span>
                    </div>
                </div>

                <div class="paneles-stand-circulo">
                    <div class="paneles-stand-circulo-middle">
                        <div class="left-circulo imagen" data-id="imagen_banner_1" data-width="972" data-height="1200" data-accept=".jpg,.jpeg,.png">
                            <span><img src="plantillas/imagenes/tin-green.svg" /></span>
                            <a href="#" class="zooms_circulo_open">
                                <img
                                    src="<?php echo ( isset($this->configuracion['imagen_banner_1'])) ? 'paginas/stand-circular/'.$this->configuracion['imagen_banner_1']['hash'] : 'img/plantillas/stand-circular/imagen_banner_1.jpg'; ?>"
                                    class="img"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="La dimensión recomendada es de 972 px de ancho y 1200 px de alto"
                                />
                            </a>
                        </div>

                        <div class="space-2"></div>
                        <div class="center-circulo imagen" data-id="imagen_tv_1" data-width="700" data-height="359" data-accept=".jpg,.jpeg,.png">
                            <span><img src="plantillas/imagenes/tin-green.svg" /></span>
                            <a href="#" class="fade_open">
                                <img
                                    src="<?php echo ( isset($this->configuracion['imagen_tv_1'])) ? 'paginas/stand-circular/'.$this->configuracion['imagen_tv_1']['hash'] : 'img/plantillas/stand-circular/imagen_tv_1.jpg'; ?>"
                                    class="img"
                                    data-toggle="tooltip"
                                    data-placement="bottom"
                                    title="La dimensión recomendada es de 700 px de ancho y 359 px de alto"
                                />
                            </a>
                        </div>
                    </div>
                </div>

                <div class="box-counter-circulo">
                    <div class="box-counter-center-circulo">
                        <img src="plantillas/imagenes/counter-circular.png">
                        <div class="logo-company imagen" data-id="imagen_logo_3" data-width="332" data-height="120" data-accept=".jpg,.jpeg,.png">
                        <img src="<?php echo ( isset($this->configuracion['imagen_logo_3'])) ? 'paginas/stand-circular/'.$this->configuracion['imagen_logo_3']['hash'] : 'img/plantillas/stand-circular/imagen_logo_3.svg'; ?>"
                        class="img"
                        data-toggle="tooltip"
                        data-placement="bottom"
                        title="La dimensión recomendada es de 332 px de ancho y 120 px de alto"/>
                        </div>
                    </div>
                </div>

			</div>

		</div>

               
            </div>

            <div id="vr" class="well">
                <div class="modal-contents-2">
                </div>
            </div>

            <div id="fade" class="well">
                <div class="modal-contents-2">
                </div>
            </div>

            <div id="chat" class="well-chat">
                <div class="caja-chat">
                    <h2>CONVERSA CON NOSOTROS</h2>
                    <div id="web_chat"></div>
                    <div>
                        <input type="text" id="name" placeholder="Nombre" class="campos-chat" /><br />
                        <textarea placeholder="Escribe tu consulta..." id="text" class="campos-comentarios"></textarea>
                        <input type="button" onclick="send();" value="ENVIAR" class="send-chat" /><br />
                    </div>
                </div>
            </div>

            
        </div>

        <div class="franja-azul-2" style="display: none;">
            <a href="stand-feria.html" class="cool-link"><i class="fas fa-building"></i>&nbsp;STAND</a>
            <a href="programas.html" class="cool-link" id="active"><i class="fas fa-check-circle"></i>&nbsp;PROYECTOS</a>
            <a href="cupones.html" class="cool-link"><i class="fas fa-ticket-alt"></i>&nbsp;PROMOCIONES</a>
        </div>

        <div class="franja-amarillo" style="display: none;">
            <a href="recepcion.html" class="resaltar">&nbsp;PRODUCTOS</a>
            <a href="recepción.html">&nbsp;PROMOCIONES</a>
            <a href="conferencias.html">&nbsp;SEND BUSSINESS CARD</a>
            <a href="conferencias.html">&nbsp;INFORMACIÓN</a>
            <a href="conferencias.html" class="resaltar-pestaña">&nbsp;VR 360°</a>
            <a href="conferencias.html">&nbsp; JUEGOS</a>
            <a class="space"></a>

            <div class="menu-amarillo no-click">
                <a href="recepcion.html"><i class="fas fa-arrow-circle-left"></i>&nbsp;ANTERIOR</a>
                <a class="space"></a>
                <a>STAND</a>
                <a class="space"></a>
                <a href="conferencias.html">&nbsp;SIGUIENTE&nbsp;<i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="grid-back" style="display: none;">
            <div id="grid-empresas-resume">
                <a href="stand-feria.html" data-tooltip="ABRIL"><img src="plantillas/imagenes/logos-menu/stand-1.png" /></a>
                <a href="stand-feria.html" data-tooltip="AVENIR"><img src="plantillas/imagenes/logos-menu/stand-2.png" /></a>
                <a href="stand-feria.html" data-tooltip="MI VIVIENDA"><img src="plantillas/imagenes/logos-menu/stand-3.png" /></a>
                <a href="stand-feria.html" data-tooltip="HPC"><img src="plantillas/imagenes/logos-menu/stand-4.png" /></a>
                <a href="stand-feria.html" data-tooltip="LA VENTUROSA"><img src="plantillas/imagenes/logos-menu/stand-5.png" /></a>
                <a href="stand-feria.html" data-tooltip="MARCAN"><img src="plantillas/imagenes/logos-menu/stand-6.png" /></a>
            </div>
        </div>

        <div class="navbar" style="display: none;">
            <div class="boton1"></div>

            <div class="boton2">
                <img src="plantillas/imagenes/iconos-menu-02-01.svg" width="30%" />
                <a href="https://centrovirtualdeconvenciones.com/feria-ccl-mapa/index.htm">MAPA</a>
            </div>

            <div class="boton3">
                <img src="plantillas/imagenes/iconos-menu-03.svg" width="30%" />
                <a href="https://centrovirtualdeconvenciones.com/feria-ccl-auditorio/index.htm">CONFERENCIA</a>
            </div>
        </div>

    </body>

    <script>
        /*!
         * Based on articles on
         * https://gomakethings.com
         */

        var drawer = function () {
            /**
             * Element.closest() polyfill
             * https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill
             */
            if (!Element.prototype.closest) {
                if (!Element.prototype.matches) {
                    Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
                }
                Element.prototype.closest = function (s) {
                    var el = this;
                    var ancestor = this;
                    if (!document.documentElement.contains(el)) return null;
                    do {
                        if (ancestor.matches(s)) return ancestor;
                        ancestor = ancestor.parentElement;
                    } while (ancestor !== null);
                    return null;
                };
            }

            //
            // Settings
            //
            var settings = {
                speedOpen: 50,
                speedClose: 350,
                activeClass: "is-active",
                visibleClass: "is-visible",
                selectorTarget: "[data-drawer-target]",
                selectorTrigger: "[data-drawer-trigger]",
                selectorClose: "[data-drawer-close]",
            };

            //
            // Methods
            //

            // Toggle accessibility
            var toggleAccessibility = function (event) {
                if (event.getAttribute("aria-expanded") === "true") {
                    event.setAttribute("aria-expanded", false);
                } else {
                    event.setAttribute("aria-expanded", true);
                }
            };

            // Open Drawer
            var openDrawer = function (trigger) {
                // Find target
                var target = document.getElementById(trigger.getAttribute("aria-controls"));

                // Make it active
                target.classList.add(settings.activeClass);

                // Make body overflow hidden so it's not scrollable
                document.documentElement.style.overflow = "hidden";

                // Toggle accessibility
                toggleAccessibility(trigger);

                // Make it visible
                setTimeout(function () {
                    target.classList.add(settings.visibleClass);
                }, settings.speedOpen);
            };

            // Close Drawer
            var closeDrawer = function (event) {
                // Find target
                var closestParent = event.closest(settings.selectorTarget),
                    childrenTrigger = document.querySelector('[aria-controls="' + closestParent.id + '"');

                // Make it not visible
                closestParent.classList.remove(settings.visibleClass);

                // Remove body overflow hidden
                document.documentElement.style.overflow = "";

                // Toggle accessibility
                toggleAccessibility(childrenTrigger);

                // Make it not active
                setTimeout(function () {
                    closestParent.classList.remove(settings.activeClass);
                }, settings.speedClose);
            };

            // Click Handler
            var clickHandler = function (event) {
                // Find elements
                var toggle = event.target,
                    open = toggle.closest(settings.selectorTrigger),
                    close = toggle.closest(settings.selectorClose);

                // Open drawer when the open button is clicked
                if (open) {
                    openDrawer(open);
                }

                // Close drawer when the close button (or overlay area) is clicked
                if (close) {
                    closeDrawer(close);
                }

                // Prevent default link behavior
                if (open || close) {
                    event.preventDefault();
                }
            };

            // Keydown Handler, handle Escape button
            var keydownHandler = function (event) {
                if (event.key === "Escape" || event.keyCode === 27) {
                    // Find all possible drawers
                    var drawers = document.querySelectorAll(settings.selectorTarget),
                        i;

                    // Find active drawers and close them when escape is clicked
                    for (i = 0; i < drawers.length; ++i) {
                        if (drawers[i].classList.contains(settings.activeClass)) {
                            closeDrawer(drawers[i]);
                        }
                    }
                }
            };

            //
            // Inits & Event Listeners
            //
            document.addEventListener("click", clickHandler, false);
            document.addEventListener("keydown", keydownHandler, false);
        };

        drawer();
    </script>

    <!-- begin olark code 
<script type="text/javascript" async>
	;(function(o,l,a,r,k,y){if(o.olark)return; r="script";y=l.createElement(r);r=l.getElementsByTagName(r)[0]; y.async=1;y.src="//"+a;r.parentNode.insertBefore(y,r); y=o.olark=function(){k.s.push(arguments);k.t.push(+new Date)}; y.extend=function(i,j){y("extend",i,j)}; y.identify=function(i){y("identify",k.i=i)}; y.configure=function(i,j){y("configure",i,j);k.c[i]=j}; k=y._={s:[],t:[+new Date],c:{},l:a}; })(window,document,"static.olark.com/jsclient/loader.js");
	/* custom configuration goes here (www.olark.com/documentation) */
	olark.identify('1806-796-10-6944');
</script>
 end olark code -->
    <script>
        // Wait for window load
        $(window).load(function () {
            // Animate loader off screen
            $(".se-pre-con").fadeOut("slow");
        });
    </script>
    <?php echo $this->partial('partial/paginas/opciones-stand', ['empresa'=> $this->empresa,'feria'=>$this->feria,'cliente'=>$this->cliente,'idpaginasstand'=>$this->idpaginasstand,'configuracion'=>$this->configuracion,'listaEmpresas'=> $this->listaEmpresas]); ?>

    <form id="form_pagina">
        <input type="hidden" name="plantilla" value="stand-circular" />
        <input type="hidden" name="idempresas" value="<?php echo $this->empresa['idempresas']; ?>" />
        <input type="hidden" name="idpaginasstand" value="<?php echo $this->idpaginasstand; ?>" />
        <input type="file" id="imagen_logo_1" name="imagen_logo_1" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_logo_2" name="imagen_logo_2" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_logo_3" name="imagen_logo_3" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_banner_1" name="imagen_banner_1" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_banner_2" name="imagen_banner_2" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_tv_1" name="imagen_tv_1" style="display: none;" onchange="subirArchivo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="file" id="imagen_fondo" name="imagen_fondo" style="display: none;" onchange="subirFondo(this.files, this)" accept=".jpg,.jpeg,.png" />
        <input type="hidden" id="tv_texto_1" name="tv_texto_1" value="<?php echo (isset($this->configuracion['tv_texto_1'])) ? $this->configuracion['tv_texto_1'] : ''; ?>" style="display: none;" />
        <input type="file" id="fondo_video" name="fondo_video" style="display: none;" onchange="subirFondoVideo(this.files, this, 'btn-fondo-video')" accept=".mp4" />
        <input type="hidden" id="activar_fondo_video" name="activar_fondo_video" value="false">
    </form>
    <script>
        $("[data-text='tv_texto_1']").keyup(function(){
            $("#tv_texto_1").val($(this).val());
        });
        $("a").click(function (e) {
            e.preventDefault();
        });

        $(".img.img, .btn-cambiar-fondo").tooltip();

        $(".imagen").click(function () {
            let idinputfile = $(this).attr("data-id");
            $("#" + idinputfile).click();
        });

        $(".btn-cambiar-fondo").click(function () {
            $("#imagen_fondo").click();
        });

        $(".btn-fondo-video").click(function () {
            $("#fondo_video").click();
        });

        var _URL = window.URL || window.webkitURL;

        function subirArchivo(files, obj) {
          let reader = new FileReader();
          let idinputfile = $(obj).attr("id");
          let contenedor = $("[data-id='" + idinputfile + "']");
          let imgContenedor = contenedor.find(".img");
          let file = files[0];
          let img_width = parseInt(contenedor.attr("data-width"));
          let img_height = parseInt(contenedor.attr("data-height"));
          let accept = contenedor.attr("data-accept");
          reader.readAsDataURL(file);
          reader.onload = function (e) {
              var image = new Image();
              image.src = e.target.result;
              image.onload = function () {
                  var width = this.width;
                  var height = this.height;
                  if (width != img_width || height != img_height) {
                      alerta("La imagen no cumple con las dimensiones recomendadas.", "danger");
                      $(obj).val("");
                      imgContenedor.attr("src", "img/no-imagen.jpg");
                      return false;
                  }
                  contenedor.find("img.img").attr("src", e.target.result);
              };
          };
        }

        function subirFondo(files, obj) {
          let contenedor = $(".imagen-fondo");
          let reader = new FileReader();
          let file = files[0];
          let img_width = parseInt(contenedor.attr("data-width"));
          let img_height = parseInt(contenedor.attr("data-height"));
          let accept = contenedor.attr("data-accept");
          reader.readAsDataURL(file);
          reader.onload = function (e) {
              var image = new Image();
              image.src = e.target.result;
              image.onload = function () {
                  var width = this.width;
                  var height = this.height;
                  if (width != img_width || height != img_height) {
                      alerta("La imagen no cumple las dimensiones recomendadas. Por favor, intentelo otra vez.", "warning");
                      $(obj).val("");
                      contenedor.css({ "background-image": "url(img/no-imagen.jpg)" });
                      return false;
                  }
                  console.log(e.target.result);
                  contenedor.css({ "background-image": "url(" + e.target.result + ")" });
              };
          };
        }

        function subirFondoVideo(files, obj, classFondoVideo) {
            document.querySelector(`.${classFondoVideo}`).innerHTML = `<i class="fas fa-images"></i> Cambiar Video`;
        }

        $(".btn-guardar-cambios").click(function () {
            let _this = $(this);
            let form = $("form#form_pagina");
            var data = new FormData(form[0]);
            _this.attr("disabled", "");
            _this.find("i").hide();
            $.ajax({
                url: "cliente/guardar-parametros-stand",
                type: "POST",
                data: data,
                contentType: false,
                processData: false,
                success: function (response) {
                    //console.log( response );
                    if (response.result == "success") {
                        form.find("input[name='idpaginasstand']").val(response.idpaginasstand);
                        _this.find("i").show();
                        _this.find("span").text("Guardar Cambios");
                        alerta("Los datos se guardaron correctamente.", "success");
                    }
                    _this.removeAttr("disabled", "");
                },
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener(
                        "progress",
                        function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round((evt.loaded / evt.total) * 100) + "%";
                                //console.log( percentComplete );
                                _this.find("span").text(percentComplete + " Guardando Cambios...");
                            }
                        },
                        false
                    );
                    return xhr;
                },
                error: function () {
                    alerta("Se han detectado errores de red intente en otro momento.", "danger");
                    _this.removeAttr("disabled", "");
                },
            });
        });
        
    </script>
</html>