<?php
    $data = ['empresa'=> $this->empresa, 'zona'=> $this->zona];
    echo $this->partial('partial/empresa/header-logo-movil', $data);
?>

<div class="home-fondo-stands <?php echo ($this->fondo_video['estado']) ? 'bg-none' : ''; ?>" style="background-image: url(<?php echo(isset($this->configuracion['imagen_fondo']))? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_fondo']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_fondo.jpg';?>);">

    <?php if( $this->banco ) : ?>
    <div id="banco-modulo-2">
        <a id="closeButton">X</a>
        <div class="center">
            <div class="todo-banco">
                <div class="logo">
                    <img src="<?php echo ( $this->banco['hash_logo'] != '' ) ? $this->layout()->url_backend."/bancos/logo/".$this->banco['hash_logo'] : $this->layout()->url_backend."/img/no-imagen.jpg"; ?>" alt="">
                </div>
                <div class="contenido-hide">
                    <h2><?php echo $this->layout()->language->translate('ASESOR VIRTUAL')['text']; ?></h2>
                    <div class="foto">
                        <img src="imagenes/girl-phone.jpg" alt="">
                    </div>
                    <div class="names">
                        <p><?php echo $this->layout()->language->translate('Nombre del Ejecutivo')['text']; ?></p>
                        <p><?php echo $this->layout()->language->translate('Correo')['text']; ?></p>
                    </div>
                    <div class="two-botons">
                        <a href="javascript:void(0)" onclick="Panel.enviarCorreo('banco', <?php echo $this->banco['idbancos']; ?>, this, <?php echo $this->empresa['idempresas']; ?>)"> <img src="imagenes/sms.svg" alt=""></a>
                        <a href="tel:<?php echo $this->banco['telefono']; ?>"> <img src="imagenes/call.svg" alt=""></a>
                        <a href="javascript:abrirVentanaWindow('<?php echo $this->banco['enlace_wsp']; ?>')"> <img src="imagenes/wsp.svg" alt=""></a>
                    </div>
                </div>
                <div class="navbar-bbva" style="display: none;">
                    <div class="boton" style="animation-delay: 1.7s;">
                        <a href="#" class="credito_open"><img src="imagenes/whatsapp.svg" alt="" onclick="Panel.validarSesion(event)"></a>
                    </div>
                </div>
                <div class="calcula">
                    <a href="javascript:abrirVentanaWindow('<?php echo ( $this->banco['enlace'] != '' ) ? $this->banco['enlace'] : ''; ?>')" class="credito_open"><?php echo $this->layout()->language->translate('CALCULA TU')['text']; ?><br /><?php echo $this->layout()->language->translate('CREDITO AQUÍ')['text']; ?></a>
                </div>
            </div>
            <img class="modulito" src="<?php echo ( $this->banco['hash_logo_modulo'] != '' ) ? $this->layout()->url_backend."/bancos/logo/".$this->banco['hash_logo_modulo'] : $this->layout()->url_backend."/bancos/no-imagen.jpg"; ?>" alt="">
        </div>
    </div>
    <?php endif; ?>

    <?php
        $data = ['expositor'=> $this->expositor, 'empresa'=> $this->empresa];
        echo $this->partial('partial/empresa/info-modulo', $data);
    ?>

    <div class="stand-middle-circulo">

        <?php if( $this->empresa['stand_config_estado_rv'] === "1" ) : ?>
        <img src="imagenes/stand-circulo.png" alt=""/>
        <?php else: ?>
        <img src="imagenes/stand-circulo-rv.png" alt=""/>
        <?php endif; ?>

        <div class="logo-stand-circulo">
            <div class="logo-stand-circulo-center">
                <div class="logo-frizo-circulo-1">
                    <img src="<?php echo ( isset($this->configuracion['imagen_logo_1'])) ? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_logo_1']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_logo_1.svg'; ?>" alt="">
                </div>
                <div class="space"></div>
                <div class="logo-frizo-circulo-2">
                    <img src="<?php echo ( isset($this->configuracion['imagen_logo_2'])) ? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_logo_2']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_logo_2.svg'; ?>" alt="">
                </div>
            </div>
        </div>

        <?php if( $this->empresa['stand_config_estado_rv'] !== "1" ) : ?>
        <div class="logo-stand-vr">
            <div class="logo-stand-center-vr">
                <a style="<?php if( $this->empresa['enlace_rv'] == '' ) echo "pointer-events: none"; ?>" href="<?php echo $this->empresa['enlace_rv']; ?>" class="vr_open rv"><img src="imagenes/vr.svg" /></a>
            </div>
        </div>
        <?php endif; ?>

        <div class="logo-stand-circulo-plin">
            <div class="logo-stand-circulo-center-plin">
                <a onclick="Panel.validarSesion(event)" href="<?php echo $this->layout()->idiomaSeleccionado.'/panel/expositores-vivo/zona/'.$this->zona['orden'].'/empresa/'.$this->empresa['orden'].'/'.$this->empresa['hash_url']; ?>" class="en-vivo <?php if( $this->empresa['config_estado_boton_envivo'] == "1" ) echo "ocultar"; ?>"> <?php echo $this->layout()->language->translate(($this->empresa['titulo_boton_envivo']!='')?$this->empresa['titulo_boton_envivo']:'AGENDA TU CITA')['text']; ?><img src="imagenes/tin.svg" alt=""></a>
            </div>
        </div>

        <div class="logo-stand-circulo-distrito">
            <div class="logo-stand-circulo-distrito-center">
                <span><input type="text" data-text="tv_texto_1" value="<?php echo (isset($this->configuracion['tv_texto_1'])) ? $this->configuracion['tv_texto_1'] : ''; ?>"></span>
            </div>
        </div>

        <div class="paneles-stand-circulo">
            <div class="paneles-stand-circulo-middle">
                <div class="left-circulo">
                    <span><img src="imagenes/tin-green.svg" alt=""></span>
                    <a class="banner_izquierda_1 banner_1_open" href="#" data-tooltip="<?php echo $this->layout()->language->translate('MÁS INFORMACIÓN')['text']; ?>">
                        <img src="<?php echo ( isset($this->configuracion['imagen_banner_1'])) ? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_banner_1']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_banner_1.jpg'; ?>" alt="">
                    </a>
                </div>
                <div class="space-2"></div>
                <div class="center-circulo">
                    <span><img src="imagenes/tin-green.svg" alt=""></span>
                    <a href="<?php echo ( $this->empresa['enlace_video'] != '' ) ? $this->empresa['enlace_video'] : 'javascript:void(0)'; ?>" data-tooltip="<?php echo $this->layout()->language->translate('VER VIDEO')['text']; ?>" class="tv1_open">
                        <img src="<?php echo ( isset($this->configuracion['imagen_tv_1'])) ? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_tv_1']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_tv_1.jpg'; ?>" alt="">
                    </a>
                </div>
            </div>
        </div>

        <!--MODAL BANNER [INICIO]-->
        <div id="banner_1" class="well-zoom">
            <div class="modal-contents-zoom">
                <a href="javascript:abrirVentanaWindow('<?php echo ( $this->empresa['banner_izquierda_1'] != '' ) ? $this->empresa['banner_izquierda_1'] : ''; ?>')">
                    <img src="<?php echo ( isset($this->configuracion['imagen_banner_1'])) ? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_banner_1']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_banner_1.jpg'; ?>" alt="">
                </a>
            </div>
        </div>
        <!--MODAL BANNER [FIN]-->

        <div class="box-counter-circulo">
            <div class="box-counter-center-circulo">
                <img src="imagenes/counter-circular.png" alt="">
                <div class="logo-company imagen" data-id="imagen_logo_3" data-width="135" data-height="26" data-accept=".jpg,.jpeg,.png">
                <img src="<?php echo ( isset($this->configuracion['imagen_logo_3'])) ? $this->layout()->url_backend.'/paginas/stand-circular/'.$this->configuracion['imagen_logo_3']['hash'] : $this->layout()->url_backend.'/img/plantillas/stand-circular/imagen_logo_3.svg'; ?>" alt="">
                </div>
            </div>
        </div>

        <?php if( $this->empresa['enlace_wsp'] != '' ) : ?>
        <div class="navbar4">
            <div class="boton" style="animation-delay: 1.7s;">
                <a href="javascript:abrirVentanaWindow('<?php echo $this->empresa['enlace_wsp']; ?>')" data-tooltip="<?php echo $this->layout()->language->translate('CHATEA CON UN ASESOR')['text']; ?>" class="chat_open wsp"><img src="imagenes/logo-stands-02.svg" alt=""></a>
            </div>
        </div>
        <?php endif; ?>

        <?php if( $this->empresa['enlace_wsp_2'] != '' ) : ?>
        <div class="navbar4-2">
            <div class="boton" style="animation-delay: 1.7s;">
                <a href="javascript:abrirVentanaWindow('<?php echo $this->empresa['enlace_wsp_2']; ?>')" data-tooltip="<?php echo $this->layout()->language->translate('CHATEA CON UN ASESOR')['text']; ?>" class="chat_open wsp"><img src="imagenes/logo-stands-02.svg" alt=""></a>
            </div>
        </div>
        <?php endif; ?>

    </div>

    <?php
        echo $this->partial('partial/menus/banner-modulo', [
            'empresa'=> $this->empresa,
            'zona'=> $this->zona,
            'accion'=> 'stand',
            'totalProductos'=> $this->totalProductos,
            'totalPromociones'=> $this->totalPromociones,
            'totalPlanos'=> $this->totalPlanos,
            'class'=> '3'
        ]);
    ?>

    <a href="<?php echo $this->layout()->idiomaSeleccionado.'/panel/expositores-vivo/zona/'.$this->zona['orden'].'/empresa/'.$this->empresa['orden'].'/'.$this->empresa['hash_url']; ?>" id="toggle" class="en-vivo <?php if( $this->empresa['config_estado_boton_envivo'] == "1" ) echo "disabled"; ?>"><?php echo $this->layout()->language->translate(($this->empresa['titulo_boton_envivo']!='')?$this->empresa['titulo_boton_envivo']:'AGENDA TU CITA')['text']; ?>
        <img src="imagenes/tin.svg" alt="">
    </a>

    <div id="chat" class="well-chat">
        <div class="caja-chat">
            <h2><?php echo $this->layout()->language->translate('CONVERSA CON NOSOTROS')['text']; ?></h2>
            <div id="web_chat"></div>
            <div>
                <input type="text" id="name" placeholder="Nombre" class="campos-chat" /><br />
                <textarea placeholder="Escribe tu consulta..." id="text" class="campos-comentarios"></textarea>
                <input type="button" onclick="send();" value="ENVIAR" class="send-chat" /><br />
            </div>
        </div>
    </div>

    <?php if( $this->banco ) : ?>
    <h3><?php echo $this->layout()->language->translate('SOLICITA TU CREDITO AQUÍ')['text']; ?></h3>
    <a id="toggle"><img src="<?php echo ( $this->banco['hash_logo_small'] != '' ) ? $this->layout()->url_backend."/bancos/logo/".$this->banco['hash_logo_small'] : $this->layout()->url_backend."/img/no-imagen-small.jpg"; ?>" alt=""></a>
    <?php endif; ?>

</div>

<script>

    <?php $this->inlineScript()->captureStart(); ?>

    $('#banner_1').popup({
        transition: 'all 0.3s',
        closebutton: true
    });
    var toggle = document.getElementById("toggle");
    var content = document.getElementById("banco-modulo-2");
    toggle.addEventListener(
        "click",
        function () {
            content.classList.toggle("appear");
        },
        false
    );
    if(document.getElementById("closeButton")){
        document.getElementById("closeButton").addEventListener("click", function (e) {
            e.preventDefault();
            this.parentNode.style.display = "none";
        }, false);
    }

    <?php if( $this->fondo_video['estado'] ) : ?>
        anamorph("<?php echo $this->layout()->url_backend.'/paginas/stand-circular/'.$this->fondo_video['ruta']; ?>", 0.5, "https://www.jqueryscript.net/dummy/6.jpg");
    <?php endif; ?>

    <?php $this->inlineScript()->captureEnd(); ?>

</script>