<style>
    .agenda-estado {
        width: 100%;
        height: 20px;
    }
    .agenda-estado.confirmado {
        background-color: orange;
    }
    .agenda-estado.en-curso {
        background-color: green;
        color: #FFF;
        text-align: center;
    }
    .agenda-estado.finalizado {
        background-color: yellow;
    }
    .loader {
        --color: white;
        --size-mid: 6vmin;
        --size-dot: 1.5vmin;
        --size-bar: 0.4vmin;
        --size-square: 3vmin;
        
        display: block;
        position: relative;
        width: 100%;
        display: grid;
        place-items: center;
    }
    .loader::before,
    .loader::after {
        content: '';
        box-sizing: border-box;
        position: absolute;
    }

    .loader.--4::before {
        height: var(--size-bar);
        width: 6vmin;
        background-color: var(--color);
        animation: loader-4 0.8s cubic-bezier(0, 0, 0.03, 0.9) infinite;
    }
    @keyframes loader-4 {
        0%, 44%, 88.1%, 100% {
            transform-origin: left;
        }
        0%, 100%, 88% {
            transform: scaleX(0);
        }
        44.1%, 88% {
            transform-origin: right;
        }
        33%, 44% {
            transform: scaleX(1);
        }
    }
</style>

<div class="panel">
    <div class="panel-container show">
        <div class="panel-content">
            <table id="dataTables" class="table table-bordered table-hover table-striped w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>Empresa</th>
                        <th>Contacto</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Confirmado</th>
                        <th>En Curso</th>
                        <th>Finalizado</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<script>

    <?php $this->inlineScript()->captureStart(); ?>

    var tablaOpcionIzquierda = '';
    var tablaOpcionDerecha = '';
    var responsiveHelper_dataTables = undefined;
    var dataTable;
    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };
    dataTable = $('#dataTables').dataTable({
        "ajax": "/cliente/listar-agenda",
        "sDom": "<'row'<'col-xs-11 col-sm-6 tabla-opciones-izquierda'f><'col-sm-6 col-xs-1 tabla-opciones-derecha'>r>" +
                "t" +
                "<'row'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth": false,
        "oLanguage": {
            "sUrl": "js/datagrid/datatables/Spanish.json",
        },
        "aoColumnDefs": [
            {"bSortable": false, "aTargets": [1]}
        ],
        "preDrawCallback": function () {
            if (!responsiveHelper_dataTables) {
                responsiveHelper_dataTables = new ResponsiveDatatablesHelper($('#dataTables'), breakpointDefinition);
            }
        },
        "rowCallback": function (nRow) {
            responsiveHelper_dataTables.createExpandIcon(nRow);
        },
        "drawCallback": function (oSettings) {
            responsiveHelper_dataTables.respond();
            tablaOpcionIzquierda = $(".tabla-opciones-izquierda");
            tablaOpcionDerecha = $(".tabla-opciones-derecha");
        },
        "ordering": false,
        responsive: true
    });

    $(document).ready(function () {
        setTimeout(function(){
            
            tablaOpcionIzquierda.find(".input-group-addon").addClass("input-group-text d-inline-flex width-3 align-items-center justify-content-center border-bottom-right-radius-0 border-top-right-radius-0 border-right-0");
            tablaOpcionIzquierda.find(".input-group-addon").find("i").removeAttr("class").addClass("fas fa-search");
            tablaOpcionIzquierda.find("input[type='search']").attr("placeholder", "Buscar");
            tablaOpcionDerecha.append('<div class="opciones">'+
                '<button type="button" class="btn btn-info pop-up" style="display: none" href=""><i class="fas fa-plus"></i> <span class="hidden-xs">X</span></button> '+
            '</div>');

            iniciarFechasEnCurso();
            $(".agenda-estado.en-curso").find("i").show();
            setTimeout(() => {
                refrescarTiempoEnCurso();
            }, 2000);

        }, 700);
    });

    function refrescarTiempoEnCurso(){
        setInterval(() => {
            iniciarFechasEnCurso();
        }, 1000);
    }

    function iniciarFechasEnCurso(){
        console.log("Fecha Inicializado");
        $("table#dataTables tbody tr").each(function(){
            let estadoEnCurso = $(this).find("td").eq(5).find(".en-curso");
            //console.log("estadoEnCurso", estadoEnCurso.length);
            if(estadoEnCurso.length) {
                let date = $(this).find("td").eq(0).find(".agenda_fechas").text().trim().split("|");
                let fa = moment().format('YYYY-MM-DD HH:mm');
                let fi = date[0];
                let ff = date[1];
                let resultDate = moment(ff).diff(fa, 'minutes');
                console.log("resultDate", resultDate);
                if(resultDate){
                    estadoEnCurso.find("span").text(`${ resultDate } min restantes`);
                } else {
                    estadoEnCurso.parent().next("td").html('<div class="agenda-estado finalizado"></div>');
                    estadoEnCurso.parent().html("");
                }
            } 
        })
    }

    function listarDatos() {
        dataTable.api().ajax.reload(null, false);
    }

    function respuesta(response, mensaje) {
        ocultarModal();
        if (response.result == 'success') {
            listarDatos();
            alerta(mensaje, 'success');
        } else if (response.result == 'plan_excedido') {
            alerta('Según el plan asociado a la feria, solo puede crear como máximo '+response.data.cantidad_empresas_zonas+' empresas por zona', 'warning');
        }
    }

    <?php $this->inlineScript()->captureEnd(); ?>

</script>