<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Expositores</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-agregar-expositores" data-callback="respuesta(response, 'Expositores agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
        <div class="form-group">
            <label class="form-label">Feria</label>
            <span>
                <select class="select2 form-control" name="idferias">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->ferias as $item) : ?>
                    <option value="<?php echo $item['idferias'];?>" <?php if( $this->layout()->datosUsuario['idperfil'] == $item['idferias'] ) echo "selected='select'";  ?>><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <?php endif; ?>
        <div class="form-group">
            <label class="form-label">Nombres</label>
            <span>
                <input type="text" name="nombres" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Paterno</label>
            <span>
                <input type="text" name="apellido_paterno" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Materno</label>
            <span>
                <input type="text" name="apellido_materno" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Correo Electrónico</label>
            <span>
                <input type="text" name="correo" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Teléfono</label>
            <span>
                <input type="text" name="telefono" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Tipo Documento</label>
            <span>
                <select class="select2 form-control" name="tipo_documento">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="DNI">DNI</option>
                    <option value="CARNET DE EXTRANJERIA">CARNET DE EXTRANJERIA</option>
                    <option value="PASAPORTE">PASAPORTE</option>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">N° Documento</label>
            <span>
                <input type="text" name="numero_documento" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Enlace Conferencia Asesor</label>
            <span>
                <input type="text" name="enlace_conferencia_asesor" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Enlace Whatsapp</label>
            <span>
                <input type="text" name="enlace_wsp" class="form-control">
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-clock"></i>&nbsp;Horario de Atención</h2>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <label class="form-label">Hora Inicio</label>
                    <span>
                        <input type="text" name="hora_inicio[]" data-inputmask="'mask': '99:99'" class="form-control">
                    </span>
                </div>
                <div class="col-md-6">
                    <label class="form-label">Hora Fin</label>
                    <span>
                        <input type="text" name="hora_fin[]" data-inputmask="'mask': '99:99'" class="form-control">
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label class="form-label">Hora Inicio</label>
                    <span>
                        <input type="text" name="hora_inicio[]" data-inputmask="'mask': '99:99'" class="form-control">
                    </span>
                </div>
                <div class="col-md-6">
                    <label class="form-label">Hora Fin</label>
                    <span>
                        <input type="text" name="hora_fin[]" data-inputmask="'mask': '99:99'" class="form-control">
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Foto</h2>
        </div>
        <div class="form-group">   
            <div class="contenedor-imagen-personalizado">
                <img src="img/no-imagen.jpg" width="300" class="imagen">
                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 339 px de ancho y 267 px de alto</div>
                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                <input type="file" data-width="339" data-height="267" onchange="cambiarImagenDimension(this, event);" class="hidden" name="foto" accept=".jpg,.jpeg,.png" style="display: none;">
                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Foto Networking</h2>
        </div>
        <div class="form-group">   
            <div class="contenedor-imagen-personalizado">
                <img src="img/no-imagen.jpg" width="300" class="imagen">
                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 339 px de ancho y 267 px de alto</div>
                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                <input type="file" data-width="339" data-height="267" onchange="cambiarImagenDimension(this, event);" class="hidden" name="foto_networking" accept=".jpg,.jpeg,.png" style="display: none;">
                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Fondo Conferencia</h2>
        </div>
        <div class="form-group">   
            <div class="contenedor-imagen-personalizado">
                <img src="img/no-imagen.jpg" width="300" class="imagen">
                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 1200 px de ancho y 800 px de alto</div>
                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                <input type="file" data-width="1200" data-height="800" onchange="cambiarImagenDimension(this, event);" class="hidden" name="logo" accept=".jpg,.jpeg,.png" style="display: none;">
                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Expositores</button>
    </div>
</form>

<script>

    $(document).ready(function(){
        $(":input").inputmask();
    });

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: true
            },
            <?php endif;?>
            nombres: {
                required: true
            },
            numero_documento: {
                required: true,
                remote: "/cliente/validar-numero-documento"
            },
            correo: {
                required: false,
                email: true
            }
        },
        messages: {
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: 'Por favor, seleccione la feria'
            },
            <?php endif;?>
            nombres: {
                required: 'Por favor, ingrese los nombres'
            },
            numero_documento: {
                required: 'Por favor, ingrese el número de documento'
            },
            correo: {
                required: 'Por favor, ingrese el correo electrónico',
                email: 'Por favor, ingrese una dirección de correo electrónico válida'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>