<style>
    .stand-modelos{
        color: #fff!important;
    } 
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Empresas</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-agregar-empresas" data-callback="respuesta(response, 'Empresas agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <!-- TABS [INICIO] -->
        <div class="contenedor-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tab_default-1" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Información</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-2" role="tab"><i class="fas fa-fw fa-lg fa-cog"></i> Configuración</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-3" role="tab"><i class="fas fa-fw fa-lg fa-cog"></i> Stand Anuncio</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab_default-1" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Zona</label>
                        <span>
                            <select class="select2 form-control" name="idzonas">
                                <option value="" selected="select" disabled="">Seleccionar...</option>
                                <?php foreach($this->zonas as $item):?>
                                <option value="<?php echo $item['idzonas'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Nombre</label>
                        <span>
                            <input type="text" name="nombre" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Video 1</label>
                        <span>
                            <input type="text" name="enlace_video" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Video 2</label>
                        <span>
                            <input type="text" name="enlace_video_2" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Whatsapp 1</label>
                        <span>
                            <input type="text" name="enlace_wsp" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Whatsapp 2</label>
                        <span>
                            <input type="text" name="enlace_wsp_2" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Web</label>
                        <span>
                            <input type="text" name="enlace_web" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace RV</label>
                        <span>
                            <input type="text" name="enlace_rv" class="form-control">
                        </span>
                    </div>
                    <?php if( $this->layout()->datosUsuario['idperfil'] != '9'): ?>
                    <div class="form-group">
                        <label class="form-label">Stand</label>
                        <span>
                            <select class="select2 form-control select-stand" name="idstand">
                                <option value="" selected="select" disabled="">Seleccionar...</option>
                                <?php foreach($this->stand as $item):?>
                                <option value="<?php echo $item['idstand'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Modelo</label>
                        <div>
                            <a class="btn btn-dark pop-up-2 stand-modelos disabled">Seleccionar Modelo</a>
                            <input type="hidden" name="idstandgaleria" id="idstandgaleria">
                        </div>
                    </div>
                    <?php endif; ?>
                    <span class="opciones-banner" data-banner="izquierda" style="display: none;">
                        <div class="panel-hdr">
                            <h2><i class="fas fa-fw fa-lg fa-th-list"></i>&nbsp;Banner Izquierda</h2>
                        </div>
                        <div class="form-group" data-id="enlace_1">
                            <label class="form-label">Enlace 1</label>
                            <span>
                                <input type="text" name="banner_izquierda_1" class="form-control">
                            </span>
                        </div>
                        <div class="form-group" data-id="enlace_2">
                            <label class="form-label">Enlace 2</label>
                            <span>
                                <input type="text" name="banner_izquierda_2" class="form-control">
                            </span>
                        </div>
                    </span>
                    <span class="opciones-banner" data-banner="derecha" style="display: none;">
                        <div class="panel-hdr">
                            <h2><i class="fas fa-fw fa-lg fa-th-list"></i>&nbsp;Banner Derecha</h2>
                        </div>
                        <div class="form-group" data-id="enlace_1">
                            <label class="form-label">Enlace 1</label>
                            <span>
                                <input type="text" name="banner_derecha_1" class="form-control">
                            </span>
                        </div>
                        <div class="form-group" data-id="enlace_2">
                            <label class="form-label">Enlace 2</label>
                            <span>
                                <input type="text" name="banner_derecha_2" class="form-control">
                            </span>
                        </div>
                    </span>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-user"></i>&nbsp;Expositor</h2>
                    </div>
                    <div class="form-group">
                        <span>
                            <select class="select2 form-control" name="idexpositores">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->expositores as $item):?>
                                <option value="<?php echo $item['idexpositores'];?>"><?php echo $item['nombres'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-building"></i>&nbsp;Banco</h2>
                    </div>
                    <div class="form-group">
                        <span>
                            <select class="select2 form-control" name="idbancos">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->bancos as $item):?>
                                <option value="<?php echo $item['idbancos'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Logo</h2>
                    </div>
                    <div class="form-group">   
                        <div class="contenedor-imagen-personalizado">
                            <img src="img/no-imagen.jpg" width="300" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 492 px de ancho y 140 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="492" data-height="140" onchange="cambiarImagenDimension(this, event);" class="hidden" name="logo" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Logo Chat</h2>
                    </div>
                    <div class="form-group">   
                        <div class="contenedor-imagen-personalizado">
                            <img src="img/no-imagen.jpg" width="115" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 115 px de ancho y 115 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="115" data-height="115" onchange="cambiarImagenDimension(this, event);" class="hidden" name="logo_chat" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-2" role="tabpanel">
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-building"></i>&nbsp;Stand</h2>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Título Botón En Vivo</label>
                        <span>
                            <input type="text" name="titulo_boton_envivo" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-checkbox custom-control-inline mt-1">
                            <input type="checkbox" name="config_estado_boton_envivo" value="1" class="custom-control-input" id="defaultInline1">
                            <label class="custom-control-label" for="defaultInline1"><span class=""></span> Ocultar Botón En Vivo</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-checkbox custom-control-inline mt-1">
                            <input type="checkbox" name="stand_config_estado_rv" value="1" class="custom-control-input" id="defaultInline1StandRV">
                            <label class="custom-control-label" for="defaultInline1StandRV"><span class=""></span> Deshabilitar RV</label>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-3" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Título</label>
                        <span>
                            <input type="text" name="stand_anuncio_titulo" class="form-control" value="<?php echo $this->stand_anuncio_titulo; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Descripción</label>
                        <span>
                            <input type="text" name="stand_anuncio_descripcion" class="form-control" value="<?php echo $this->stand_anuncio_descripcion; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Duración en Segundo</label>
                        <span>
                            <input type="number" name="stand_anuncio_duracion_segundos" class="form-control" value="<?php echo $this->stand_anuncio_duracion_segundos; ?>">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <!-- TABS [FIN] -->
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Empresas</button>
    </div>
</form>

<script>

    $(".select-stand").change(function(){
        $("#idstandgaleria").val('');
        let idstand = $(this).val();
        let textModelo = $(".select-stand").find("option:selected").text();
        $(".stand-modelos").addClass("disabled");
        if(idstand!='')$(".stand-modelos").removeClass("disabled");
        $(".stand-modelos").text("Seleccionar modelo ("+textModelo+")").attr("href", "/cliente/modelos-stand?idstand="+idstand);
        validarOpcionesBanner(idstand);
    });

    var bannerIdsOpciones = ["izquierda","derecha"];

    function validarOpcionesBanner(idStandSelected) {
        //let idStandSelected = $(this).val();
        if( idStandSelected != '' ){
            for(let i in bannerIdsOpciones){
                //console.log(bannerIdsOpciones[i]);
                let opciones = $("[data-banner='"+bannerIdsOpciones[i]+"']");
                opciones.hide();
                opciones.each(function(){
                    $(this).find("[data-id='enlace_1'], [data-id='enlace_2']").hide();
                    switch(idStandSelected){
                        case '5': //Big
                        case '8': //Vip
                        case '9': //Big Scotiabank
                        case '11': //Stand Nuevo 2
                            $(this).find("[data-id='enlace_1'], [data-id='enlace_2']").show();
                            opciones.show();
                        break;
                        case '6': //Circular
                            if(bannerIdsOpciones[i] == 'izquierda'){
                                $(this).find("[data-id='enlace_1']").show();
                                opciones.show();
                            }
                        break;
                        case '7': //Standar
                        case '10': //Stand Nuevo 1
                            $(this).find("[data-id='enlace_1']").show();
                            opciones.show();
                        break;
                    }
                });
            }
        }
    }

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        ignore: [],
        rules: {
            idzonas: {
                required: true
            },
            nombre: {
                required: true
            },
            enlace_video: {
                required: true
            },
            enlace_wsp: {
                required: false
            },
            enlace_web: {
                required: true
            },
            enlace_rv: {
                required: false
            },
            idstand: {
                required: true
            },
            idstandgaleria: {
                required: true
            }
        },
        messages: {
            idzonas: {
                required: 'Por favor, seleccione la zona'
            },
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            enlace_video: {
                required: 'Por favor, ingrese el enlace de video'
            },
            enlace_wsp: {
                required: 'Por favor, ingrese el enlace del whatsapp'
            },
            enlace_web: {
                required: 'Por favor, ingrese el enlace de su web'
            },
            enlace_rv: {
                required: 'Por favor, ingrese el enlace de RV'
            },
            idstand: {
                required: 'Por favor, seleccione el stand'
            },
            idstandgaleria: {
                required: 'Por favor, seleccione el modelo del stand'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>
