<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Visitantes</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-agregar-visitantes" data-callback="respuesta(response, 'Visitantes agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
        <div class="form-group">
            <label class="form-label">Feria</label>
            <span>
                <select class="select2 form-control" name="idferias">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->ferias as $item):?>
                    <option value="<?php echo $item['idferias'];?>"><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <?php endif; ?>
        <div class="form-group">
            <label class="form-label">Nombres</label>
            <span>
                <input type="text" name="nombres" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Paterno</label>
            <span>
                <input type="text" name="apellido_paterno" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Apellido Materno</label>
            <span>
                <input type="text" name="apellido_materno" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Correo Electrónico</label>
            <span>
                <input type="text" name="correo" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Teléfono</label>
            <span>
                <input type="text" name="telefono" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Tipo Documento</label>
            <span>
                <select class="select2 form-control" name="tipo_documento">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="DNI">DNI</option>
                    <option value="CARNET DE EXTRANJERIA">CARNET DE EXTRANJERIA</option>
                    <option value="PASAPORTE">PASAPORTE</option>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">N° Documento</label>
            <span>
                <input type="text" name="numero_documento" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <div class="custom-control custom-checkbox custom-control-inline mt-1">
                <input type="checkbox" name="sala_premium" value="1" class="custom-control-input" id="defaultInline1">
                <label class="custom-control-label" for="defaultInline1"><span class=""></span> Sala Premium</label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Visitantes</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: true
            },
            <?php endif; ?>
            nombres: {
                required: true
            },
            numero_documento: {
                required: true,
                remote: "/cliente/validar-numero-documento"
            },
            correo: {
                required: true,
                email: true
            }
        },
        messages: {
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: 'Por favor, seleccione la feria'
            },
            <?php endif; ?>
            nombres: {
                required: 'Por favor, ingrese los nombres'
            },
            numero_documento: {
                required: 'Por favor, ingrese el número de documento'
            },
            correo: {
                required: 'Por favor, ingrese el correo electrónico',
                email: 'Por favor, ingrese una dirección de correo electrónico válida'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>