<style>
    .contenedor-tabs .tab-content{
        margin-top: 8px;
    }
    .contenedor-imagen-personalizado img.imagen{
        max-width: 50%;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Cronogramas</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-agregar-cronogramas" data-callback="respuesta(response, 'Cronogramas agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <!-- TABS [INICIO] -->
        <div class="contenedor-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tab_default-1" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Información</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-3" role="tab"><i class="fas fa-fw fa-lg fa-images"></i> Imagen</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-4" role="tab"><i class="fas fa-fw fa-lg fa-images"></i> Portada</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab_default-1" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Título</label>
                        <span>
                            <input type="text" name="titulo" class="form-control">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Fecha</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text fs-xl"><i class="fal fa-calendar"></i></span>
                            </div>
                            <input type="text" name="fecha" class="form-control calendario" value="<?php echo date('d/m/Y'); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="form-label">Hora Inicio</label>
                                <span>
                                    <input type="text" name="hora_inicio" data-inputmask="'mask': '99:99'" class="form-control">
                                </span>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Hora Fin</label>
                                <span>
                                    <input type="text" name="hora_fin" data-inputmask="'mask': '99:99'" class="form-control">
                                </span>
                            </div>
                        </div>
                    </div>
                    <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
                    <div class="form-group">
                        <label class="form-label">Feria</label>
                        <span>
                            <select class="select2 form-control" name="idferias">
                                <option value="" selected="select" disabled="">Seleccionar...</option>
                                <?php foreach($this->ferias as $item):?>
                                <option value="<?php echo $item['idferias'];?>"><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label class="form-label">Expositor</label>
                        <span>
                            <select class="select2 form-control" name="idexpositores">
                                <option value="" selected="select" disabled="">Seleccionar...</option>
                                <?php foreach($this->expositores as $item):?>
                                <option value="<?php echo $item['idexpositores'];?>"><?php echo $item['nombres'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Conferencia</label>
                        <span>
                            <select class="select2 form-control" name="idconferencias">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php foreach($this->conferencias as $item):?>
                                <option value="<?php echo $item['idconferencias'];?>"><?php echo $item['titulo'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Sala</label>
                        <span>
                            <select class="select2 form-control" name="idsalas">
                                <option value="" selected="select">Seleccionar...</option>
                                <?php $salasCategorias = ["R"=> "Regular", "P"=> "Premium"]; ?>
                                <?php foreach($this->salas as $item):?>
                                <option value="<?php echo $item['idsalas'];?>"><?php echo $item['nombre']. " (".$salasCategorias[$item['categoria']].")"; ?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-3" role="tabpanel">
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="img/no-imagen.jpg" width="536" class="imagen">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 536 px de ancho y 428 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="536" data-height="428" onchange="cambiarImagenDimension(this, event);" class="hidden" name="logo" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-4" role="tabpanel">
                    <?php if( empty($this->planes) || $this->planes['idplanes'] != '5') : ?>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Imagen Izquierda</h2>
                    </div>
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="img/no-imagen.jpg" width="492" class="imagen">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 492 px de ancho y 730 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="492" data-height="730" onchange="cambiarImagenDimension(this, event);" class="hidden" name="portada_izquierda" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Imagen Derecha</h2>
                    </div>
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="img/no-imagen.jpg" width="492" class="imagen">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 492 px de ancho y 730 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="492" data-height="730" onchange="cambiarImagenDimension(this, event);" class="hidden" name="portada_derecha" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- TABS [FIN] -->
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Cronogramas</button>
    </div>
</form>

<script>

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $(document).ready(function(){
        $(":input").inputmask();
    });

    $('.calendario').datepicker({
        language: 'es',
        orientation: "bottom left",
        autoclose: true
    });

    $("#validar_formulario").validate({
        ignore: [],
        rules: {
            titulo: {
                required: true
            },
            fecha: {
                required: true
            },
            hora_inicio: {
                required: true
            },
            hora_fin: {
                required: true
            },
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: true
            },
            <?php endif; ?>
            idexpositores: {
                required: true
            }
        },
        messages: {
            titulo: {
                required: 'Por favor, ingrese el titulo'
            },
            fecha: {
                required: 'Por favor, seleccione la fecha'
            },
            hora_inicio: {
                required: 'Por favor, ingrese la hora inicio'
            },
            hora_fin: {
                required: 'Por favor, ingrese el hora fin'
            },
            idferias: {
                required: 'Por favor, seleccione la feria'
            },
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: 'Por favor, seleccione la feria'
            },
            <?php endif; ?>
            idexpositores: {
                required: 'Por favor, seleccione los expositores'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>