<style>
.label-info {
    background-color: #5bc0de;
}
.label {
    display: inline;
    padding: .2em .6em .3em;
    font-size: 75%;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: .25em;
}
.bootstrap-tagsinput{
    width: 100%;
    height: calc(1.47em + 1rem + 2px);
    border: 1px solid #E5E5E5;
    box-shadow: none;
}
</style>

<div class="modal-header">
    <h4 class="modal-title">Configurar Correos</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-configurar-correos-ferias" data-callback="respuesta(response, 'Correo guardado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <input type="hidden" name="idferias" value="<?php echo $this->idferias; ?>">
        <div class="form-group">
            <label class="form-label">Plantilla</label>
            <span>
                <select class="select2 form-control" name="plantilla_correo">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->plantillaCorreos as $key => $item):?>
                    <option value="<?php echo $key;?>"><?php echo ucwords(mb_strtolower($item['value']));?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div data-config="correos" style="display:none;">
            <div class="form-group">
                <label class="form-label">Asunto</label>
                <span>
                    <input type="text" name="asunto" class="form-control">
                </span>
            </div>
            <div class="form-group">
                <label class="form-label">CC</label>
                <span>
                    <select class="tagsselect" name="correo_copia[]" multiple data-role="tagsinput"></select>
                </span>
            </div>
            <div class="form-group">
                <label class="form-label">Contenido</label>
                <span>
                    <textarea name="contenido" id="editor" class="form-control"></textarea>
                </span>
            </div>
            <div data-option="contenido" style="display: none;">
                <div class="opciones" data-option="visitante">
                    <!-- <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Enlaces Redes Sociales</h2>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Facebook</label>
                                <span>
                                    <input type="text" name="config_facebook_compartir_url" class="form-control">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Twitter</label>
                                <span>
                                    <input type="text" name="config_twitter_compartir_url" class="form-control">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Whatsapp</label>
                                <span>
                                    <input type="text" name="config_whatsapp_compartir_url" class="form-control">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">LinkedIn</label>
                                <span>
                                    <input type="text" name="config_linkedin_compartir_url" class="form-control">
                                </span>
                            </div>
                        </div>
                    </div> -->
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Pie Página</h2>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">Texto Primera Línea</label>
                                <span>
                                    <input type="text" name="config_pie_pagina_titulo_linea_1" class="form-control">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">Texto Segunda Línea</label>
                                <span>
                                    <input type="text" name="config_pie_pagina_titulo_linea_2" class="form-control">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">Texto Tercera Línea</label>
                                <span>
                                    <input type="text" name="config_pie_pagina_titulo_linea_3" class="form-control">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="panel-hdr">
                                <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Fondo</h2>
                            </div>
                            <div class="form-group">
                                <div class="contenedor-imagen-personalizado">
                                    <img src="img/no-imagen.jpg" width="165" class="imagen imagen-fondo" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 1500 px de ancho y 2184 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="1500" data-height="2184" onchange="cambiarImagenDimension(this, event);" class="hidden files-img" name="config_hash_fondo_plantilla" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                            <div class="panel-hdr">
                                <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Logo Feria</h2>
                            </div>
                            <div class="form-group">
                                <div class="contenedor-imagen-personalizado">
                                    <img src="img/no-imagen.jpg" width="165" class="imagen imagen-logo-feria" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 300 px de ancho y 145 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="300" data-height="145" onchange="cambiarImagenDimension(this, event);" class="hidden files-img" name="config_hash_logo_feria" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="panel-hdr">
                                <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Logo Cliente</h2>
                            </div>
                            <div class="form-group">
                                <div class="contenedor-imagen-personalizado">
                                    <img src="img/no-imagen.jpg" width="165" class="imagen imagen-logo-cliente" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 270 px de ancho y 50 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="270" data-height="50" onchange="cambiarImagenDimension(this, event);" class="hidden files-img" name="config_hash_logo_cliente" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                            <div class="panel-hdr">
                                <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;QR</h2>
                            </div>
                            <div class="form-group">
                                <div class="contenedor-imagen-personalizado">
                                    <img src="img/no-imagen.jpg" width="165" class="imagen imagen-qr" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 165 px de ancho y 163 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="165" data-height="163" onchange="cambiarImagenDimension(this, event);" class="hidden files-img" name="config_hash_qr" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Datos</button>
    </div>
</form>

<script>

    var contenidoCorreo = CKEDITOR.replace('editor');

    contenidoCorreo.on('change', function(evt) {
        $("textarea[name='contenido']").html(evt.editor.getData());
    });

    $("select[name='plantilla_correo']").change(function(){
        let plantilla = $(this).val();
        let contenidoOpcion = $("div[data-option='contenido']");
        contenidoOpcion.hide();
        contenidoOpcion.find(".opciones").hide();
        $(".files-img").val(""); //Limpiar el valor de la imagen seleccionada
        if(plantilla != '') {
            $("[data-config='correos']").show();
            $.post("/cliente/obtener-plantilla-correos", {idferias: '<?php echo $this->idferias; ?>', plantilla: plantilla}, function(data){
                if(Object.keys(data).length){
                    console.log("data", data);
                    $("input[name='asunto']").val(data.asunto);
                    $("input[name='config_facebook_compartir_url']").val(data.config_facebook_compartir_url);
                    $("input[name='config_twitter_compartir_url']").val(data.config_twitter_compartir_url);
                    $("input[name='config_whatsapp_compartir_url']").val(data.config_whatsapp_compartir_url);
                    $("input[name='config_linkedin_compartir_url']").val(data.config_linkedin_compartir_url);
                    $("input[name='config_pie_pagina_titulo_linea_1']").val(data.config_pie_pagina_titulo_linea_1);
                    $("input[name='config_pie_pagina_titulo_linea_2']").val(data.config_pie_pagina_titulo_linea_2);
                    $("input[name='config_pie_pagina_titulo_linea_3']").val(data.config_pie_pagina_titulo_linea_3);
                    CKEDITOR.instances.editor.setData(data.contenido);
                    if(data.correo_copia != ''){
                        let correos_copia = data.correo_copia.split(",");
                        if(correos_copia.length){
                            $("select[name='correo_copia[]']").html('');
                            correos_copia.forEach(function(item){
                                let option = $('<option>');
                                option.attr("value", item),
                                option.text(item);
                                $("select[name='correo_copia[]']").append(option);
                            });
                            tagsSelect('restart');
                        }
                    }

                    $(".imagen").attr("src", "img/no-imagen.jpg")
                    //Mostrar imagen QR
                    if(data.config_hash_qr != null) {
                        $(".imagen-qr").attr("src", "correos/imagen/" + data.config_hash_qr)
                    }
                    //Mostrar imagen fondo
                    if(data.config_hash_fondo_plantilla != null) {
                        $(".imagen-fondo").attr("src", "correos/imagen/" + data.config_hash_fondo_plantilla)
                    }
                    //Mostrar imagen fondo
                    if(data.config_hash_logo_cliente != null) {
                        $(".imagen-logo-cliente").attr("src", "correos/imagen/" + data.config_hash_logo_cliente)
                    }
                    //Mostrar imagen fondo
                    if(data.config_hash_logo_feria != null) {
                        $(".imagen-logo-feria").attr("src", "correos/imagen/" + data.config_hash_logo_feria)
                    }
                } else {
                    tagsSelect('delete');
                    CKEDITOR.instances.editor.setData('');
                }
            }, 'json');
            
            //Mostrar opciones por tipo de plantilla
            let contenidoOpcionSeleccionado = $("div[data-option='"+plantilla+"']");
            if(plantilla == 'visitante' && contenidoOpcionSeleccionado.length) {
                contenidoOpcionSeleccionado.show();
                contenidoOpcion.show();
            }
        
        }
    });

    function tagsSelect(accion){
        switch(accion){
            case 'delete':
                $(".tagsselect").html(''),
                $(".tagsselect").tagsinput('destroy');
                $(".tagsselect").tagsinput('items');
            break;
            case 'restart':
                $(".tagsselect").tagsinput('destroy');
                $(".tagsselect").tagsinput('items');
            break;
        }
    }

    $(".select2").select2();
    $(".tagsselect").tagsinput('items');

    $("#validar_formulario").validate({
        ignore: [],
        rules: {
            para: {
                required: true,
                email: true,
            },
            asunto: {
                required: true
            },
            correo_copia: {
                required: true
            }
        },
        messages: {
            para: {
                required: 'Por favor, ingrese el correo electrónico',
                email: 'Por favor, ingrese una dirección de correo electrónico válida'
            },
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

</script>