<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Personalizar Ferias</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-configurar-ferias" data-callback="respuesta(response, 'Configuración guardado correctamente.')" autocomplete="off">
    <input type="hidden" name="idferias" value="<?php echo $this->idferias; ?>">
    <div class="modal-body">
        <div class="contenedor-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tab_default-1" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Información</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-2" role="tab"><i class="fas fa-fw fa-lg fa-object-ungroup"></i> Auditorio</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-3" role="tab"><i class="fas fa-fw fa-lg fa-object-ungroup"></i> Promoción</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-4" role="tab"><i class="fas fa-fw fa-lg fa-list"></i> Páginas</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-5" role="tab"><i class="fas fa-fw fa-lg fa-list"></i> Registro</a></li>
            </ul>
            <div class="tab-content">
                <!-- INICIO TAB -->
                <div class="tab-pane fade show active" id="tab_default-1" role="tabpanel">
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-info"></i>&nbsp;Términos y Condiciones</h2>
                    </div>
                    <div class="form-group">
                        <span>
                            <textarea rows="6" class="form-control" name="config_terminos_condiciones"><?php echo $this->config_terminos_condiciones; ?></textarea>
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-search"></i>&nbsp;Buscador</h2>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Título</label>
                        <span>
                            <input type="text" name="config_buscador_titulo" class="form-control" value="<?php echo $this->config_buscador_titulo; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Fondo</label>
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->config_buscador_hash_fondo != '' ) ? 'buscador/fondo/'.$this->config_buscador_hash_fondo : 'plantillas/imagenes/fondo-buscador.jpeg'; ?>" width="1280" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 1280 px de ancho y 367 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="1280" data-height="367" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_buscador_fondo" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-object-ungroup"></i>&nbsp;Portada</h2>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Favicon</label>
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->config_hash_favicon != '' ) ? 'portal/favicon/'.$this->config_hash_favicon : 'img/not-favicon.jpg'; ?>" width="50" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 50 px de ancho y 47 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="50" data-height="47" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_hash_favicon" accept=".jpg,.jpeg,.png" style="display: none;" data-imagen-inicial="img/not-favicon.jpg">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-users"></i>&nbsp;Asesor Banner</h2>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Color Texto</label>
                                <span>
                                    <input type="color" name="config_asesor_banner_color_texto" class="form-control" value="<?php echo $this->config_asesor_banner_color_texto; ?>">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="form-label">Color Fondo</label>
                                <span>
                                    <input type="color" name="config_asesor_banner_color_fondo" class="form-control" value="<?php echo $this->config_asesor_banner_color_fondo; ?>">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Fondo Correo</h2>
                    </div>
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->config_fondo_correo_hash_imagen != '' ) ? 'ferias/correos/fondos/'.$this->config_fondo_correo_hash_imagen : 'img/no-imagen.jpg'; ?>" width="160" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 682 px de ancho y 1024 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="682" data-height="1024" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_fondo_correo_hash_imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-2" role="tabpanel">
                    <div class="panel-hdr">
                        <h2>Fondo</h2>
                    </div>
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->config_auditorio_hash_fondo != '' ) ? 'auditorio/fondo/'.$this->config_auditorio_hash_fondo : 'auditorio/fondo-inicial.jpg'; ?>" width="1723" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 1723 px de ancho y 835 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="1723" data-height="835" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_auditorio_fondo" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2>Video Fondo</h2>
                    </div>
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->config_auditorio_hash_video_fondo_inicial != '' ) ? 'auditorio/fondo/'.$this->config_auditorio_hash_video_fondo_inicial : 'auditorio/video-inicial.jpg'; ?>" width="710" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 710 px de ancho y 402 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="710" data-height="402" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_auditorio_hash_video_fondo_inicial" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2>Banner Inicial</h2>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="form-label">Fondo Izquierda</label>
                                <div class="contenedor-imagen-personalizado">
                                    <img src="<?php echo ( $this->config_auditorio_hash_banner_izquierdo_inicial != '' ) ? 'auditorio/fondo/'.$this->config_auditorio_hash_banner_izquierdo_inicial : 'cronogramas/portada-no-imagen.jpg'; ?>" width="492" class="imagen" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 492 px de ancho y 730 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="492" data-height="730" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_auditorio_hash_banner_izquierdo_inicial" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label">Fondo Derecha</label>
                                <div class="contenedor-imagen-personalizado">
                                    <img src="<?php echo ( $this->config_auditorio_hash_banner_derecho_inicial != '' ) ? 'auditorio/fondo/'.$this->config_auditorio_hash_banner_derecho_inicial : 'cronogramas/portada-no-imagen.jpg'; ?>" width="492" class="imagen" alt="">
                                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 492 px de ancho y 730 px de alto</div>
                                    <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                                    <input type="file" data-width="492" data-height="730" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_auditorio_hash_banner_derecho_inicial" accept=".jpg,.jpeg,.png" style="display: none;">
                                    <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-3" role="tabpanel">
                    <div class="panel-hdr">
                        <h2>Fondo</h2>
                    </div>
                    <div class="form-group">
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->config_promocion_hash_imagen != '' ) ? 'promocion/imagen/'.$this->config_promocion_hash_imagen : 'promocion/no-imagen.jpg'; ?>" width="701" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 701 px de ancho y 701 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="701" data-height="701" onchange="cambiarImagenDimension(this, event);" class="hidden" name="config_promocion_hash_imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-4" role="tabpanel">
                    <div class="panel-hdr">
                        <h2>Recepción</h2>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Video Presentación</label>
                        <span>
                            <input type="text" name="config_pagina_enlace_video_presentacion" class="form-control" value="<?php echo $this->config_pagina_enlace_video_presentacion; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Video Tutorial</label>
                        <span>
                            <input type="text" name="config_pagina_enlace_video_tutorial" class="form-control" value="<?php echo $this->config_pagina_enlace_video_tutorial; ?>">
                        </span>
                    </div>
                </div>
                <!-- FIN TAB -->
                <!-- INICIO TAB -->
                <div class="tab-pane fade" id="tab_default-5" role="tabpanel">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label class="form-label">Título</label>
                                <span>
                                    <input type="text" name="config_formulario_titulo" class="form-control" value="<?php echo $this->config_formulario_titulo; ?>">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="form-label">Móvil</label>
                                <span>
                                    <input type="color" name="config_formulario_titulo_color_movil" class="form-control" value="<?php echo $this->config_formulario_titulo_color_movil; ?>">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="form-label">Desktop</label>
                                <span>
                                    <input type="color" name="config_formulario_titulo_color_desktop" class="form-control" value="<?php echo $this->config_formulario_titulo_color_desktop; ?>">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label class="form-label">Subtítulo</label>
                                <span>
                                    <input type="text" name="config_formulario_subtitulo" class="form-control" value="<?php echo $this->config_formulario_subtitulo; ?>">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="form-label">Móvil</label>
                                <span>
                                    <input type="color" name="config_formulario_subtitulo_color_movil" class="form-control" value="<?php echo $this->config_formulario_subtitulo_color_movil; ?>">
                                </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="form-label">Desktop</label>
                                <span>
                                    <input type="color" name="config_formulario_subtitulo_color_desktop" class="form-control" value="<?php echo $this->config_formulario_subtitulo_color_desktop; ?>">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN TAB -->
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-info btn-submit btn-uploader-form" data-id-form="validar_formulario">Guardar Cambios</button>
    </div>
</form>

<script>

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        var dataImagenInicial = $(obj).attr("data-imagen-inicial");
        dataImagenInicial = (dataImagenInicial !== undefined ) ? dataImagenInicial : 'img/no-imagen.jpg';
        if(typeof event.target.files[0] === "undefined"){
            return;
        }
        var sizeMB = parseFloat((event.target.files[0].size / (1024*1024)).toFixed(2));
        if(sizeMB > 3){
            alert("La imagen que intenta subir no debe pesar mas de 3M. Por favor, intente subir otra imagen.")
            return;
        }
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", dataImagenInicial);
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

    $("#validar_formulario").validate({
        rules: {
            config_terminos_condiciones:{
                required: false
            },
            config_buscador_titulo:{
                required: true
            },
        },
        messages: {},
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }/*,
        submitHandler: function(form) {
            guardarDatos($(form).serialize());
        }*/
    });


    function guardarDatos(data) {
        $.post("/cliente/guardar-configurar-ferias",data,function(response){
            if(response.result === 'success') {
                ocultarModal();
                alerta('Configuración guardado correctamente.', 'success');
            }
        }, 'json');
    }

</script>