<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Páginas Ferias</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-editar-paginas-ferias?idpaginasferias=<?php echo $this->idpaginasferias; ?>" data-callback="respuesta(response, 'Páginas Ferias actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Feria</label>
            <span>
                <select class="select2 form-control" name="idferias">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->ferias as $item):?>
                    <option value="<?php echo $item['idferias'];?>" <?php if( $this->idferias == $item['idferias'] ) echo "selected='select'"; ?>><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Página</label>
            <span>
                <select class="select2 form-control" name="idpaginas">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->paginas as $item):?>
                    <option value="<?php echo $item['idpaginas'];?>" <?php if( $this->idpaginas == $item['idpaginas'] ) echo "selected='select'"; ?>><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            idpaginas: {
                required: true
            },
            idferias: {
                required: true
            }
        },
        messages: {
            idpaginas: {
                required: 'Por favor, seleccione la página'
            },
            idferias: {
                required: 'Por favor, seleccione la feria'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>