<style>
    .icon-success{
        color: #24ad24
    }
    .tabla-opciones-izquierda-visitantes .panel-row {
        display: inline-block;
        vertical-align: middle;
        margin-right: 4px;
    }
    .tabla-opciones-izquierda-visitantes .panel-row:last-child {
        margin-right: 0px;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Visitantes</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form autocomplete="off">
    <div class="modal-body">
        <table id="dataTablesTarjetas" class="table table-bordered table-hover table-striped w-100">
            <thead>
                <tr>
                    <th width="120">Nombres</th>
                    <th width="160">Apellido Paterno</th>
                    <th>Apellido Materno</th>
                    <th>Correo</th>
                    <th>Teléfono</th>
                    <th>N° Documento</th>
                    <th>Fecha Registro</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
    </div>
</form>

<script>

    var tablaOpcionIzquierdaTarjetas = '';
    var tablaOpcionDerechaTarjetas = '';
    var responsiveHelper_dataTablesTarjetas = undefined;
    var dataTablesTarjetas;
    var breakpointDefinitionDataTablesTarjetas = {
        tablet: 1024,
        phone: 480
    };
    dataTablesTarjetas = $('#dataTablesTarjetas').dataTable({
        "ajax": "/cliente/listar-ferias-visitantes?idferias=<?php echo $this->idferias; ?>&rango_fechas=<?php echo date("d/m/Y",time()-(3600*24*3));?> - <?php echo date("d/m/Y");?>",
        "sDom": "<'row'<'col-xs-11 col-sm-6 tabla tabla-opciones-izquierda-visitantes m-b-6'><'col-sm-6 col-xs-1 tabla tabla-opciones-derecha-visitantes m-b-6'>r>" +
                "t" +
                "<'row'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth": false,
        "oLanguage": {
            "sUrl": "js/datagrid/datatables/Spanish.json",
        },
        "aoColumnDefs": [
            {"bSortable": false, "aTargets": [0]}
        ],
        "preDrawCallback": function () {
            if (!responsiveHelper_dataTablesTarjetas) {
                responsiveHelper_dataTablesTarjetas = new ResponsiveDatatablesHelper($('#dataTablesTarjetas'), breakpointDefinitionDataTablesTarjetas);
            }
        },
        "rowCallback": function (nRow) {
            responsiveHelper_dataTablesTarjetas.createExpandIcon(nRow);
        },
        "drawCallback": function (oSettings) {
            responsiveHelper_dataTablesTarjetas.respond();
            tablaOpcionIzquierdaTarjetas = $(".tabla-opciones-izquierda-visitantes");
            tablaOpcionDerechaTarjetas = $(".tabla-opciones-derecha-visitantes");
        },
        "ordering": false,
        responsive: true
    });

    $(document).ready(function () {
        setTimeout(function(){
            
            tablaOpcionIzquierdaTarjetas.find(".input-group-addon").addClass("input-group-text d-inline-flex width-3 align-items-center justify-content-center border-bottom-right-radius-0 border-top-right-radius-0 border-right-0");
            tablaOpcionIzquierdaTarjetas.find(".input-group-addon").find("i").removeAttr("class").addClass("fas fa-search");
            tablaOpcionIzquierdaTarjetas.find("input[type='search']").attr("placeholder", "Buscar");
            tablaOpcionDerechaTarjetas.append('<div class="opciones">'+
                '<button class="btn btn-success" onclick="Panel.exportarFeriaVisitantes(this)"><i class="fas fa-file-excel"></i> Exportar</button>'+
            '</div>');

            var divRow = $("<div/>").addClass("panel-row");
            var input = $("<input/>");
                input.attr('type','text').addClass('form-control datepicker rango-fechas');
            var divGroup = $("<div/>");
                divGroup.addClass('input-group-append').append('<span class="input-group-text fs-xl"><i class="fal fa-calendar"></i></span>');
            var div = $("<div/>");
                div.addClass('input-group').css({'width': '208px'});
                div.append(input).append(divGroup);
            $(".tabla-opciones-izquierda-visitantes").append(divRow);
            divRow.append(div);

            $('.rango-fechas').daterangepicker({
                "startDate": "<?php echo date("d/m/Y",time()-(3600*24*3));?>",
                "endDate": "<?php echo date("d/m/Y");?>",
                opens: 'rigth',
                locale: {
                    format: 'DD/MM/YYYY',
                    daysOfWeek: ["Do","Lu","Ma","Mi","Ju","Vi","Sa"],
                    monthNames: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Augosto","Setiembre","Octubre","Noviembre","Diciembre"],
                    "applyLabel": "Aceptar",
                    "cancelLabel": "Cancelar"
                }
            });

            $('.rango-fechas').change(function(){
                dataTablesTarjetas.api().ajax.url("/cliente/listar-ferias-visitantes?idferias=<?php echo $this->idferias; ?>&rango_fechas="+$(".rango-fechas").val()).load();
            });

        }, 700);
    });

    var Panel = {
        exportarFeriaVisitantes: function(obj){
            let _this = this;
            $(obj).html('<i class="fas fa-sync fa-spin"></i> Descargando reporte...');
            $.post("cliente/descargar-reporte-feria-visitantes", {idferias: '<?php echo $this->idferias; ?>', rango_fechas: $(".rango-fechas").val()}, function(response){
                if(response.result == 'success'){
                    $(obj).html('<i class="fas fa-file-excel"></i> Exportar');
                    _this.downloadURI('tmp/reporte_visitantes.xlsx', 'Reporte Feria Visitantes.xlsx');
                }
            }, 'json');
        },
        downloadURI: function (uri, name) {
            var link = document.createElement("a");
            link.setAttribute('download', name);
            link.href = uri;
            document.body.appendChild(link);
            link.click();
            link.remove();
        }
    };

</script>