<style>
    .scroll-chat {
        max-height: 50vh;
        overflow-x: hidden;
        border: 1px solid #e6e6e6;
        border-radius: 12px 0px 0px 12px;
    }
    .scroll-chat::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
        background-color: #F5F5F5;
    }
    .scroll-chat::-webkit-scrollbar {
        width: 6px;
        background-color: #F5F5F5;
    }
    .scroll-chat::-webkit-scrollbar-thumb {
        background-color: #808080;
    }
    #chat_container .m-0{
        margin: 0;
    }
    .badge-tooltip{
        font-size: 90%;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Chat Historial</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<form autocomplete="off">
    <div class="modal-body">
        <div id="chat_container" class="w-100 p-4 scroll-chat">
            <?php if(!empty($this->historial)) : ?>
                <?php foreach($this->historial as $date => $dataMensaje): ?>
                <div class="chat-segment">
                    <div class="time-stamp text-center mb-2 fw-400"><?php echo date('d/m/Y', strtotime($date)); ?></div>
                </div>
                <?php foreach($dataMensaje as $mensaje): ?>
                <div class="chat-segment chat-segment-<?php echo ($mensaje['type'] === 'V') ? 'sent' : 'get'; ?>">
                    <div class="chat-message">
                        <p><strong><?php echo $mensaje['user']; ?></strong></p>
                        <p><?php echo $mensaje['msg']; ?></p>
                    </div>
                    <div class="<?php echo ($mensaje['type'] === 'V') ? 'text-right' : ''; ?> fw-300 text-muted mt-1 fs-xs"><?php echo $mensaje['time']; ?></div>
                </div>
                <?php endforeach; ?>
                <?php endforeach; ?>
            <?php else: ?>
            <p class="m-0">No se encontraron mensajes...</p>
            <?php endif; ?>
        </div>
        <?php if(!empty($this->historial)): ?>
        <br>
        <div class="demo">
            <button type="button" class="btn btn-dark badge-tooltip" onclick="descargarChat(this)" data-toggle="tooltip" data-placement="auto" title="" data-original-title="Click para descargar chat"><i class="fas fa-download"></i> Descargar Chat</button>
        </div>
        <?php endif; ?>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
    </div>
</form>

<script>
    $(".badge-tooltip").tooltip();

    function descargarChat(obj){
        $(obj).addClass("disabled");
        $.post("/cliente/descargar-historial-chat", {id: '<?php echo $this->id; ?>'}, function(response){
            if(response.result === 'success') {
                downloadURI('chats/historial/' + response.file, 'Historial_Chat.txt');
            }
            $(obj).removeClass("disabled");
        },'json');
    }

    /*function downloadURI (uri, name) {
        var link = document.createElement("a");
        link.setAttribute('download', name);
        link.href = uri;
        document.body.appendChild(link);
        link.click();
        link.remove();
    }*/

</script>