<style>
    .custom-file{
        margin-bottom: 6px;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Importar Visitantes</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-importar-visitantes" data-callback="respuesta(response, 'Visitantes Importado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
        <div class="form-group">
            <label class="form-label">Feria</label>
            <span>
                <select class="select2 form-control" name="idferias">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->ferias as $item):?>
                    <option value="<?php echo $item['idferias'];?>"><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <?php endif; ?>
        <div class="form-group">
            <label class="form-label">Archivo <span class="importante">(*)</span></label>
            <div class="custom-file">
                <input type="file" name="archivo" accept=".csv" class="custom-file-input adjuntar" onchange="this.nextElementSibling.textContent = this.value">
                <label class="custom-file-label">Elija el archivo</label>
            </div>
            <a download="Formato Visitantes" href="formatos/visitantes.xlsx">
                <div class="alert alert-warning" role="alert">
                    <strong>Click para descargar formato excel</strong>
                </div>
            </a>
        </div>
        <div class="form-group">
            <div class="custom-control custom-checkbox custom-control-inline mt-1">
                <input type="checkbox" name="sala_premium" value="1" class="custom-control-input" id="defaultInline1">
                <label class="custom-control-label" for="defaultInline1"><span class=""></span> Sala Premium</label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Importar Visitantes</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: true
            },
            <?php endif; ?>
            archivo: {
                required: true
            }
        },
        messages: {
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: 'Por favor, seleccione la feria'
            },
            <?php endif; ?>
            archivo: {
                required: 'Por favor, seleccione el archivo'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>