<style>
    .panel-virtual .titulo{
        padding: 2%;
        background: #3da3c1;
        color: #fff;
        font-size: 20px;
        font-weight: 600;
        width: 100%;
        text-align: center;
        border-radius: 15px;
        height: 40px;
        line-height: 1;
    }
    .panel-virtual .opciones{
        margin-top: 8px;
    }
    .panel-virtual .opciones .panel{
        margin-bottom: 8px;
    }
    .panel-virtual .opciones .panel > * {
        display: inline-block;
        vertical-align: middle;
        margin-right: -2px;
    }
    .panel-virtual .opciones .panel .imagen {
        width: 10%;
        height: 40px;
        background: #3da3c1;
        border-radius: 15px 0 0 15px;
        text-align: center;
        padding: 6px;
        cursor: move;
    }
    .panel-virtual .opciones .panel .imagen img {
        width: 25px;
    }
    .panel-virtual .opciones .panel .input {
        width: 90%;
        /*height: 40px;*/
    }
    .panel-virtual .opciones .panel .input input {
        height: 40px;
        border: none;
        background: #fff;
        font-size: 20px;
        width: 100%;
        text-align: left;
        color: #1b3362;
        font-weight: 600;
        font-style: italic;
        text-decoration: none;
        border-bottom: 0.1px solid #dadada;
        padding-left: 12px;
    }
    .panel-virtual .opciones .panel .input input:focus {
        outline: none;
        border-bottom: 0.1px solid #6b6a6a;
    }
    .select-opciones{
        margin-top: 0;
        padding: 0;
        width: 100%;
        background-color: inherit;
        outline: 0px;
    }
    .select-opciones option{
        color: inherit;
    }
    .select-opciones.valid{
        color: #999;
    }
</style>

<div class="modal-header">
    <div class="close-modal" data-dismiss="modal" aria-label="Close"><i class="fas fa-times"></i></div>
    <h4 class="modal-title">Auditorio Virtual</h4>
</div>
<form id="validar_formulario">
    <div class="modal-body">
        <div class="panel-virtual">
            <div class="titulo">AUDITORIO VIRTUAL</div>
            <div class="opciones"></div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-info">Cambiar Orden</button>
    </div>
</form>

<script>

    $(document).ready(function(){
        cargarDatosOpciones();
    });

    $(".panel-virtual .opciones").sortable({
        containment: "parent"
    });
    $("#validar_formulario").validate({
        rules: {
            virtual_conferencias: {
                required: false,
                maxlength: 19,
                minlength: 1
            },
            virtual_zona: {
                required: false,
                maxlength: 19,
                minlength: 1
            },
            virtual_auditorio: {
                required: false,
                maxlength: 19,
                minlength: 1
            },
            buscador: {
                required: false,
                maxlength: 19,
                minlength: 1
            }
        },
        messages: {},
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
            var data = [];
            var i = 0;
            $(".panel-virtual .opciones .panel").each(function(){
                let key = $(this).find("input[type='text']").attr("name");
                let value = $(this).find("input[type='text']").val();
                let url = $(this).find("select[data-banner='url']").val();
                data.push({key: key, value: value, order: i, url: url});
                i++;
            });
            $("input[name='hall_conferencias_opciones']").val(JSON.stringify(data));
            ordenarOpciones(data);
            ocultarModal();
        }
    });

    function ordenarOpciones(data){
        var navbarConference = $(".navbar-conference");
        var plantillaConference = '<div class="marco-boton"><img src="plantillas/imagenes/iconos-menu-03.svg" width="30%"></div><a href="javascript:void(0)">PROG. CONFERENCIAS</a><input type="hidden" data-banner="url">';
        if(data.length > 0){
            navbarConference.find(".lista-opciones").html('');
            for(i in data){
                let div = $('<div>').addClass("boton-conference").html(plantillaConference);
                let nombreImagen = '';
                if( data[i].key == 'virtual_conferencias' )nombreImagen = 'iconos-menu-03.svg';
                else if( data[i].key == 'virtual_zona' )nombreImagen = 'iconos-menu-agenda.svg';
                else nombreImagen = 'iconos-menu-01.svg';
                div.attr("data-key", data[i].key);
                div.find("img").attr("src", "plantillas/imagenes/" + nombreImagen);
                div.find("a").text(data[i].value);
                div.find("input[data-banner='url']").val(data[i].url);
                navbarConference.find(".lista-opciones").append(div);
            }
        }
    }

    function cargarDatosOpciones(){
        var panelVirtual = $(".panel-virtual");
        var plantillaOpciones = '<div class="imagen">'+
            '<img src="">'+
        '</div>'+
        '<div class="input">'+
            '<input type="text" data-banner="name">'+
            '<select class="select-opciones" data-banner="url">'+
                <?php foreach($this->menusEncabezado as $item) : ?>
                '<option value="<?php echo $item['hash_url']; ?>"><?php echo $item['nombre']; ?></option>'+
                <?php endforeach; ?>
            '</select>'+
        '</div>';
        $(".lista-opciones .boton-conference").each(function(){
            let img = $(this).find("img").attr("src").split('plantillas/imagenes/')[1];
            let text = $(this).find("a").text();
            let key = $(this).attr("data-key");
            let url = $(this).find("input[data-banner='url']").val();
            let divPanel = $('<div>').addClass("panel").html(plantillaOpciones);
            divPanel.find("img").attr("src", "plantillas/imagenes/" + img);
            divPanel.find("input[data-banner='name']").attr("placeholder", "Nombre").attr("name", key).val(text);
            divPanel.find("select[data-banner='url']").val(url);
            panelVirtual.find(".opciones").append(divPanel);
        });
    }

</script>