<style>
    .list-banner{
        width: 100%;
    }
    .list-banner .banner{
        width: 25%;
        height: 100%;
        display: inline-block;
        margin-right: -4px;
        padding: 0 10px;
        cursor: pointer;
        margin-bottom: 10px;
    }
    .list-banner .banner:last-child{
        margin-bottom: 0;
    }
    .list-banner .banner img{
        width: 100%;
        border: 3px solid #999;
    }
    .list-banner .banner .select2{
        width: 100%!important;
    }
</style>

<div class="modal-header">
    <div class="close-modal" data-dismiss="modal" aria-label="Close"><i class="fas fa-times"></i></div>
    <h4 class="modal-title">Asociar Banner</h4>
</div>
<form id="validar_formulario">
    <div class="modal-body">
        <div class="list-banner"></div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
    </div>
</form>

<?php //print_r($this->empresas); ?>

<script>

    var listBanner = $(".list-banner");

    $(document).ready(function(){
        let idBannerSelected = "";
        let idBannerUrlSelected = "";
        let i=0;
        $(".banners").each(function(){
            idBannerSelected = $(this).attr("data-idbanner");
            idBannerUrlSelected = $(this).attr("data-idbanner-url"); //INPUT URL
            //console.log(i + " idBannerSelected", idBannerSelected);
            console.log(i + " idBannerUrlSelected", idBannerUrlSelected);
            let idBanner = $(this).attr("data-id");
            let div = $('<div>').addClass("banner").attr("data-id", idBanner);
            let img = $('<img>').attr("src", $(this).find("img.img").attr("src"));
            let select = $('<select>').addClass("select-empresa");
            select.append('<option value="">Seleccionar</option>');
            <?php foreach($this->empresas as $item) : $selected = ''; ?>
            select.append('<option value="<?php echo $item['orden']; ?>"><?php echo $item['nombre']." (".$item['zona'].")"; ?></option>');
            <?php endforeach; ?>
            select.attr('style', 'width: 100% !important');
            let input = $('<input>');
            input.addClass("input-url");
            input.attr({
                'style': 'width: 100% !important',
                'placeholder': 'Ingrese URL externo',
                'value': idBannerUrlSelected
            });
            div.append(img).append(select).append(input);
            select.val(idBannerSelected).trigger('change');
            select.select2();
            listBanner.append(div);
            i++;
        });
    });

    $(".select-empresa").change(function(){
        console.log('change select');
        let content = $(this).parents(".banner");
        let idBannerSelected = content.attr("data-id");
        let idEmpresaSelected = $(this).val();
        let banner = $(".banners[data-id='"+idBannerSelected+"']");
        if(banner.length){
            banner.attr("data-idbanner", idEmpresaSelected);
        }
        guardarBanners(idEmpresaSelected);
    });

    function guardarBanners(idbanner){
        let data = {};
        $(".banner").each(function(){
            let idBannerSelected = $(this).attr("data-id");
            let idEmpresaSelected = $(this).find(".select-empresa").val();
            data[idBannerSelected] = idEmpresaSelected;
        });
        $("input[name='banner_opciones']").val(JSON.stringify(data));
    }

    $(".input-url").keyup(function(){
        console.log('change input');
        let content = $(this).parents(".banner");
        let idBannerSelected = content.attr("data-id");
        let idBannerUrlSelected = $(this).val();
        let banner = $(".banners[data-id='"+idBannerSelected+"']");
        if(banner.length){
            banner.attr("data-idbanner-url", idBannerUrlSelected);
        }
        guardarBannersUrl(idBannerUrlSelected);
    });

    function guardarBannersUrl(idbanner){
        let data = {};
        $(".banner").each(function(){
            let idBannerSelected = $(this).attr("data-id");
            let idBannerUrlSelected = $(this).find(".input-url").val();
            data[idBannerSelected] = idBannerUrlSelected;
        });
        $("input[name='banner_opciones_url']").val(JSON.stringify(data));
    }

</script>