<style>
    .label-info {
        background-color: #5bc0de;
    }
    .label {
        display: inline;
        padding: .2em .6em .3em;
        font-size: 75%;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: .25em;
    }
    .bootstrap-tagsinput{
        width: 100%;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title"><?php echo $this->feria['nombre']; ?>: Páginas Pasos</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" class="formseo" data-accion="/cliente/guardar-pagina-pasos-ferias" data-callback="respuesta(response, 'Pasos guardado correctamente.')" autocomplete="off">
    <input type="hidden" name="idferias" value="<?php echo $this->idferias; ?>">
    <input type="hidden" name="idferiaspasos" value="<?php echo $this->feriasPasos['idferiaspasos'] ; ?>">
    <div class="modal-body">
        <div data-contenido="pasos" data-paso="1">
            <div class="panel-hdr">
                <h2><i class="fas fa-fw fa-lg fa-building"></i>&nbsp;Paso 1 (Home) </h2>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox custom-control-inline mt-1">
                    <input type="checkbox" name="paso_1" value="1" class="check_paso custom-control-input" id="defaultInlinepaso_1" <?php if( (int)$this->feriasPasos['paso_1'] ) { echo "checked='true'"; } ?>>
                    <label class="custom-control-label" for="defaultInlinepaso_1"><span class=""></span> Habilitado</label>
                </div>
            </div>
            <div class="form-group" style="<?php if( $this->feriasPasos['paso_1'] !== "1" ) { echo "display: none"; } ?>">
                <label class="form-label">Página</label>
                <span>
                    <select class="select2 form-control select-menu" name="paso_1_idmenu">
                        <option value="" selected="select">Seleccionar...</option>
                        <?php foreach($this->menus as $item):?>
                        <option value="<?php echo $item['idmenus'];?>" <?php if( $this->feriasPasos['paso_1_idmenu'] == $item['idmenus'] ) { echo "selected='select'"; } ?>><?php echo $item['nombre'];?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
        <div data-contenido="pasos" data-paso="2">
            <div class="panel-hdr">
                <h2><i class="fas fa-fw fa-lg fa-building"></i>&nbsp;Paso 2 (Registro)</h2>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox custom-control-inline mt-1">
                    <input type="checkbox" name="paso_2" value="1" class="check_paso custom-control-input" id="defaultInlinepaso_2" <?php if( (int)$this->feriasPasos['paso_2'] ) { echo "checked='true'"; } ?>>
                    <label class="custom-control-label" for="defaultInlinepaso_2"><span class=""></span> Habilitado</label>
                </div>
            </div>
            <div class="form-group" style="<?php if( $this->feriasPasos['paso_2'] !== "1" ) { echo "display: none"; } ?>">
                <label class="form-label">Página</label>
                <span>
                    <select class="select2 form-control select-menu" name="paso_2_idmenu">
                        <option value="" selected="select">Seleccionar...</option>
                        <?php foreach($this->menus as $item):?>
                        <option value="<?php echo $item['idmenus'];?>" <?php if( $this->feriasPasos['paso_2_idmenu'] == $item['idmenus'] ) { echo "selected='select'"; } ?>><?php echo $item['nombre'];?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
        <div data-contenido="pasos" data-paso="3">
            <div class="panel-hdr">
                <h2><i class="fas fa-fw fa-lg fa-building"></i>&nbsp;Paso 3 (Contenido)</h2>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox custom-control-inline mt-1">
                    <input type="checkbox" name="paso_3" value="1" class="check_paso custom-control-input" id="defaultInlinepaso_3" <?php if( (int)$this->feriasPasos['paso_3'] ) { echo "checked='true'"; } ?>>
                    <label class="custom-control-label" for="defaultInlinepaso_3"><span class=""></span> Habilitado</label>
                </div>
            </div>
            <div class="form-group" style="<?php if( $this->feriasPasos['paso_3'] !== "1" ) { echo "display: none"; } ?>">
                <label class="form-label">Página</label>
                <span>
                    <select class="select2 form-control select-menu" name="paso_3_idmenu">
                        <option value="" selected="select">Seleccionar...</option>
                        <?php foreach($this->menus as $item):?>
                        <option value="<?php echo $item['idmenus'];?>" <?php if( $this->feriasPasos['paso_3_idmenu'] == $item['idmenus'] ) { echo "selected='select'"; } ?>><?php echo $item['nombre'];?></option>
                        <?php endforeach;?>
                    </select>
                </span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-info btn-submit btn-uploader-form" data-id-form="validar_formulario">Guardar Cambios</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            idmenus:{
                required: true
            },
            titulo:{
                required: true
            },
            descripcion:{
                required: true
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

    $(document).on("click", ".check_paso", function(){
        let checkSelected = $(this);
        let nextElement = $(this).parent().parent().next();
        if( checkSelected.is(":checked") ) {
            nextElement.show();
        } else {
            nextElement.hide();
        }
    });

</script>