<style>
    .contenedor-imagen-personalizado {
        background: #eaeaea;
    }
    .cambiar-imagen-personalizado{
        margin-top: 4px;
    }
    .row-botones {
        border-bottom: 1px solid rgba(0, 0, 0, 0.07);
        padding: 10px 0;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Página <?php echo $this->pagina['nombre'] ?>: Personalizar Botones</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/cliente/guardar-personalizar-botones-paginas" data-callback="respuesta(response, 'Botones Personalizado Correctamente.')" autocomplete="off">
    <div class="modal-body">
        <input type="hidden" name="idpaginas" value="<?php echo $this->idpaginas; ?>">
        <input type="hidden" name="idferias" value="<?php echo $this->idferias; ?>">
        <input type="hidden" name="totalBotones" value="<?php echo $this->totalBotones; ?>">
        <?php
            $data = ['botones'=> $this->botones, 'menus'=> $this->menus, 'paginasBotones'=> $this->paginasBotones];
            switch( $this->pagina['hash_url'] ) {
                case 'recepcion':
                case 'hall': echo $this->partial('partial/paginas/plantilla-botones', $data); break;
                case 'hall-conferencias': echo $this->partial('partial/paginas/plantilla-botones-conferencias', $data); break;
                default: echo 'No se encontro una plantilla.'; break;
            }
        ?>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>
    
    $(".select2").select2();

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/boton-no-found.png");
                    return false;
                } 
                img.attr("src", e.target.result);
            };
        }
    }

</script>