<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Personalizar Ferias</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<?php //print_r( $this->color_configuracion ); ?>

<form id="validar_formulario" autocomplete="off">
    <div class="modal-body">
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Color Botón Primero</h2>
        </div>
        <div class="form-group header-color-config" data-config="boton_primero">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Color Botón Segundo</h2>
        </div>
        <div class="form-group header-color-config" data-config="boton_segundo">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Color Encabezado Primero</h2>
        </div>
        <div class="form-group header-color-config" data-config="encabezado_primero">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Color Encabezado Segundo</h2>
        </div>
        <div class="form-group header-color-config" data-config="encabezado_segundo">
            <div class="row mb-10">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">T. Línea Hover</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto_linea_hover" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Buscador Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="buscador_fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Buscador Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="buscador_texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">B. T Línea Hover</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="buscador_texto_linea_hover" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Color Encabezado Tercero</h2>
        </div>
        <div class="form-group header-color-config" data-config="encabezado_tercero">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Pie Página Primero</h2>
        </div>
        <div class="form-group header-color-config" data-config="pie_pagina_primero">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Pie Página Segundo</h2>
        </div>
        <div class="form-group header-color-config" data-config="pie_pagina_segundo">
            <div class="row mb-10">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">T. Línea Hover</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto_linea_hover" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Hover Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Fondo Menú</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo_menu" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">F. M. Resaltado</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo_menu_resaltado" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Flechas Zonas</h2>
        </div>
        <div class="form-group header-color-config" data-config="flechas_zonas">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-palette"></i>&nbsp;Sección Maestría</h2>
        </div>
        <div class="form-group header-color-config" data-config="seccion_maestria">
            <div class="row">
                <div class="col-md-3">
                    <label class="form-label">Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Texto</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="texto" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Hover Fondo</label>
                    <span class="input-group color-personalizar">
                        <input type="text" data-idconfig="hover_fondo" class="form-control">
                        <span class="input-group-append">
                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                        </span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-info">Guardar Cambios</button>
    </div>
</form>

<script>

    $(document).ready(function(){
        loadColorConfig();
    });

    //$('.color-personalizar').colorpicker();

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {},
        messages: {},
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function(form) {
            saveColorConfig();
        }
    });

    function loadColorConfig(){
        let dataConfig = JSON.parse('<?php echo $this->color_configuracion ?>');
        let dataConfigInitial = JSON.parse('<?php echo $this->color_configuracion_inicial ?>');
        for(key in dataConfig){
            let headerConfig = $(".header-color-config[data-config='"+key+"']");
            if(headerConfig.length > 0){
                headerConfig.each(function(){
                    $(this).find(".col-md-3").each(function(){
                        let keyInput = $(this).find("input[type='text']").attr("data-idconfig");
                        let keyInputInitial = ( dataConfigInitial[key][keyInput] !== undefined ) ? dataConfigInitial[key][keyInput] : '#FFFFFF';
                        if( $(this).find("input[data-idconfig='fondo']").length > 0 ) $(this).find("input[data-idconfig='fondo']").val((dataConfig[key].fondo != '') ? dataConfig[key].fondo : keyInputInitial);
                        if( $(this).find("input[data-idconfig='texto']").length > 0 ) $(this).find("input[data-idconfig='texto']").val((dataConfig[key].texto != '') ? dataConfig[key].texto : keyInputInitial);
                        if( $(this).find("input[data-idconfig='hover_fondo']").length > 0 ) $(this).find("input[data-idconfig='hover_fondo']").val((dataConfig[key].hover_fondo != '') ? dataConfig[key].hover_fondo : keyInputInitial);
                        if( $(this).find("input[data-idconfig='hover_texto']").length > 0 ) $(this).find("input[data-idconfig='hover_texto']").val((dataConfig[key].hover_texto != '') ? dataConfig[key].hover_texto : keyInputInitial);
                        if( $(this).find("input[data-idconfig='texto_linea_hover']").length > 0 ) $(this).find("input[data-idconfig='texto_linea_hover']").val((dataConfig[key].texto_linea_hover != '') ? dataConfig[key].texto_linea_hover : keyInputInitial);
                        if( $(this).find("input[data-idconfig='buscador_fondo']").length > 0 ) $(this).find("input[data-idconfig='buscador_fondo']").val((dataConfig[key].buscador_fondo != '') ? dataConfig[key].buscador_fondo : keyInputInitial);
                        if( $(this).find("input[data-idconfig='buscador_texto']").length > 0 ) $(this).find("input[data-idconfig='buscador_texto']").val((dataConfig[key].buscador_texto != '') ? dataConfig[key].buscador_texto : keyInputInitial);
                        if( $(this).find("input[data-idconfig='buscador_texto_linea_hover']").length > 0 ) $(this).find("input[data-idconfig='buscador_texto_linea_hover']").val((dataConfig[key].buscador_texto_linea_hover != '') ? dataConfig[key].buscador_texto_linea_hover : keyInputInitial);
                        if( $(this).find("input[data-idconfig='fondo_menu_resaltado']").length > 0 ) $(this).find("input[data-idconfig='fondo_menu_resaltado']").val((dataConfig[key].fondo_menu_resaltado != '') ? dataConfig[key].fondo_menu_resaltado : keyInputInitial);
                        if( $(this).find("input[data-idconfig='fondo_menu']").length > 0 ) $(this).find("input[data-idconfig='fondo_menu']").val((dataConfig[key].fondo_menu != '') ? dataConfig[key].fondo_menu : keyInputInitial);
                    });
                });
            }
        }
        $('.color-personalizar').colorpicker({
            horizontal: true
        });
    }

    function saveColorConfig() {
        let dataConfig = getDatacolorConfig();
        $.post("/cliente/guardar-personalizar-ferias",{idferias: '<?php echo $this->idferias; ?>', config: JSON.stringify(dataConfig)},function(response){
            //console.log(response);
            if(response.result === 'success') {
                ocultarModal();
                alerta('Colores personalizados correctamente.', 'success');
            }
        }, 'json');
    }

    function getDatacolorConfig(){
        let dataColor = {};
        $(".header-color-config").each(function(){
            let idconfig = $(this).attr("data-config");
            let config = {};
            $(this).find(".col-md-3").each(function(){
                let key = $(this).find("input[type='text']").attr("data-idconfig");
                let value = $(this).find("input[type='text']").val();
                config[key] = value;
            });
            dataColor[idconfig] = config;
        });
        //console.log(dataColor);
        return dataColor;
    }

</script>