<style>
    .label-info {
        background-color: #5bc0de;
    }
    .label {
        display: inline;
        padding: .2em .6em .3em;
        font-size: 75%;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: .25em;
    }
    .bootstrap-tagsinput{
        width: 100%;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title"><?php echo $this->feria['nombre']; ?>: SEO</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fal fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" class="formseo" data-accion="/cliente/guardar-seo-ferias" data-callback="respuesta(response, 'SEO guardado correctamente.')" autocomplete="off">
    <input type="hidden" name="idferias" value="<?php echo $this->idferias; ?>">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Página</label>
            <span>
                <select class="select2 form-control select-menu" name="idmenus">
                    <option value="" selected="select">Seleccionar...</option>
                    <?php foreach($this->menus as $item):?>
                    <option value="<?php echo $item['idmenus'];?>"><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="contenido-seo" style="display: none">
            <div class="form-group" style="display: none">
                <label class="form-label">Título</label>
                <span>
                    <input type="text" name="titulo" class="form-control">
                </span>
            </div>
            <div class="form-group">
                <label class="form-label">Descripción</label>
                <span>
                    <textarea rows="6" class="form-control" name="descripcion"></textarea>
                </span>
            </div>
            <div class="form-group">
                <label class="form-label">Keywords</label>
                <span>
                    <select class="tagsselect select-keywords" name="keywords[]" multiple data-role="tagsinput"></select>
                </span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-info btn-submit btn-uploader-form" data-id-form="validar_formulario">Guardar Cambios</button>
    </div>
</form>

<script>

    $(".select-menu").change(function(){
        let idmenus = $(this).val();
        if(idmenus === ''){
            FormSeo.contenidoSeo.hide();
        } else {
            FormSeo.contenidoSeo.show();
        }
        $.post("/cliente/obtener-seo", {idmenus: $(this).val(), idferias: '<?php echo $this->idferias; ?>'}, function(data) {
            if(Object.keys(data).length){
                FormSeo.contenidoSeo.show();
                $("input[name='titulo']").val(data.titulo);
                $("textarea[name='descripcion']").text(data.descripcion);
                FormSeo.destroySelectTags();
                if(data.keywords.length){
                    for(let i in data.keywords){
                        let option = $('<option>');
                        option.attr({"value": data.keywords[i]}).text(data.keywords[i]);
                        FormSeo.selectKeywords.append(option);
                    }
                }
                FormSeo.initSelectTags();
            } else {
                FormSeo.clearElements();
                FormSeo.destroySelectTags();
                FormSeo.initSelectTags();
            }
        },'json');
    });

    var FormSeo = {
        contenidoSeo: $(".contenido-seo"),
        form: $(".formseo"),
        selectKeywords: $(".select-keywords"),
        selectMenu: $(".select-menu"),
        clearElements: function(){
            $("input[name='idseo']").val();
            $("input[name='titulo']").val('');
            $("textarea[name='descripcion']").text('');
        },
        initSelectTags: function(){
            this.selectKeywords.tagsinput();
        },
        destroySelectTags: function(){
            this.selectKeywords.html('');
            this.selectKeywords.tagsinput('destroy');
        }
    }

    $(".select2").select2();
    $(".select-keywords").tagsinput();

    $("#validar_formulario").validate({
        rules: {
            idmenus:{
                required: true
            },
            titulo:{
                required: true
            },
            descripcion:{
                required: true
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>