<div class="panel">
    <div class="panel-container show">
        <div class="panel-content">
            <table id="dataTables" class="table table-bordered table-hover table-striped w-100">
                <thead>
                    <tr>
                        <th>Nombres</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</th>
                        <th width="100">Opciones</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<script>

    <?php $this->inlineScript()->captureStart(); ?>

    var tablaOpcionIzquierda = '';
    var tablaOpcionDerecha = '';
    var responsiveHelper_dataTables = undefined;
    var dataTable;
    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };
    dataTable = $('#dataTables').dataTable({
        "ajax": "/cliente/listar-speakers",
        "sDom": "<'row'<'col-xs-11 col-sm-6 tabla-opciones-izquierda'f><'col-sm-6 col-xs-1 tabla-opciones-derecha'>r>" +
                "t" +
                "<'row'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth": false,
        "oLanguage": {
            "sUrl": "js/datagrid/datatables/Spanish.json",
        },
        "aoColumnDefs": [
            {"bSortable": false, "aTargets": [1]}
        ],
        "preDrawCallback": function () {
            if (!responsiveHelper_dataTables) {
                responsiveHelper_dataTables = new ResponsiveDatatablesHelper($('#dataTables'), breakpointDefinition);
            }
        },
        "rowCallback": function (nRow) {
            responsiveHelper_dataTables.createExpandIcon(nRow);
        },
        "drawCallback": function (oSettings) {
            responsiveHelper_dataTables.respond();
            tablaOpcionIzquierda = $(".tabla-opciones-izquierda");
            tablaOpcionDerecha = $(".tabla-opciones-derecha");
        },
        "ordering": false,
        responsive: true
    });

    $(document).ready(function () {
        setTimeout(function(){
            
            tablaOpcionIzquierda.find(".input-group-addon").addClass("input-group-text d-inline-flex width-3 align-items-center justify-content-center border-bottom-right-radius-0 border-top-right-radius-0 border-right-0");
            tablaOpcionIzquierda.find(".input-group-addon").find("i").removeAttr("class").addClass("fas fa-search");
            tablaOpcionIzquierda.find("input[type='search']").attr("placeholder", "Buscar");
            tablaOpcionDerecha.append('<div class="opciones">'+
                '<button type="button" class="btn btn-info pop-up" href="/cliente/agregar-speakers"><i class="fas fa-plus"></i> <span class="hidden-xs">Agregar Speakers</span></button> '+
            '</div>');

        }, 700);
    });

    function listarDatos() {
        dataTable.api().ajax.reload(null, false);
    }

    function respuesta(response, mensaje) {
        ocultarModal();
        if (response.result == 'successConferencia') {
            console.log(response.dataConferencia);
            if(response.dataConferencia.enlace_conferencia != '')socket.emit("transmitirConferencia", {dataConferencia: response.dataConferencia});
        }
        listarDatos();
        alerta(mensaje, 'success');
    }

    <?php $this->inlineScript()->captureEnd(); ?>

</script>