<div class="panel">
    <div class="panel-container show">
        <div class="panel-content">
            <table id="dataTables" class="table table-bordered table-hover table-striped w-100">
                <thead>
                    <tr>
                        <th>Feria</th>
                        <th>Nombre</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</th>
                        <th>Correo</th>
                        <th>Teléfono</th>
                        <th width="90">N° Documento</th>
                        <th width="165">Opciones</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<script>

    <?php $this->inlineScript()->captureStart(); ?>
    var tablaOpcionIzquierda = new Object();
    var tablaOpcionDerecha = new Object();
    var responsiveHelper_dataTables = undefined;
    var dataTable;
    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };
    dataTable = $('#dataTables').dataTable({
        "ajax": {
            "url" : "/cliente/listar-visitantes",
            "type": "POST"
        },
        "sDom": "<'row'<'col-xs-11 col-sm-6 tabla-opciones-izquierda'f><'col-sm-6 col-xs-1 tabla-opciones-derecha'>r>" +
                "t" +
                "<'row'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth": false,
        "oLanguage": {
            "sUrl": "js/datagrid/datatables/Spanish.json",
        },
        "aoColumnDefs": [
            {"bSortable": false, "aTargets": [7]}
        ],
        "preDrawCallback": function () {
            if (!responsiveHelper_dataTables) {
                responsiveHelper_dataTables = new ResponsiveDatatablesHelper($('#dataTables'), breakpointDefinition);
            }
        },
        "rowCallback": function (nRow) {
            responsiveHelper_dataTables.createExpandIcon(nRow);
        },
        "drawCallback": function (oSettings) {
            responsiveHelper_dataTables.respond();
        },
        "ordering": false,
        responsive: true,
        "pageLength": 30,
        "serverSide":true,
        "processing":true,
        "initComplete": function(settings, json) {
            iniciarFiltrosDatatable();
        }
    });

    $(document).ready(function () {
        
    });

    function iniciarFiltrosDatatable() {
        tablaOpcionIzquierda = $(".tabla-opciones-izquierda");
        tablaOpcionDerecha = $(".tabla-opciones-derecha");
        tablaOpcionIzquierda.find(".input-group-addon").addClass("input-group-text d-inline-flex width-3 align-items-center justify-content-center border-bottom-right-radius-0 border-top-right-radius-0 border-right-0");
        tablaOpcionIzquierda.find(".input-group-addon").find("i").removeAttr("class").addClass("fal fa-search");
        tablaOpcionIzquierda.find("input[type='search']").attr("placeholder", "Buscar");
        tablaOpcionDerecha.append('<div class="opciones">'+
            '<button type="button" class="btn btn-info pop-up" href="/cliente/agregar-visitantes"><i class="fas fa-plus"></i> <span class="hidden-xs">Agregar Visitantes</span></button> '+
            '<button type="button" class="btn btn-success pop-up" href="/cliente/importar-visitantes"><i class="fas fa-file-import"></i> <span class="hidden-xs">Importar Visitantes</span></button> '+
        '</div>');
    }

    function listarDatos() {
        dataTable.api().ajax.reload(null, false);
    }

    function respuesta(response, mensaje) {
        ocultarModal();
        listarDatos();
        if (response.result == 'success') {
            alerta(mensaje, 'success');
        } else if ( response.result == 'visitantes_existentes' ) {
            alerta('Se encontraron visitantes registrados.', 'warning');
        } else if ( response.result == 'extension_invalida' ) {
            alerta('El formato del archivo es invalido.', 'warning');
        } else if ( response.result == 'formato_incorrecto' ) {
            alerta('El formato que ha subido es incorrecto. Por favor, descargue el formato adecuado.', 'warning');
        }
    }

    <?php $this->inlineScript()->captureEnd(); ?>

</script>