<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Ofertas</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/oferta/guardar-editar-ofertas?idofertas=<?php echo $this->idofertas; ?>" data-callback="respuesta(response, 'Ofertas actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Empresa</label>
            <span>
                <select class="select2 form-control" name="idempresas">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->empresas as $item):?>
                    <option value="<?php echo $item['idempresas'];?>" <?php if( $this->idempresas == $item['idempresas'] ) echo "selected='select'"; ?>><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Nombre</label>
            <span>
                <input type="text" name="nombre" class="form-control" value="<?php echo $this->nombre; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Descripción</label>
            <span>
                <textarea type="text" name="descripcion" value="<?php echo $this->descripcion; ?>" class="form-control"></textarea>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Pais</label>
            <span>
                <input type="text" name="pais" value="<?php echo $this->pais; ?>" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Fecha</label>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text fs-xl"><i class="fal fa-calendar"></i></span>
                </div>
                <input type="text" name="fecha" class="form-control calendario" value="<?php echo date('d/m/Y', strtotime($this->fecha)); ?>">
            </div>
        </div>
        <div class="form-group">
            <label class="form-label">Estado</label>
            <span>
                <select  name="estado" class="select2 form-control">
                        <option value="1" <?php if($this->estado=="1"){echo "selected";} ?>>Abierto</option>
                        <option value="0" <?php if($this->estado=="0"){echo "selected";} ?>>Cerrado</option>
                </select>
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Imagen</h2>
        </div>
        <div class="form-group">
            <div class="contenedor-imagen-personalizado">
                <img src="<?php echo ( $this->hash_imagen != '' ) ? 'ofertas/imagen/'.$this->hash_imagen.'?t='.time() : 'img/no-imagen.jpg'; ?>" width="300" class="imagen">
                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 590 px de ancho y 700 px de alto</div>
                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                <input type="file" data-width="590" data-height="700" onchange="cambiarImagenDimension(this, event);" class="hidden" name="imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $('.calendario').datepicker({
        language: 'es',
        orientation: "bottom left",
        autoclose: true
    });

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                }
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            idempresas: {
                required: true
            },
            nombre: {
                required: true
            },
            fecha: {
                required: true
            }
        },
        messages: {
            idempresas: {
                required: 'Por favor, seleccionar la empresa'
            },
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            fecha: {
                required: 'Por favor, ingrese la fecha'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>