<?= $this->doctype() ?>

<?= $this->content; ?>

<!-- CSS [INICIO] -->
<link rel="stylesheet" media="screen, print" href="css/fa-solid.css">
<link rel="stylesheet" media="screen, print" href="plantillas/css/bootstrap.css">
<!-- CSS [FIN] -->

<!-- JS [INICIO] -->
<script src="plantillas/js/bootstrap.js"></script>
<script src="plantillas/js/jquery-ui.js"></script>
<script src="js/jquery-validation/jquery.validate.min.js"></script>
<script src="js/jquery-validation/localization/messages_es.js"></script>
<!-- JS [FIN] -->

<div class="modal fade" id="modal-uno" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<div class="modal fade" id="modal-dos" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<script>

    $("body").on("click",".pop-up",function(e){
        e.preventDefault();
        abrirModal($(this).attr("href"),'uno');
    });

    $("body").delegate(".pop-up-2","click",function(e){
        e.preventDefault();
        abrirModal($(this).attr("href"),'dos');
    });

    function abrirModal(src,id){
        $('#modal-'+id).modal({
            backdrop: 'static',
            keyboard: true
        });
        $('#modal-'+id).find('.modal-content').html('<div class="text-center" style="padding:30px;text-align: center;"><i class="fas fa-spinner fa-pulse fa-5x"></i> <br/><br/> <p>Cargando Contenido</p></div>');
        $.post(src,function(data){
            $('#modal-'+id).find('.modal-content').html(data);
        }).fail(function(e){
            var msj = '';
            var icon = 'fas fa-warning fa-5x txt-color-red';
            switch(e.status){
                case 0:
                    msj = 'No se ha podido conectar con el servidor, intente en otro momento.';
                    icon = "fas fa-globe fa-5x txt-color-red";
                break;
                case 404:
                    msj = 'El contenido que usted esta buscando no se ha encontrado en el servidor.';
                break;
                case 401:
                    msj = 'Usted no tiene acceso a esta opción.';
                    icon = "fas fa-ban fa-5x txt-color-red";
                break;
                case 500:
                    msj = 'Se ha encontrado un error en el servidor, contácte con su administrador del sistema.';
                    icon = "fas fa-plug fa-5x txt-color-red";
                break;
                default:
                    msj = 'No se ha podido conectar con el servidor, intente en otro momento.';
                    icon = "fas fa-globe fa-5x txt-color-red";
                break;
            }
            $('#modal-'+id).find('.modal-content').html('<div class="text-center" style="padding:30px;text-align: center;"><i class="'+icon+'"></i> <br/><br/> <p>'+msj+'</p><br/> <div class="btn btn-default" data-dismiss="modal">Cerrar</div></div>'); 	
        });
    }

    function ocultarModal(instance){
        if(!instance)instance = 'uno';
        $('#modal-'+instance).modal('hide');
        $('#modal-'+instance).find('.modal-content').html('');
    }

    toastr.options = {
        "timeOut": 10000
    }

    function alerta(mensaje, clase){
        switch(clase){
            case "success": toastr["success"](mensaje); break;
            case "error": toastr["error"](mensaje); break;
            case "warning": toastr["warning"](mensaje); break;
            default: toastr["warning"](mensaje); break;
        }
    }
</script>