<?= $this->doctype() ?>

<!DOCTYPE html>
<html lang="<?php echo $this->layout()->idiomaSeleccionado; ?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="theme-color" content="#00b3ce" />
        <meta http-equiv="Content-Language" content="<?php echo $this->layout()->idiomaSeleccionado; ?>" />
        <title><?php echo $this->headTitle()->renderTitle(); ?></title>
        <?php echo $this->headMeta(); ?>
        <meta name="author" content="Dragma">
        <base href="<?php echo $this->layout()->base_url; ?>" />
        <link href="<?php echo ( $this->layout()->feria['config_hash_favicon'] != '' ) ? $this->layout()->url_backend."/portal/favicon/".$this->layout()->feria['config_hash_favicon'] : $this->layout()->url_backend."/img/not-favicon.jpg"; ?>" rel="shortcut icon" title="Icono Feria" />
        <meta name="viewport" content="width=480" initial-scale="1" />
        <link rel="alternate" hreflang="es" href="https://dragmastands.com/" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" media="screen, print" href="css/fontawesome.min.css">
        <link href="css/base.css" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="js/jquery.popupoverlay.js"></script>
        <script type="text/javascript" src="js/usuario-eventos.js?t=<?php echo time(); ?>"></script>
        <script type="text/javascript" src="js/drawer.js"></script>
        <script type="text/javascript" src="js/anamorph.min.js"></script>
        <script type="text/javascript" src="js/init.js?t=<?php echo time(); ?>"></script>
        <!-- Open Graph -->
        <meta property="og:locale" content="es_ES">
        <meta property="og:site_name" content="Dragma - Plataforma Virtual" />
        <meta property="og:url" content="<?php echo $this->layout()->urlActual; ?>" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="<?php echo $this->layout()->feria['nombre']; ?>" />
        <meta property="og:description" content="<?php echo $this->layout()->feria['descripcion']; ?>" />
        <meta property="og:image" content="<?php echo $this->layout()->url_backend."/".$this->layout()->openGraph['url_imagen']; ?>" />
        <meta property="og:image:url" content="<?php echo $this->layout()->url_backend."/".$this->layout()->openGraph['url_imagen']; ?>" />
        <meta property="og:image:secure_url" content="<?php echo $this->layout()->url_backend."/".$this->layout()->openGraph['url_imagen']; ?>" />
        <meta property="og:image:width" content="682" />
	    <meta property="og:image:height" content="1024" />
        <meta property="og:image:type" content="gif"/>
        <meta property="og:image:type" content="jpeg"/>
        <meta property="og:image:type" content="JPEG"/>
        <meta property="og:image:type" content="png"/>
        <meta property="og:image:type" content="jpg"/>
        <meta property="og:updated_time" content="<?php echo time(); ?>"/>
        <meta property="og:image:alt" content="<?php echo $this->layout()->feria['descripcion']; ?>"/>
        <meta property="article:published_time" content="<?php echo time(); ?>"/>
        <meta property="article:modified_time" content="<?php echo time(); ?>"/>
        <meta property="fb:app_id" content="<?php echo $this->layout()->configuracion['aplicacion_red_social']['facebook']['app_id']; ?>" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:image" content="<?php echo $this->layout()->url_backend."/".$this->layout()->openGraph['url_imagen']; ?>" />
        <meta name="twitter:description" content="<?php echo $this->layout()->feria['descripcion']; ?>" />
        <meta name="twitter:title" content="<?php echo $this->layout()->feria['nombre']; ?>" />
        <meta name="twitter:site" content="Dragma - Plataforma Virtual" />
        <meta name="twitter:creator" content="Dragma" />
    </head>

    <?php echo $this->partial('partial/css/personalizado', []); ?>
    <?php echo $this->partial('partial/css/select-idioma', []); ?>

    <body>

        <div class="container-language">
            <select class="select-idioma" onchange="Panel.cambiarIdioma(this)" class="grayout">
                <?php if($this->layout()->listaIdiomas): foreach($this->layout()->listaIdiomas as $key => $idioma): ?>
                <option value="<?php echo $key; ?>" <?php if( $key === $this->layout()->idiomaSeleccionado ) echo 'selected="select"'; ?>><?php echo ( $this->layout()->language ) ? $this->layout()->language->translate($idioma)['text']: ''; ?></option>
                <?php endforeach; endif; ?>
            </select>
        </div>

        <div class="header-index">
            <a href="/" class="logos">
                <img src="<?php echo $this->layout()->url_backend; ?>/ferias/logo/<?php echo $this->layout()->feria['hash_logo']; ?>" width="60%" alt="">
            </a>
            <div class="eye" style="visibility: hidden;">
                <button class="hide-counter"><i class="fas fa-eye" aria-hidden="true"></i></button>
                <div class="contador">
                    <div id="myDIVI">
                        <div class="as">
                            <a href="#">
                                <img src="imagenes/list-1.svg" alt="">
                                <strong>Total de Participantes <span>1000</span></strong>
                            </a>
                        </div>
                        <div class="as2">
                            <a href="#">
                                <img src="imagenes/list-2.svg" alt="">
                                <strong>Participantes AQUÍ <span>1000</span></strong>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="logos-2">
                <img src="imagenes/logo-ccl-01.svg" width="38%" style="display:none;" alt="">
                <img src="<?php echo $this->layout()->url_backend; ?>/clientes/logo/<?php echo $this->layout()->cliente['hash_logo']; ?>" width="26%" alt="">
            </div>
            <div class="logos-3">
                <?php if($this->layout()->idiomaSeleccionado): ?>
                <?php $urlPath = ( $this->layout()->menuSecuencia['home']['menu_posicion'] === 'C') ? 'panel/' : ''; ?>
                <a href="<?php echo $this->layout()->idiomaSeleccionado."/".$urlPath.$this->layout()->menuSecuencia['home']['menu_url']; ?>">
                    <i class="fas fa-user"></i>&nbsp;<?php echo $this->layout()->language->translate('INGRESAR AL EVENTO')['text']; ?>
                </a>
                <?php endif; ?>
            </div>
            <a href="#" data-drawer-trigger aria-controls="drawer-name" aria-expanded="false" class="button-menu">
                <img src="imagenes/menu-01.svg" width="68%" alt="">
            </a>
        </div>

        <a href="#" class="claim-book"><img src="imagenes/reclamaciones.svg" width="40%" alt=""> </a>

        <?php echo $this->partial('partial/menus/encabezado-movil', []); ?>

        <?= $this->content; ?>

        <div class="navbar">
            <div class="boton" style="animation-delay: 1.3s; display: none;">
                <img src="imagenes/new-icons-01.svg" width="32%" alt="">
                <a href="recepcion.html"> RECEPCIÓN</a>
            </div>

            <div class="boton" style="animation-delay: 1.5s; display: none;">
                <img src="imagenes/new-icons-03.svg" width="32%" alt="">
                <a href="hall.html">EXPOSITORES</a>
            </div>

            <div class="boton" style="animation-delay: 1.7s; display: none;">
                <img src="imagenes/new-icons-02.svg" width="32%" alt="">
                <a href="conferencias.html">CONFERENCIAS</a>
            </div>
        </div>

        <script>
            const idiomaSeleccionado = "<?php echo $this->layout()->idiomaSeleccionado; ?>";
            UsuariosEventos.idioma = idiomaSeleccionado;
            Panel.idioma = idiomaSeleccionado;
            Panel.init();
            $(document).ready(function () {
                $("#ingresar").popup({
                    transition: "all 0.3s",
                    closebutton: true,
                });
            });
            $(window).load(function () {
                $(".se-pre-con").fadeOut("slow");
            });
        </script>

        <?php echo $this->partial('partial/scripts/index', []); ?>

    </body>

</html>