<!DOCTYPE html>
<html lang="es" class="root-text-sm">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex">
        <title>Login | Grupo Dragma</title>
        <base href="<?php echo $this->layout()->base_url;?>" />
        <meta name="description" content="Login">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, minimal-ui">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="msapplication-tap-highlight" content="no">
        <link rel="stylesheet" media="screen, print" href="css/vendors.bundle.css">
        <link rel="stylesheet" media="screen, print" href="css/app.bundle.css">
        <link rel="apple-touch-icon" sizes="180x180" href="img/favicon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="img/favicon/favicon-32x32.png">
        <link rel="mask-icon" href="img/favicon/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="stylesheet" media="screen, print" href="css/fa-solid.css">
        <link rel="stylesheet" media="screen, print" href="css/fa-brands.css">
        <link rel="stylesheet" href="css/base.css">
        <link rel="stylesheet" href="css/base-media-screen.css">
    </head>
    <body>

        <script src="js/vendors.bundle.js"></script>
        <script src="js/app.bundle.js"></script>
        <script src="js/jquery-validation/jquery.validate.min.js"></script>
        <script src="js/jquery-validation/localization/messages_es.js"></script>

        <div class="page-wrapper">
            <div class="page-inner bg-brand-gradient">
                <div class="page-content-wrapper bg-transparent m-0">
                    <div class="height-10 w-100 shadow-lg px-4 bg-brand-gradient">
                        <div class="d-flex align-items-center container p-0">
                            <div class="page-logo width-mobile-auto m-0 align-items-center justify-content-center p-0 bg-transparent bg-img-none shadow-0 height-9">
                                <a href="javascript:void(0)" class="page-logo-link press-scale-down d-flex align-items-center">
                                    <img src="img/logo.svg" aria-roledescription="logo">
                                    <span class="page-logo-text mr-1">Grupo Dragma</span>
                                </a>
                            </div>
                            <a href="javascript:void(0)" class="btn-link text-white ml-auto">&nbsp;</a>
                        </div>
                    </div>
                    <div class="flex-1 login-contenedor" style="background: url(img/svg/pattern-1.svg) no-repeat center bottom fixed; background-size: cover;">
                        <div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0 margin-bottom-6rem margin-top-6rem">
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-5 col-xl-4 ml-auto col-center">
                                    <h1 class="text-white fw-300 mb-3 d-sm-block d-md-none">Iniciar Sesión</h1>
                                    <div class="card p-4 rounded-plus bg-faded">
                                        <?= $this->content; ?>
                                    </div>
                                </div>
                                <div class="col col-md-6 col-lg-7 hidden-sm-down">
                                    <h2 class="fs-xxl fw-500 mt-4 text-white">
                                        PODEROSA PLATAFORMA PARA PERSONALIZAR TUS FERIAS Y EVENTOS
                                        <small class="h3 fw-300 mt-3 mb-5 text-white opacity-60">
                                            Presenting you with the next level of innovative UX design and engineering. The most modular toolkit available with over 600+ layout permutations. Experience the simplicity of SmartAdmin, everywhere you go!
                                        </small>
                                    </h2>
                                    <a href="#" class="fs-lg fw-500 text-white opacity-70">Learn more &gt;&gt;</a>
                                    <div class="d-sm-flex flex-column align-items-center justify-content-center d-md-block">
                                        <div class="px-0 py-1 mt-5 text-white fs-nano opacity-50">Encuéntrenos en las redes sociales</div>
                                        <div class="d-flex flex-row opacity-70">
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-facebook-square"></i>
                                            </a>
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-twitter-square"></i>
                                            </a>
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-google-plus-square"></i>
                                            </a>
                                            <a href="#" class="mr-2 fs-xxl text-white">
                                                <i class="fab fa-linkedin"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="position-absolute pos-bottom pos-left pos-right p-3 text-center text-white"><?php echo date('Y'); ?> © Derechos Reservados Grupo Dragma</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            
        <script>

            $(document).ready(function(){
                $("[name='usuario']").focus();
            });

            $(document).keyup(function (e) {
                if (e.keyCode == 13)$(".btn-login").click();
            });

            var btnLogin = $(".btn-login");
            var mensajeLogin = $(".mensaje-login");

            btnLogin.click(function (e) {
                e.preventDefault();
                var idForm = $(this).attr("data-id-form");
                var form = $('#' + idForm);
                var url = form.attr('data-accion');
                var callback = form.attr('data-callback');
                if (form.valid()) {
                    $("div[class*='alert-']").removeClass (function (index, css) {
                        return (css.match (/(^|\s)alert-\S+/g) || []).join(' ');
                    });
                    mensajeLogin.hide();
                    btnLogin.attr("disabled", "");
                    btnLogin.find("span").text('Validando datos...');
                    btnLogin.find("i").removeClass('hidden');
                    var data = form.serialize();
                    procesarFormulario(url, data, callback);
                }
            });

            function procesarFormulario(url, data, callback) {
                $.post(url, data, function (response) {
                    if (typeof callback === 'function')callback(response);
                    else if (callback.length > 2) eval(callback);
                }).fail(function (response) {
                    resultado({"result":"error_network"});
                });
            }

            function resultado(data) {

                var claseMensaje = '';
                var mensaje = '';

                if (data.result == "success") {
                    document.location = '/panel';
                    return;
                } else if (data.result == "error") {
                    claseMensaje = 'danger';
                    mensaje = 'Ocurrio un error interno en el servidor. Intente nuevamente.';
                } else if (data.result == "noactivate") {
                    claseMensaje = 'warning';
                    mensaje = 'Su usuario no se encuentro activo. Contáctar con el área de sistemas.';
                } else if (data.result == "excess_error") {
                    claseMensaje = 'danger';
                    mensaje = 'Ocurrio un error interno en el Servidor. Intente Nuevamente.';
                } else if (data.result == "noaccess") {
                    claseMensaje = 'warning';
                    mensaje = 'Su usuario no tiene acceso al sistema. Contáctar con el área de sistemas.';
                } else if (data.result == "error_network") {
                    claseMensaje = 'warning';
                    mensaje = 'Ocurrio un error interno en el Servidor. Intente Nuevamente.';
                } else if (data.result == "credential_invalid") {
                    claseMensaje = 'warning';
                    mensaje = 'El usuario y contraseña ingresado, no se encuentra registrado en el sistema. Intente Nuevamente.';
                }

                mensajeLogin.addClass("alert-"+claseMensaje).text(mensaje).show();

                btnLogin.removeAttr("disabled");
                btnLogin.find("span").text('Iniciar Sesión');
                btnLogin.find("i").addClass('hidden');

            }

        </script>

    </body>
</html>
