<section class="drawer" id="drawer-name" data-drawer-target>
    <div class="drawer__overlay" data-drawer-close tabindex="-1"></div>
    <div class="drawer__wrapper">
        <button class="drawer__close" data-drawer-close aria-label="Close Drawer"></button>
        <div class="drawer__content">
            <ul class="menu-responsive">
                <?php if(!empty($this->layout()->menus['encabezado'])) : foreach( $this->layout()->menus['encabezado'] as $item) : ?>
                <a href="<?php echo $this->layout()->idiomaSeleccionado; ?>/panel/<?php echo $item['hash_url']; ?>" class="<?php echo ( $this->layout()->menus['hash_url_activo'] == $item['hash_url'] ) ? 'resaltar' : ''; ?>"><?php echo ( $this->layout()->language ) ? $this->layout()->language->translate(mb_strtoupper($item['nombre']))['text'] : ''; ?></a>
                <?php endforeach; endif; ?>
            </ul>
        </div>
    </div>
</section>