<style>
    .contenedor-tabs .tab-content{
        margin-top: 8px;
    }
    .lista-submodulos .contenido input[data-name="titulo"] {
        font-weight: 500;
    }
    .row-img {
        position: relative;
        padding: 4px 8px 8px;
        background-color: #c5c5c526;
        border-radius: 4px;
        margin-bottom: 6px;
    }
    .row-img:last-child{
        margin-bottom: 0px;
    }
    .row-img .bloque:first-child{
        margin-bottom: 4px;
    }
    .row-img i.remove{
        position: absolute;
        right: 8px;
        top: 3px;
        font-size: 16px;
        color: #a0a0a0;
        cursor: pointer;
    }
    .row-img .bg_imagen{
        width: 100%;
        height: 50px;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        border-radius: 4px;
        background-color: #ececec;
        position: relative;
        cursor: pointer;
    }
    .row-img .bg_imagen .icon{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        color: #ababab;
    }
    .row-img .bg_imagen .icon i{
        font-size: 26px;
        line-height: 1;
    }
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Productos</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/producto/guardar-editar-productos?idproductos=<?php echo $this->idproductos; ?>" data-callback="respuesta(response, 'Productos actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <!-- TABS [INICIO] -->
        <div class="contenedor-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tab_default-1" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Detalle</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-2" role="tab"><i class="fas fa-fw fa-lg fa-info"></i> Información</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-3" role="tab"><i class="fas fa-fw fa-lg fa-images"></i> Imagenes</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#tab_default-4" role="tab"><i class="fas fa-fw fa-lg fa-images"></i> Lista de Productos</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab_default-1" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Empresa</label>
                        <span>
                            <select class="select2 form-control" name="idempresas">
                                <option value="" selected="select" disabled="">Seleccionar...</option>
                                <?php foreach($this->empresas as $item):?>
                                <option value="<?php echo $item['idempresas'];?>" <?php if( $this->idempresas == $item['idempresas'] ) echo "selected='select'"; ?>><?php echo $item['nombre'];?></option>
                                <?php endforeach;?>
                            </select>
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Nombre</label>
                        <span>
                            <input type="text" name="nombre" class="form-control" value="<?php echo $this->nombre; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Descripción</label>
                        <span>
                            <input type="text" name="descripcion" class="form-control" value="<?php echo $this->descripcion; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Dirección</label>
                        <span>
                            <input type="text" name="direccion" class="form-control" value="<?php echo $this->direccion; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Tipo Enlace</label>
                        <span>
                            <select class="select2 form-control select-tipoenlace" name="tipo_enlace">
                                <option value="" selected="select">Seleccionar...</option>
                                <option value="URL" <?php if( $this->tipo_enlace == 'URL' ) echo "selected='select'"; ?>>URL</option>
                                <option value="PDF" <?php if( $this->tipo_enlace == 'PDF' ) echo "selected='select'"; ?>>PDF</option>
                            </select>
                        </span>
                    </div>
                    <span data-contenedor="enlace" style="<?php if( $this->tipo_enlace == 'PDF' ) echo "display: none;" ?>">
                        <div class="form-group">
                            <label class="form-label">Enlace</label>
                            <span>
                                <input type="text" name="enlace" class="form-control" value="<?php echo $this->enlace; ?>">
                            </span>
                        </div>
                    </span>
                    <span data-contenedor="pdf" style="<?php if( $this->tipo_enlace == 'URL' ) echo "display: none;" ?>">
                        <div class="form-group">
                            <label class="form-label">PDF</label>
                            <div class="contenedor-archivo">
                                <button type="button" class="btn btn-default btn-archivo"><?php echo ( $this->hash_pdf != '' ) ? 'Cambiar archivo' : 'Seleccionar archivo'; ?></button>
                                <button type="button" class="btn btn-danger btn-eliminar" style="display: none;" onclick="File.delete(this)"><i class="fas fa-times"></i></button>
                                <a href="<?php echo ( $this->hash_pdf != '' ) ? 'productos/documentos/'.$this->hash_pdf : 'javascript:void(0)'; ?>" download class="btn btn-primary btn-descargar" style="<?php echo ( $this->hash_pdf != '' ) ? '' : 'display: none;'; ?>"><i class="fas fa-download"></i> Descargar</a>
                                <input type="file" name="archivo_pdf" class="form-control" size-valid="5000000" valid-file="application/pdf" onchange="File.upload(this, event);" accept="application/pdf" style="display: none;">
                                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">El peso máximo del archivo es de 5 MB</div>
                            </div>
                        </div>
                    </span>
                    <div class="form-group">
                        <label class="form-label">Enlace Whatsapp</label>
                        <span>
                            <input type="text" name="enlace_wsp" class="form-control" value="<?php echo $this->enlace_wsp; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Mapa</label>
                        <span>
                            <input type="text" name="enlace_mapa" class="form-control" value="<?php echo $this->enlace_mapa; ?>">
                        </span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Enlace Recorrido Virtual</label>
                        <span>
                            <input type="text" name="enlace_recorrido_virtual" class="form-control" value="<?php echo $this->enlace_recorrido_virtual; ?>">
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-dollar-sign"></i>&nbsp;Precio</h2>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <label class="form-label">Moneda</label>
                                <span>
                                    <select class="select2 form-control select-moneda" name="moneda">
                                        <option value="" selected="select">Seleccionar...</option>
                                        <option value="S" <?php if( $this->moneda == 'S' ) echo "selected='select'"; ?>>SOLES</option>
                                        <option value="D" <?php if( $this->moneda == 'D' ) echo "selected='select'"; ?>>DOLARES</option>
                                    </select>
                                </span>
                            </div>
                            <div class="col-md-4">
                                <label class="form-label">Precio Desde</label>
                                <span>
                                    <input type="number" name="precio_desde" class="form-control" value="<?php echo $this->precio_desde; ?>">
                                </span>
                            </div>
                            <div class="col-md-4 <?php if( $this->moneda === 'S' ) echo 'disabled'; ?>">
                                <label class="form-label">TC Referencial</label>
                                <span>
                                    <input type="number" name="tc_referencial" class="form-control" value="<?php echo $this->tc_referencial; ?>">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-2" role="tabpanel">
                    <div class="contenedor-dinamico lista-submodulos">
                        <input type="hidden" name="informacion">
                        <div class="encabezado">
                            <div class="row">
                                <div class="col-md-5">
                                    <label class="form-label">Título</label>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label">Descripción</label>
                                </div>
                                <div class="col-md-1">
                                </div>
                            </div>
                        </div>
                        <div class="plantilla" style="display: none;">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <span>
                                            <input type="text" class="form-control" data-name="titulo">
                                        </span>
                                    </div>
                                    <div class="col-md-6">
                                        <span>
                                            <input type="text" class="form-control" data-name="descripcion">
                                        </span>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="button" class="btn btn-danger btn-plantilla" onclick="Fila.eliminar(this)"><i class="fas fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="contenido">
                            <?php $informacion = json_decode($this->informacion, true); ?>
                            <?php if( $informacion ) : foreach($informacion as $item): ?>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-5">
                                        <span>
                                            <input type="text" class="form-control" data-name="titulo" value="<?php echo $item['titulo'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-6">
                                        <span>
                                            <input type="text" class="form-control" data-name="descripcion" value="<?php echo $item['descripcion'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="button" class="btn btn-danger btn-plantilla" onclick="Fila.eliminar(this)"><i class="fas fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                            <?php endforeach; endif; ?>
                        </div>
                        <div class="opcion">
                            <button type="button" class="btn btn-success btn-block" onclick="Fila.agregar(this)"><i class="fas fa-plus"></i> Agregar Información</button>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-3" role="tabpanel">
                    <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 980 px de ancho y 460 px de alto</div>
                    <div class="contenido-imagenes">
                        <div data-template='imagenes' style="display: none;">
                            <div class="row-img">
                                <input type="hidden" name="idproductosimagenes_active[]" value="off">
                                <input type="hidden" name="idproductosimagenes[]" value="">
                                <div class="bloque">
                                    <div><strong>Título</strong></div>
                                    <div><input type="text" class="form-control" data-name="titulo" name="titulo[]"></div>
                                </div>
                                <div class="bloque">
                                    <div data-name="imagenes" class="bg_imagen" onclick="Imagenes.seleccionar(this)" data-width="980" data-height="460">
                                        <div class="icon" >
                                            <i class="fas fa-images"></i>
                                            <div>Seleccionar archivo</div>
                                        </div>
                                    </div>
                                    <input type="file" name="imagenes[]" accept="image/*" style="display: none;" onchange="Imagenes.subir(this, event)">
                                </div>
                                <i class="fas fa-times remove" onclick="Imagenes.eliminar(this)"></i>
                            </div>
                        </div>
                        <div data-result="imagenes">
                            <?php //print_r($this->imagenes); ?>
                            <?php foreach($this->imagenes as $item) : ?>
                            <div class="row-img">
                                <input type="hidden" name="idproductosimagenes_active[]" value="on">
                                <input type="hidden" name="idproductosimagenes[]" value="<?php echo $item['idproductosimagenes']; ?>">
                                <div class="bloque">
                                    <div><strong>Título</strong></div>
                                    <div><input type="text" class="form-control" data-name="titulo" name="titulo[]" value="<?php echo $item['titulo']; ?>"></div>
                                </div>
                                <div class="bloque">
                                    <div data-name="imagenes" class="bg_imagen" onclick="Imagenes.seleccionar(this)" data-width="980" data-height="460" style="<?php echo ( $item['hash_imagen'] != '' ) ? 'background-image: url(productos/slider/'.$item['hash_imagen'].')' : '';  ?>">
                                        <div class="icon" style="<?php echo ( $item['hash_imagen'] != '' ) ? 'display: none' : '';  ?>">
                                            <i class="fas fa-images"></i>
                                            <div>Seleccionar archivo</div>
                                        </div>
                                    </div>
                                    <input type="file" name="imagenes[]" accept="image/*" style="display: none;" onchange="Imagenes.subir(this, event)">
                                </div>
                                <i class="fas fa-times remove" onclick="Imagenes.eliminar(this)"></i>
                            </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="opcion">
                            <button type="button" class="btn btn-success btn-block" onclick="Imagenes.agregar(this)"><i class="fas fa-plus"></i> Agregar Imagen</button>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab_default-4" role="tabpanel">
                    <div class="form-group">
                        <label class="form-label">Nombre</label>
                        <span>
                            <input type="text" name="institucion_nombre" class="form-control" value="<?php echo $this->institucion_nombre; ?>">
                        </span>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Imagen</h2>
                    </div>
                    <div class="form-group">   
                        <div class="contenedor-imagen-personalizado">
                            <img src="<?php echo ( $this->hash_institucion_imagen != '' ) ? 'productos/institucion/imagen/'.$this->hash_institucion_imagen.'?t='.time() : 'img/no-imagen.jpg'; ?>" width="300" class="imagen" alt="">
                            <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 590 px de ancho y 700 px de alto</div>
                            <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                            <input type="file" data-width="590" data-height="700" onchange="cambiarImagenDimension(this, event);" class="hidden" name="hash_institucion_imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                            <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
                        </div>
                    </div>
                    <div class="panel-hdr">
                        <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Maestrías</h2>
                    </div>
                    <div class="contenedor-dinamico lista-maestrias">
                        <input type="hidden" name="maestrias">
                        <div class="encabezado">
                            <div class="row">
                                <div class="col-md-3">
                                    <label class="form-label">Título</label>
                                </div>
                                <div class="col-md-2">
                                    <label class="form-label"><i class="fas fa-link"></i> Web</label>
                                </div>
                                <div class="col-md-2">
                                    <label class="form-label"><i class="fas fa-link"></i> Doc</label>
                                </div>
                                <div class="col-md-2">
                                    <label class="form-label"><i class="fas fa-link"></i> Youtube</label>
                                </div>
                                <div class="col-md-2">
                                    <label class="form-label"><i class="fas fa-link"></i> Whatsapp</label>
                                </div>
                                <div class="col-md-1">
                                </div>
                            </div>
                        </div>
                        <div class="plantilla" style="display: none;">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <span>
                                            <input type="text" class="form-control" data-name="titulo">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_web">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_doc">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_youtube">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_whatsapp">
                                        </span>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="button" class="btn btn-danger btn-plantilla" onclick="Fila.eliminar(this)"><i class="fas fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="contenido">
                            <?php $maestrias = json_decode($this->maestrias, true); ?>
                            <?php if( $maestrias ) : foreach($maestrias as $item): ?>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-3">
                                        <span>
                                            <input type="text" class="form-control" data-name="titulo" value="<?php echo $item['titulo'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_web" value="<?php echo $item['link_web'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_doc" value="<?php echo $item['link_doc'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_youtube" value="<?php echo $item['link_youtube'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-2">
                                        <span>
                                            <input type="text" class="form-control" data-name="link_whatsapp" value="<?php echo $item['link_whatsapp'] ?>">
                                        </span>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="button" class="btn btn-danger btn-plantilla" onclick="Fila.eliminar(this)"><i class="fas fa-times"></i></button>
                                    </div>
                                </div>
                            </div>
                            <?php endforeach; endif; ?>
                        </div>
                        <div class="opcion">
                            <button type="button" data-action="maestrias" class="btn btn-success btn-block" onclick="Fila.agregar(this)"><i class="fas fa-plus"></i> Agregar Productos</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- TABS [FIN] -->
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $(document).ready(function(){
        $("input[name='informacion']").val('<?php echo ( $this->informacion ) ? $this->informacion : ''; ?>');
        $("input[name='maestrias']").val('<?php echo ( $this->maestrias ) ? $this->maestrias : ''; ?>');
    });
    
    var Imagenes = {
        dataTemplateImages: $("div[data-template='imagenes']"),
        dataResultImages: $("div[data-result='imagenes']"),
        agregar: function(){
            let divRowimagen = $('<div>').html(this.dataTemplateImages.html());
            //divRowimagen.find("input[type='file']").attr("name")
            this.dataResultImages.append(divRowimagen.html());
        },
        eliminar: function(obj){
            if(confirm("¿Estas seguro de eliminar la imagen?")){
                let activeProducto = $(obj).parent().find("input[name='idproductosimagenes_active[]']");
                if(activeProducto.val().trim() !== 'on'){
                    $(obj).parent().remove();
                } else {
                    activeProducto.val("on_delete");
                    $(obj).parent().hide();
                }
            }
        },
        seleccionar: function(obj){
            $(obj).parent().parent().find("input[type='file']").click();
        },
        subir: function(obj, event){
            console.log(event);
            var contenedor = $(obj).parent();
            var reader = new FileReader();
            var img = contenedor.find(".bg_imagen");
            var icon = img.find(".icon");
            var img_width = parseInt(img.attr("data-width"));
            var img_height = parseInt(img.attr("data-height"));
            reader.readAsDataURL(event.target.files[0]);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    var width = this.width;
                    var height = this.height;
                    if (width != img_width || height != img_height) {
                        alert('La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.');
                        icon.show();
                        $(obj).val('');
                        img.removeAttr("style");
                        return false;
                    }
                    icon.hide();
                    img.css({"background-image": "url('"+e.target.result+"')"});
                };
            }
        }
    }

    var iconoSeleccionar = '';

    function abrirModalIcono(id){
        iconoSeleccionar = id;
        abrirModal('sistema/seleccionar-icono?id='+id, 'icono');
    }

    $(document).on("click", ".agregar-icono", function(){
        guardarSubmodulos();
    });

    $(document).on("keyup", ".contenedor-dinamico .form-group", function(){
        guardarSubmodulos();
        guardarMaestrias();
    });

    var Fila = {
        agregar: function(obj){
            let idInputIcono = $.now();
            let contenedor = $(obj).parents(".contenedor-dinamico");
            let plantilla = contenedor.find(".plantilla");
            let plantillaContenido = $("<div>").html(plantilla.html());
            let contenido = contenedor.find(".contenido");
            plantillaContenido.find(".contenedor-icono").attr({
                "data-idicono": idInputIcono,
                "onclick": "abrirModalIcono('"+idInputIcono+"')"
            });
            contenido.append(plantillaContenido.html());
        },
        eliminar: function(obj){
            if(confirm("¿Estas seguro de eliminar la información?")){
                $(obj).parents(".form-group").remove();
                guardarSubmodulos();
                guardarMaestrias();
            }
        }
    }

    function guardarSubmodulos(){
        let data = [];
        $(".lista-submodulos .contenido .form-group").each(function(){
            let titulo = $(this).find("input[data-name='titulo']").val().trim();
            let descripcion = $(this).find("input[data-name='descripcion']").val().trim();
            if(titulo != ''){
                data.push({
                    titulo: titulo,
                    descripcion: descripcion
                });
                data = data.filter(data => data.titulo != '');
            }
        });
        console.log(data);
        $("input[name='informacion']").val(JSON.stringify(data));
    }

    function guardarMaestrias(){
        let data = [];
        $(".lista-maestrias .contenido .form-group").each(function(){
            let titulo = $(this).find("input[data-name='titulo']").val().trim();
            let link_web = $(this).find("input[data-name='link_web']").val().trim();
            let link_doc = $(this).find("input[data-name='link_doc']").val().trim();
            let link_youtube = $(this).find("input[data-name='link_youtube']").val().trim();
            let link_whatsapp = $(this).find("input[data-name='link_whatsapp']").val().trim();
            if(titulo != ''){
                data.push({
                    titulo,
                    link_web,
                    link_doc,
                    link_youtube,
                    link_whatsapp,
                });
                data = data.filter(data => data.titulo != '');
            }
        });
        console.log(data);
        $("input[name='maestrias']").val(JSON.stringify(data));
    }

    $(".btn-archivo").click(function(){
        $(this).parent().find("input[type='file']").click();
    });

    var File = {
        upload: function(obj, event){
            let contenedor = $(obj).parent();
            let btnArchivo = contenedor.find(".btn-archivo");
            let btnEliminar = contenedor.find(".btn-eliminar");
            let btnDescargar = contenedor.find(".btn-descargar");
            let inputFile = contenedor.find("input[type='file']");
            let validFiles = inputFile.attr("valid-file").split(",");
            if(event.target.files.length){
                if( validFiles.indexOf(event.target.files[0].type) == -1 ){
                    this.message('invalid-format', 'warning');
                    this.restore(obj);
                    return;
                }
                if( event.target.files[0].size > 5000000 ) {
                    this.message('invalid-size', 'warning');
                    this.restore(obj);
                    return;
                }
                btnArchivo.text("Cambiar archivo");
                btnEliminar.show();
            } else {
                this.restore(obj);
            }
        },
        delete: function(obj) {
            this.restore(obj);
        },
        restore: function(obj) {
            let contenedor = $(obj).parent();
            let btnArchivo = contenedor.find(".btn-archivo");
            let btnEliminar = contenedor.find(".btn-eliminar");
            let inputFile = contenedor.find("input[type='file']");
            btnArchivo.text("Seleccionar archivo");
            btnEliminar.hide();
            inputFile.val('');
        },
        message: function(type, typeMessage){
            switch(type){
                case 'invalid-format': alerta("El tipo de formato no es valido. Por favor, vuelva a intentarlo.", typeMessage); break;
                case 'invalid-size': alerta("El peso máximo no es valido. Por favor, vuelva a intentarlo.", typeMessage); break;
            }
        }
    }

    var selectTipoEnlace = $(".select-tipoenlace");
    var contenedorEnlace = $('span[data-contenedor="enlace"]');
    var contenedorPdf = $('span[data-contenedor="pdf"]');

    selectTipoEnlace.change(function(){
        let tipo = $(this).val();
        if( tipo == 'URL' ){
            contenedorEnlace.show();
            contenedorPdf.hide();
            File.restore($(".contenedor-archivo"));
        }else{
            contenedorEnlace.hide();
            contenedorPdf.show();
        }
    });

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                }
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        ignore: [],
        rules: {
            idempresas: {
                required: true
            },
            nombre: {
                required: true
            },
            tipo_enlace: {
                required: true
            }
        },
        messages: {
            idempresas: {
                required: 'Por favor, seleccionar la empresa'
            },
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            tipo_enlace: {
                required: 'Por favor, seleccionar el tipo de enlace'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

    var inputTipoCambioReferencial = $("input[name='tc_referencial']");

    $(".select-moneda").change(function(){
        if( $(this).val() === 'S' )inputTipoCambioReferencial.val('0.00').parent().parent().addClass("disabled");
        else inputTipoCambioReferencial.parent().parent().removeClass("disabled")
    });

</script>