<style>
    .list-submenus{
        padding: 0;
        list-style: none;
    }
    .m-b-6 {
        margin-bottom: 6px;
    }
</style>

<div class="row">
    <?php if( !empty($this->dashboard) ) : foreach( $this->dashboard as $data ) : ?>
    <div class="col-md-4">
        <div class="alert alert-primary alert-dismissible m-b-6">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">
                    <em class="fal fa-times"></em>
                </span>
            </button>
            <div class="d-flex flex-start w-100">
                <div class="mr-2 hidden-sm-down">
                    <span class="icon-stack icon-stack-lg">
                        <em class="base-14 icon-stack-3x color-primary-400"></em>
                        <em class="base-14 icon-stack-2x color-primary-600 opacity-70"></em>
                        <em class="fal <?php echo $data['modulo']['icono'] ?> icon-stack-1x text-white opacity-90"></em>
                    </span>
                </div>
                <div class="d-flex flex-fill">
                    <div class="flex-fill">
                        <span class="h5"><?php echo $data['modulo']['nombre'] ?></span>
                        <br>
                        <ul class="list-submenus">
                            <?php if(!empty($data['submodulos'])) : foreach($data['submodulos'] as $submodulo) : ?>
                            <li><a href="/<?php echo $data['modulo']['ruta']."/".$submodulo['ruta']; ?>"><em class="fal <?php echo $submodulo['icono']; ?>"></em> <?php echo $submodulo['nombre']; ?></a></li>
                            <?php endforeach; endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; endif; ?>
</div>