<img src="img/logo-login.png" class="logo-login">

<form id="form-login" autocomplete="off" data-accion="/login" data-callback="resultado(response);">
    <div class="form-group">
        <label class="form-label">Usuario</label>
        <div><input type="text" id="usuario" name="usuario" class="form-control form-control-lg"></div>
    </div>
    <div class="form-group">
        <label class="form-label">Contraseña</label>
        <div><input type="password" id="contrasena" name="contrasena" class="form-control form-control-lg"></div>
    </div>
    <div class="form-group text-left">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="rememberme" name="remember_me">
            <label class="custom-control-label" for="rememberme"> Recordar Sesión</label>
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-lg-12 pr-lg-1 my-2">
            <button type="submit" class="btn btn-info btn-login btn-block btn-lg" data-id-form="form-login"><i class="fas fa-spinner fa-spin hidden"></i> <span>Iniciar Sesión</span></button>
            <div class="mensaje-login alert" role="alert"></div>
        </div>
    </div>
</form>

<script>

$("#form-login").validate({
    rules: {
        usuario: {
            required: true
        },
        contrasena: {
            required: true
        }
    },
    messages: {
        usuario: {
            required: 'Por favor, ingrese su usuario'
        },
        contrasena: {
            required: 'Por favor, ingrese su contraseña'
        }
    },
    errorPlacement: function (error, element) {
        error.insertAfter(element.parent());
    }
});

</script>