<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Buscador</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/buscador/guardar-editar-buscador?idbuscador=<?php echo $this->idbuscador; ?>" data-callback="respuesta(response, 'Buscador actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
        <div class="form-group">
            <label class="form-label">Feria</label>
            <span>
                <select class="select2 form-control" name="idferias">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <?php foreach($this->ferias as $item):?>
                    <option value="<?php echo $item['idferias'];?>" data-idplataformas="<?php echo $item['idplataformas']; ?>" data-idplanes="<?php echo $item['idplanes']; ?>" <?php if( $this->idferias == $item['idferias'] ) echo "selected='select'"; ?>><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <?php endif; ?>
        <!-- <div class="form-group">
            <label class="form-label">Tipo</label>
            <span class="disabled">
                <select class="select2 form-control" name="tipo">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="P" <?php if( $this->tipo == 'P' ) echo "selected='select'"; ?>>Producto</option>
                    <option value="S" <?php if( $this->tipo == 'S' ) echo "selected='select'"; ?>>Speaker</option>
                </select>
            </span>
        </div> -->
        <div class="form-group">
            <label class="form-label">Empresa</label>
            <span>
                <select class="select2 form-control" name="idempresas">
                    <option value="" selected="select">Seleccionar...</option>
                    <?php foreach($this->empresas as $item):?>
                    <option value="<?php echo $item['idempresas'];?>" <?php if( $this->idempresas == $item['idempresas'] ) echo "selected='select'"; ?>><?php echo $item['nombre'];?></option>
                    <?php endforeach;?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Nombre</label>
            <span>
                <input type="text" name="nombre" class="form-control" value="<?php echo $this->nombre; ?>">
            </span>
        </div>
        <div class="form-group" style="<?php echo ( $this->idempresas === '0' ) ? 'display: none' : ''; ?>">
            <label class="form-label">Descripción</label>
            <span>
                <input type="text" name="descripcion" class="form-control" value="<?php echo $this->descripcion; ?>">
            </span>
        </div>
        <div class="form-group" style="<?php echo ( $this->idempresas !== '0' ) ? 'display: none' : ''; ?>">
            <label class="form-label">Enlace</label>
            <span>
                <input type="text" name="enlace" class="form-control" value="<?php echo $this->enlace; ?>">
            </span>
        </div>
        <div class="form-group" style="<?php echo ( $this->idempresas === '0' ) ? 'display: none' : ''; ?>">
            <label class="form-label">Enlace Whatsapp</label>
            <span>
                <input type="text" name="enlace_wsp" class="form-control" value="<?php echo $this->enlace_wsp; ?>">
            </span>
        </div>
        <div class="form-group" style="<?php echo ( $this->idempresas === '0' ) ? 'display: none' : ''; ?>">
            <div class="custom-control custom-checkbox custom-control-inline mt-1">
                <input type="checkbox" name="pagina_envivo" value="1" class="custom-control-input" id="defaultInline1" <?php if($this->pagina_envivo != '0') echo 'checked="checked"';?>>
                <label class="custom-control-label" for="defaultInline1"><span class=""></span> En vivo</label>
            </div>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-images"></i>&nbsp;Imagen</h2>
        </div>
        <div class="form-group">
            <div class="contenedor-imagen-personalizado">
                <img src="<?php echo ( $this->hash_imagen != '' ) ? 'buscador/imagen/'.$this->hash_imagen.'?t='.time() : 'img/no-imagen.jpg'; ?>" width="300" class="imagen">
                <div class="panel-tag panel-tag--alert-danger mb-5 mt-5">Imagen recomendada de 590 px de ancho y 700 px de alto</div>
                <button type="button" class="btn btn-dark btn-block cambiar-imagen-personalizado"><i class="fas fa-upload"></i> Cambiar Imagen</button>
                <input type="file" data-width="590" data-height="700" onchange="cambiarImagenDimension(this, event);" class="hidden" name="imagen" accept=".jpg,.jpeg,.png" style="display: none;">
                <div class="hidden mensaje">La imagen que intenta subir, no cumple con las dimensiones recomendadas. Intente otra vez.</div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    var selectFeria = $("select[name='idferias']");
    var selectTipo = $("select[name='tipo']");
    var selectEmpresa = $("select[name='idempresas']");
    var inputEnlace = $("input[name='enlace']");
    var inputEnlaceWsp = $("input[name='enlace_wsp']");
    var inputDescripcion = $("input[name='descripcion']");
    var checkboxEnVivo = $("input[name='pagina_envivo']");

    selectFeria.change(function(){
        let idplataformas = $(this).find("option:selected").attr("data-idplataformas");
        if(idplataformas === "2"){
            checkboxEnVivo.prop("checked", true).parent().addClass("disabled");
        } else {
            checkboxEnVivo.prop("checked", false).parent().removeClass("disabled");;
        }
    });

    selectEmpresa.change(function(){
        if( $(this).val() !== '' ){
            inputEnlaceWsp.parent().parent().show();
            inputEnlace.parent().parent().hide();
            inputDescripcion.parent().parent().show();
            checkboxEnVivo.parent().parent().show();
        } else {
            inputEnlaceWsp.parent().parent().hide();
            inputEnlace.parent().parent().show();
            inputDescripcion.parent().parent().hide();
            checkboxEnVivo.parent().parent().hide();
        }
    });

    $(".btn-archivo").click(function(){
        $(this).parent().find("input[type='file']").click();
    });

    var File = {
        upload: function(obj, event){
            let contenedor = $(obj).parent();
            let btnArchivo = contenedor.find(".btn-archivo");
            let btnEliminar = contenedor.find(".btn-eliminar");
            let btnDescargar = contenedor.find(".btn-descargar");
            let inputFile = contenedor.find("input[type='file']");
            let validFiles = inputFile.attr("valid-file").split(",");
            if(event.target.files.length){
                if( validFiles.indexOf(event.target.files[0].type) == -1 ){
                    this.message('invalid-format', 'warning');
                    this.restore(obj);
                    return;
                }
                if( event.target.files[0].size > 5000000 ) {
                    this.message('invalid-size', 'warning');
                    this.restore(obj);
                    return;
                }
                btnArchivo.text("Cambiar archivo");
                btnEliminar.show();
            } else {
                this.restore(obj);
            }
        },
        delete: function(obj) {
            this.restore(obj);
        },
        restore: function(obj) {
            let contenedor = $(obj).parent();
            let btnArchivo = contenedor.find(".btn-archivo");
            let btnEliminar = contenedor.find(".btn-eliminar");
            let inputFile = contenedor.find("input[type='file']");
            btnArchivo.text("Seleccionar archivo");
            btnEliminar.hide();
            inputFile.val('');
        },
        message: function(type, typeMessage){
            switch(type){
                case 'invalid-format': alerta("El tipo de formato no es valido. Por favor, vuelva a intentarlo.", typeMessage); break;
                case 'invalid-size': alerta("El peso máximo no es valido. Por favor, vuelva a intentarlo.", typeMessage); break;
            }
        }
    }

    $(".cambiar-imagen-personalizado").click(function () {
        $(this).parent().find("input[type='file']").click();
    });

    var _URL = window.URL || window.webkitURL;

    function cambiarImagenDimension(obj, event){
        var contenedor = $(obj).parent();
        var reader = new FileReader();
        var img = contenedor.find("img");
        var img_width = parseInt($(obj).attr("data-width"));
        var img_height = parseInt($(obj).attr("data-height"));
        var mensaje = contenedor.find(".mensaje").text();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = function (e) {
            var image = new Image();
            image.src = e.target.result;
            image.onload = function () {
                var width = this.width;
                var height = this.height;
                if (width != img_width || height != img_height) {
                    alert(mensaje);
                    $(obj).val('');
                    img.attr("src", "img/no-imagen.jpg");
                    return false;
                }
                img.attr("src", e.target.result);
            };
        }
    }

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            nombre: {
                required: true
            },
            tipo: {
                required: true
            },
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: true
            }
            <?php endif;?>
        },
        messages: {
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            tipo: {
                required: 'Por favor, seleccionar el tipo'
            },
            <?php if( $this->layout()->datosUsuario['idperfil'] == 1 ) :?>
            idferias: {
                required: 'Por favor, seleccione la feria'
            }
            <?php endif;?>
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>