<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Agregar Menus</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/mantenimiento/guardar-agregar-menus" data-callback="respuesta(response, 'Menus agregado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Tipo</label>
            <span>
                <select class="select2 form-control" name="tipo">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="E">Encabezado (Interacción de la Feria)</option>
                    <option value="PP">Pie de Página (Interacción del Stand)</option>
                </select>
            </span>
        </div>  
        <div class="form-group">
            <label class="form-label">Nombre</label>
            <span>
                <input type="text" name="nombre" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">URL</label>
            <span>
                <input type="text" name="hash_url" class="form-control">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Posición</label>
            <span>
                <select class="select2 form-control" name="posicion">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="H">HOME</option>
                    <option value="R">REGISTRO</option>
                    <option value="C">CONTENIDO</option>
                </select>
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Agregar Menus</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            tipo: {
                required: true
            },
            nombre: {
                required: true
            },
            posicion: {
                required: true
            }
        },
        messages: {
            tipo: {
                required: 'Por favor, seleccione el tipo'
            },
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            posicion: {
                required: 'Por favor, seleccione la posición'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>