<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Planes</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/mantenimiento/guardar-editar-planes?idplanes=<?php echo $this->idplanes; ?>" data-callback="respuesta(response, 'Planes actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Nombre</label>
            <span>
                <input type="text" name="nombre" class="form-control" value="<?php echo $this->nombre; ?>">
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-grip-horizontal"></i>&nbsp;Zonas</h2>
        </div>
        <div class="form-group">
            <label class="form-label">Cantidad</label>
            <span>
                <input type="number" name="cantidad_zonas" min="1" class="form-control" value="<?php echo $this->cantidad_zonas; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Cantidad Empresas por Zonas</label>
            <span>
                <input type="number" name="cantidad_empresas_zonas" min="1" class="form-control" value="<?php echo $this->cantidad_empresas_zonas; ?>">
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-pager"></i>&nbsp;Páginas Personalizables</h2>
        </div>
        <div class="form-group">
            <span>
                <select class="select2 form-control" multiple="multiple" name="idpaginas[]">
                    <?php foreach($this->paginas as $item) : ?>
                    <option value="<?php echo $item['idpaginas']; ?>" <?php if( in_array( $item['idpaginas'], $this->idpaginas ) ) echo 'selected="select"'; ?>><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </span>
        </div>
        <div class="panel-hdr">
            <h2><i class="fas fa-fw fa-lg fa-th-list"></i>&nbsp;Menus</h2>
        </div>
        <div class="form-group">
            <label class="form-label">Encabezados: Interacción de la Feria</label>
            <span>
                <select class="select2 form-control" multiple="multiple" name="idmenus[]">
                    <?php foreach($this->menus as $item) : if( $item['tipo'] == 'PP' )continue; ?>
                    <option value="<?php echo $item['idmenus']; ?>" <?php if( in_array( $item['idmenus'], $this->idmenus ) ) echo 'selected="select"'; ?> ><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Pie de Páginas: Interacción del Stand</label>
            <span>
                <select class="select2 form-control" multiple="multiple" name="idmenus[]">
                    <?php foreach($this->menus as $item) : if( $item['tipo'] == 'E' )continue; ?>
                    <option value="<?php echo $item['idmenus']; ?>" <?php if( in_array( $item['idmenus'], $this->idmenus ) ) echo 'selected="select"'; ?> ><?php echo $item['nombre']; ?></option>
                    <?php endforeach; ?>
                </select>
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $('.select2').select2();

    $("#validar_formulario").validate({
        rules: {
            nombre: {
                required: true
            },
            cantidad_zonas: {
                required: true,
                min: 1
            },
            cantidad_empresas_zonas: {
                required: true,
                min: 1
            }
        },
        messages: {
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            cantidad_zonas: {
                required: 'Por favor, ingrese la cantidad de zonas',
                min: 'Por favor, escribe un valor mayor o igual a {0}.'
            },
            cantidad_empresas_zonas: {
                required: 'Por favor, ingrese la cantidad de empresas',
                min: 'Por favor, escribe un valor mayor o igual a {0}.'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>