<style>
    
</style>

<div class="modal-header">
    <h4 class="modal-title">Editar Menus</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fas fa-times"></i></span>
    </button>
</div>

<form id="validar_formulario" data-accion="/mantenimiento/guardar-editar-menus?idmenus=<?php echo $this->idmenus; ?>" data-callback="respuesta(response, 'Menus actualizado correctamente.')" autocomplete="off">
    <div class="modal-body">
        <div class="form-group">
            <label class="form-label">Tipo</label>
            <span>
                <select class="select2 form-control" name="tipo">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="E" <?php if( $this->tipo == 'E' ) echo "selected='select'"; ?>>Encabezado (Interacción de la Feria)</option>
                    <option value="PP" <?php if( $this->tipo == 'PP' ) echo "selected='select'"; ?>>Pie de Página (Interacción del Stand)</option>
                </select>
            </span>
        </div>  
        <div class="form-group">
            <label class="form-label">Nombre</label>
            <span>
                <input type="text" name="nombre" class="form-control" value="<?php echo $this->nombre; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">URL</label>
            <span>
                <input type="text" name="hash_url" class="form-control" value="<?php echo $this->hash_url; ?>">
            </span>
        </div>
        <div class="form-group">
            <label class="form-label">Posición</label>
            <span>
                <select class="select2 form-control" name="posicion">
                    <option value="" selected="select" disabled="">Seleccionar...</option>
                    <option value="H" <?php if( $this->posicion == 'H' ) echo "selected='select'"; ?>>HOME</option>
                    <option value="R" <?php if( $this->posicion == 'R' ) echo "selected='select'"; ?>>REGISTRO</option>
                    <option value="C" <?php if( $this->posicion == 'C' ) echo "selected='select'"; ?>>CONTENIDO</option>
                </select>
            </span>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-info btn-submit btn-uploader-form" data-id-form='validar_formulario'>Guardar Cambios</button>
    </div>
</form>

<script>

    $(".select2").select2();

    $("#validar_formulario").validate({
        rules: {
            tipo: {
                required: true
            },
            nombre: {
                required: true
            },
            posicion: {
                required: true
            }
        },
        messages: {
            tipo: {
                required: 'Por favor, seleccione el tipo'
            },
            nombre: {
                required: 'Por favor, ingrese el nombre'
            },
            posicion: {
                required: 'Por favor, seleccione la posición'
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.parent());
        }
    });

</script>