<div class="panel">
    <div class="panel-container show">
        <div class="panel-content">
            <table id="dataTables" class="table table-bordered table-hover table-striped w-100">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th width="180">Opciones</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

<script>

    <?php $this->inlineScript()->captureStart(); ?>

    var tablaOpcionIzquierda = '';
    var tablaOpcionDerecha = '';
    var responsiveHelper_dataTables = undefined;
    var dataTable;
    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };
    dataTable = $('#dataTables').dataTable({
        "ajax": "/mantenimiento/listar-paginas",
        "sDom": "<'row'<'col-xs-11 col-sm-6 tabla-opciones-izquierda'f><'col-sm-6 col-xs-1 tabla-opciones-derecha'>r>" +
                "t" +
                "<'row'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth": false,
        "oLanguage": {
            "sUrl": "js/datagrid/datatables/Spanish.json",
        },
        "aoColumnDefs": [
            {"bSortable": false, "aTargets": [1]}
        ],
        "preDrawCallback": function () {
            if (!responsiveHelper_dataTables) {
                responsiveHelper_dataTables = new ResponsiveDatatablesHelper($('#dataTables'), breakpointDefinition);
            }
        },
        "rowCallback": function (nRow) {
            responsiveHelper_dataTables.createExpandIcon(nRow);
        },
        "drawCallback": function (oSettings) {
            responsiveHelper_dataTables.respond();
            tablaOpcionIzquierda = $(".tabla-opciones-izquierda");
            tablaOpcionDerecha = $(".tabla-opciones-derecha");
        },
        "ordering": false,
        responsive: true
    });

    $(document).ready(function () {
        setTimeout(function(){
            
            tablaOpcionIzquierda.find(".input-group-addon").addClass("input-group-text d-inline-flex width-3 align-items-center justify-content-center border-bottom-right-radius-0 border-top-right-radius-0 border-right-0");
            tablaOpcionIzquierda.find(".input-group-addon").find("i").removeAttr("class").addClass("fal fa-search");
            tablaOpcionIzquierda.find("input[type='search']").attr("placeholder", "Buscar");
            tablaOpcionDerecha.append('<div class="opciones">'+
                '<button type="button" class="btn btn-info pop-up" href="/mantenimiento/agregar-paginas"><i class="fas fa-plus"></i> <span class="hidden-xs">Agregar Páginas</span></button> '+
            '</div>');

        }, 700);
    });

    function listarDatos() {
        dataTable.api().ajax.reload(null, false);
    }

    function respuesta(response, mensaje) {
        ocultarModal();
        if (response.result == 'success') {
            listarDatos();
            alerta(mensaje, 'success');
        }
    }

    $(document).on("click", ".flecha-arriba", function(){
        let contenedorFilaPortada = $(this).parents("tr");
        if(contenedorFilaPortada.prev().clone().length == 0)return;
        $(contenedorFilaPortada.clone()).insertBefore(contenedorFilaPortada.prev());
        contenedorFilaPortada.remove();
        guardarOrden();
    });

    $(document).on("click", ".flecha-abajo", function(){
        let contenedorFilaPortada = $(this).parents("tr");
        if(contenedorFilaPortada.next().clone().length == 0)return;
        $(contenedorFilaPortada.clone()).insertAfter(contenedorFilaPortada.next());
        contenedorFilaPortada.remove();
        guardarOrden();
    });

    function guardarOrden(){
        var data = [];
        var i = 1; 
        $("#dataTables tbody tr").each(function(){
            let ids = $(this).find(".opciones-flechas").attr("data-ids");
            data.push({ids: ids, orden: i});
            i++;
        });
        console.log(data);
        $.post('/mantenimiento/guardar-orden-paginas', {orden: data}, function(response){

        }, 'json');
    }

    <?php $this->inlineScript()->captureEnd(); ?>

</script>